### ISSUE TITLE
请问一下那个ftp的py为什么运行不起来？

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#1]
@K-Guan

**Comment by K-Guan** [comment]
那个？那个是哪个？

**Comment by K-Guan** [comment]
哦，你是用Python2运行的？那是一个Python2的脚本。

**Comment by redapple0204** [comment]
@K-Guan 好的，那么请问为啥在windows下py2和py3无法共存

**Comment by K-Guan** [comment]
唉？怎么会？有报什么错嘛？

**Comment by redapple0204** [comment]
@K-Guan python2的path添加不进去，导致无法用cmd执行

**Comment by redapple0204** [comment]
@K-Guan 找到解决办法了，谢谢

**Comment by K-Guan** [comment]
啊，那就好。

**Comment by redapple0204** [comment]
@K-Guan 那么，再请问一下，有没有办法让那个py加上上传功能呢？

**Comment by K-Guan** [comment]
这个嘛我就不知道了，你那个用的是`SimpleHTTPServer`，Google下文档或许有帮助。

**Comment by redapple0204** [comment]
@K-Guan 好的
