### ISSUE TITLE
话说您有什么好的vpn推荐吗

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#10]
@K-Guan hosts对一些网站的支持还是不好（例如github访问会页面错乱，要vpn才正常）

**Comment by K-Guan** [comment]
并没有。不过我倒是确实在使用 VPN （hosts 我早已不用了，但是我还在维护），但是是付费 VPN （不过速度特别快还不会有被墙的问题，如果经济不成问题的话可以考虑弄一个）。

说起来你不是一直都说你有 VPN 用么？难道出问题了？

**Comment by redapple0204** [comment]
@K-Guan 那请问您的vpn用的是什么呢？我的vpn并没有linux版本。

**Comment by redapple0204** [comment]
@K-Guan 似乎很多的vpn都不推出linux版本或者稳定性太差

**Comment by K-Guan** [comment]
我使用的是 [**PIA**](https://wiki.archlinux.org/index.php/Private_Internet_Access_VPN)，只需要 `openvpn` 就可以了。全平台兼容的。

**Comment by redapple0204** [comment]
@K-Guan 那请问您用的是什么品牌的vpn呢，还是自己搭的？

**Comment by K-Guan** [comment]
就是 PIA，[The Private Internet Access VPN](https://www.privateinternetaccess.com/) 嘛。

**Comment by redapple0204** [comment]
@K-Guan 好的，我去看看

**Comment by redapple0204** [comment]
@K-Guan 话说。。这是美元还是人民币，能用银行卡嘛（中国的）

**Comment by K-Guan** [comment]
这个……怎么付费我没考虑。好像只支持 PayPal 和一大堆我不认识的付费方式，而且标价是美元……

**Comment by redapple0204** [comment]
@K-Guan 一年180.。勉强接受；paypal？我看看
>>> （不是还有比特币吗）

**Comment by K-Guan** [comment]
我先说好啊，是不是真的好用我可不敢打包票。不过我个人用着特别快就是了。

**Comment by redapple0204** [comment]
@K-Guan 您用着好用肯定好用

**Comment by redapple0204** [comment]
@K-Guan 您用着好用肯定好用

**Comment by K-Guan** [comment]
的了吧，没事少恭维我。那你就试试看吧。

**Comment by redapple0204** [comment]
@K-Guan 好的

**Comment by K-Guan** [comment]
说说你吧。话说你为什么一直跟着我学编程？比我厉害的高手明明也多了去了。

**Comment by redapple0204** [comment]
@K-Guan 因为您最耐心啊，在别的地方随便问一下没有人会回答。

**Comment by K-Guan** [comment]
（嗯，我确实是闲的慌）

**Comment by redapple0204** [comment]
@K-Guan 其实你好厉害...以前在贴吧上几乎每时每刻都在水还学习到那么多（我说去年暑假）

**Comment by K-Guan** [comment]
那也都是技术水。“本人新开发的程序有润肠通便的作用”比起“今天的天气估计吃饭比较香”是不一样的。

**Comment by redapple0204** [comment]
@K-Guan 无聊水真的好无聊。。。

**Comment by K-Guan** [comment]
确实，其实技术水也没啥意思，所以还是走为上策。

**Comment by redapple0204** [comment]
@K-Guan 去so水肯定很有意思

**Comment by K-Guan** [comment]
嗯，那看怎么个水法。在主论坛乱水号不被封就怪了。

**Comment by redapple0204** [comment]
@K-Guan >>>去聊天室水总可以吧

**Comment by K-Guan** [comment]
嗯，但是得看是谁的聊天室（你自己的或经过同意的话随便你）。而且还是注意言语不能是 rude or spam or offensive.
