### ISSUE TITLE
还有一周....

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#101]
颓废啊....
@lizongzeshunshun

**Comment by lizongzeshunshun** [comment]
@redapple0204 如何

**Comment by lizongzeshunshun** [comment]
顺便，有没有什么关于阅卷的信息和试卷答案

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.勉强吧....数学炸了
2.我们不参加多校联考&区统考，so....

**Comment by redapple0204** [comment]
@lizongzeshunshun 另外：罗湖区改卷网站
219.223.108.40

**Comment by lizongzeshunshun** [comment]
@redapple0204 我数学也炸了！对不起数学老师！

**Comment by lizongzeshunshun** [comment]
写到最后一题还剩8分钟 然后写出了(1),(3)问，选择填空还各错一道！估计90都没了

**Comment by lizongzeshunshun** [comment]
这回真是没想到，其他都考得不错，就死在数学上

**Comment by redapple0204** [comment]
@lizongzeshunshun 我是前面写的差不多，写到最后一题只剩下5分钟，勉强写完第一个问...
不敢对答案，估计也没90.

**Comment by redapple0204** [comment]
@lizongzeshunshun 老师已经给我们提示了，说会很难。没想到花的时间那么长

**Comment by redapple0204** [comment]
帮你找了部分答案，你先看看是不是，正在上传

**Comment by redapple0204** [comment]
[daan.tar.gz](https://github.com/redapple0204/my-boring-python/files/696316/daan.tar.gz)

**Comment by redapple0204** [comment]
另：
[阅卷IP地址及相关说明（7、8年级期末联考）.docx.tar.gz](https://github.com/redapple0204/my-boring-python/files/696327/IP.7.8.docx.tar.gz)

**Comment by lizongzeshunshun** [comment]
k

**Comment by redapple0204** [comment]
@lizongzeshunshun ？？

**Comment by lizongzeshunshun** [comment]
1. ok
2. 数学这回真完了

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.“ok”是啥？？
2.why....很多错？

**Comment by lizongzeshunshun** [comment]
1. 就是对你给我的文件说 好的
2. 选择1题填空1题还有应用题倒数第二题的第二小问步骤倒数第一题的第二小问全部以及第三小问步骤
初步估计88吧

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.哦....
2.有时候罗湖区统考很**，随便打分。
可能差不多对了都回答满分吧

**Comment by lizongzeshunshun** [comment]
哎.....
顺便问一下现在改得怎样了什么时候会出

**Comment by redapple0204** [comment]
@lizongzeshunshun 明天上午能出（内部）（事实上现在应该已经出了，但是没统计），被泄露是明天下午

**Comment by lizongzeshunshun** [comment]
嗯。。。数学不知道怎么跟老师解释了

**Comment by redapple0204** [comment]
@lizongzeshunshun 你们那还好，至少不会怎么样猛烈的骂人...
我们这里数学老师超级势利，一考不好直接在课堂上破口大骂....

**Comment by lizongzeshunshun** [comment]
。。。虽然说还好但是我从来没考过那么差，肯定要被批了。。。。只是希望不要批得太惨

**Comment by redapple0204** [comment]
90 左右还算好了....至少比得上中上水平

**Comment by redapple0204** [comment]
哎..考完就考完了

**Comment by lizongzeshunshun** [comment]
嗯.....坐和放宽

**Comment by redapple0204** [comment]
~~再怎么放宽也之有一天了，哎.....~~
为啥中学改卷那么快

**Comment by lizongzeshunshun** [comment]
...

**Comment by redapple0204** [comment]
@lizongzeshunshun 话说你们今年生地好简单
几乎都是抄我们那一本复习书的
特别是第73题直接复制过来，竟然没发现软件动物......

**Comment by lizongzeshunshun** [comment]
哈哈哈软件动物

另：73题我不服，正确答案只有A

**Comment by lizongzeshunshun** [comment]
比如蜗牛，是~~软件动物~~软体动物，但是不生活在水中啊...

**Comment by redapple0204** [comment]
我当初也是则么认为的，但是问老师她说
>C选项指的是在水中生活的双壳类动物

**Comment by lizongzeshunshun** [comment]
这是强词夺理吧，而且这题我查过，是一道单选题，答案是A

**Comment by redapple0204** [comment]
@lizongzeshunshun 你看看查的题目，是不是删掉&更改了几个词
总的来说，出题人语文太差

**Comment by lizongzeshunshun** [comment]
除了“软体”和“软件”这两个字，一字不差

**Comment by redapple0204** [comment]
网上的题目
>C. 软体动物生活在水中，靠入水管、出水管获取水里的食物颗粒
现在的题目
>C. ~~软件~~软体动物生活在水中，双壳类动物靠入水管、出水管获取水里的食物颗粒

**Comment by lizongzeshunshun** [comment]
没错。但是他仍然一定了“软体动物生活在水中”这个错误的命题呀。

**Comment by redapple0204** [comment]
很大几率表达错误
不过这次出题也是机构随便复制的，即使有错误也没办法...

**Comment by lizongzeshunshun** [comment]
真是乱搞。。。

**Comment by lizongzeshunshun** [comment]
我想它应该想这样说“软体动物中，双壳类生活在水中并且靠入水管、出水管获取水里的食物颗粒。”这样就是对的。

**Comment by redapple0204** [comment]
@lizongzeshunshun 老师给的解释就是这样...

**Comment by lizongzeshunshun** [comment]
然而原题还是错的。。。

**Comment by redapple0204** [comment]
@lizongzeshunshun 对啊，这种考试审题人都没有

**Comment by lizongzeshunshun** [comment]
中国这教育就是考试，这也就算了，考试出题还出错题这我就..............

**Comment by redapple0204** [comment]
@lizongzeshunshun 其实这是教育机构出的题....又想赚钱又不想出力就copy paste喽
表示学校自己出题好
另：初三就便成罗湖区老师出题了

**Comment by lizongzeshunshun** [comment]
哎。。。这点力的不愿意出。我觉得我现在都能出一套卷子了。。

**Comment by lizongzeshunshun** [comment]
按错..

**Comment by redapple0204** [comment]
@lizongzeshunshun 学到这种水平真的能出了....
出多点力？那要花至少1000元，那种机构不会出的

**Comment by lizongzeshunshun** [comment]
失望...

**Comment by redapple0204** [comment]
恩.....
（刚在知乎上看到一个答案，顺手备份到这里吧....）
>不作弊如何过得好。

>不作弊如何让同学服我？
不作弊如何让老师宽容待我？
不作弊如何承受得住家长的逼迫？
不作弊如何在学校里过得好？

>没有办法啊。
成绩太重要了，比什么都重要。
比友情重要。比健康重要。比良心重要。比人格重要。比生命重要。
不作弊如何活得好？
若我天资有限，我如何争得过他们？
如何甘心？如何甘心！

>说到底，成绩太重要。
好像我不用只凭成绩得到正视和安全我愿意作弊一样。
----------------分割线----------------
我很敬重不作弊的人。
但那些坚持自我的人们啊，不要自傲不要炫耀了，这本是你应该做的，你不这样认为吗？





>----------------分割线----------------

>再多说几句。
本人大概是目前此问题下唯一好好回答为毛作弊的家伙了。
现在说点不对题的。


>出题者（指让他人考试者）之所以禁止作弊，是因为他们不考察作弊能力。并且，作弊会模糊考试者的能力水平。
说具体一点，考门英语，那一位不作弊，试卷表现的是ta的英语水平；在下作弊，那么试卷表现的是在下的作弊水平。
这就麻烦了。所以出题者禁止作弊。

>行，今儿个扯完了，改天再来扯一扯。
点赞的同学们记得匿名，毕竟这答案三观不正。

>作者：匿名用户
链接：https://www.zhihu.com/question/22133858/answer/38139222
来源：知乎
著作权归作者所有，转载请联系作者获得授权。

**Comment by lizongzeshunshun** [comment]
嗯。

毕竟考都考完了，没什么好后悔的了。希望开学考能有好成绩吧。

还是那句经典：

> **Never give up and you will be successful.** ——Mr. Li**

Failure IS success. 加油。

**Comment by redapple0204** [comment]
开学考？悲哀....
这句话肯定是编书的人加的...

**Comment by lizongzeshunshun** [comment]
有成绩消息希望及时通知我，谢谢@redapple0204

**Comment by redapple0204** [comment]
![qq 20170112132346](https://cloud.githubusercontent.com/assets/16254644/21878046/68416ca4-d8ca-11e6-8368-802d388688f9.png)

**Comment by lizongzeshunshun** [comment]
现在还有吗@redapple0204

**Comment by redapple0204** [comment]
能知道改完了，而且发到学校了
然而....我无法得到成绩

**Comment by lizongzeshunshun** [comment]
...只能相信原力与我同在了...

*I'm one with the Force. The Force is with me.*

**Comment by redapple0204** [comment]
我忽然想到了数年前的sudo pacman -Syu --force惨案...

**Comment by lizongzeshunshun** [comment]
666...

**Comment by lizongzeshunshun** [comment]
any news?@redapple0204

**Comment by redapple0204** [comment]
没...可以说我的极限是知道成绩已经下发给学校了
至于翠园的分数....我再那没有熟人也不知道

**Comment by lizongzeshunshun** [comment]
OK
