### ISSUE TITLE
我怀疑这次成绩有假

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#102]
好吧。。低估了自己的成绩，竟然还不错。

但是我觉得这次改卷有问题。

首先是历史：班平均分竟然降到了67，52分竟然还是B。然后有人选择错14题竟然还有86。
然后语文：很多语文学霸这次也只是拿到了高频数的平均分（76--81）。
然后是物理：1.我对了很多次是100,结果竟然96，很多人一样 2.有人对了94左右竟然97.6。
然后是英语：我不能相信我作文扣6--8分

@redapple0204

**Comment by redapple0204** [comment]
我妈说过
>罗湖区的联考的成绩往往不能显示你真实水平，因为首先出题人是教育机构，题目质量就没看有保证，再者老师又要在短时间内改完那么多卷子，大部分都是往平均分上靠，有的时候看你字写得不好直接就0分。

我觉得嘛....上面这些的确有道理，关于你觉的分数差异那么多，可能是因为1.选择题在扫描的时候有问题2.一般老师走的时候电脑都不会关，学生也喜欢动老师的电脑（这种事情在我们学校常有的）

我当年在翠园考数学也遇到过，明明能拿满分的试卷，然后硬生生给扣成了94分。
然而这种事情在我现在的学校没有发生。

所以：要获得学生的水平联考没用的。
不过嘛....等到下个学期就变成罗湖区统考，可能情况会好转。

**Comment by redapple0204** [comment]
另外【假】是一个梗...

**Comment by lizongzeshunshun** [comment]
就是想用这个梗@redapple0204
