### ISSUE TITLE
TO-DO list(2017.1-2)

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#104]
- [x] 整理“study”文件夹，进行学期分类
- [x] 删除多余的临时文件
~~- [ ] 完成“arch安装脚本（python）”任务~~ //目前水平无法达到

**Comment by redapple0204** [comment]
@lizongzeshunshun 你有什么好建议？

**Comment by lizongzeshunshun** [comment]
一个最近我会出一些关于fq的教程，再然后是写一个聊天工具（https://github.com/Class04OpenSourceORG/C4Chat）

**Comment by redapple0204** [comment]
@lizongzeshunshun fq我现在只能用tunnello+hosts了，lantern挂了
