### ISSUE TITLE
还是报错

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#108]
保存不成功
明明当时的arch想到都可以
>正在下载安装中，请稍等....
Traceback (most recent call last):
  File "arch_quick_install_software.py", line 36, in <module>
    data = urllib.request.urlopen(deepin_crossover_link).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 458, in open
    protocol = req.type
AttributeError: 'Response' object has no attribute 'type'

@lizongzeshunshun

**Comment by lizongzeshunshun** [comment]
..

**Comment by lizongzeshunshun** [comment]
你的py有问题吧

**Comment by redapple0204** [comment]
@lizongzeshunshun 你等他下载玩，看是不是会报错

**Comment by redapple0204** [comment]
@lizongzeshunshun 
>guanrenfu 9:54:17
requests和urllib.request.urlopen是两个不同的模块，但功能相似
guanrenfu 9:54:43
request.get()返回一个request的类……咳咳= =
guanrenfu 9:54:49
你去搜搜这两个模块的用法吧
guanrenfu 9:56:00
打个比方，你把本来就炸好的薯条又扔到炒锅里做炒土豆丝
guanrenfu 9:56:19
所以就没法吃了

**Comment by redapple0204** [comment]
修复完毕。
