### ISSUE TITLE
为啥会有mac&windows呢....

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#109]
不是只弄Linux[arch,debian]么？
@lizongzeshunshun

**Comment by redapple0204** [comment]
另外：是要主程序和下载捆绑还是分离？

**Comment by redapple0204** [comment]
oh, shit!什么鬼网络，github又被墙了

**Comment by redapple0204** [comment]
oh, shit!什么鬼网络，github又被墙了

**Comment by lizongzeshunshun** [comment]
奥 我想做个多平台的了。。

**Comment by lizongzeshunshun** [comment]
2. 啥意思

**Comment by redapple0204** [comment]
@lizongzeshunshun 
1.OK，不过windows几本没人用...
2.我的意思是，你想要
主程序→download.py→json

**Comment by lizongzeshunshun** [comment]
1. 嗯 去掉了OSX 
2. +

已经写好了 你测试下

**Comment by lizongzeshunshun** [comment]
说明：**必须**用python3.6+执行

看到
```
Setting up...
haha
example
Finished
```
既成功

**Comment by redapple0204** [comment]
》redapple@redapple ~/m/quickly_install_software> python3 autodown.py 
  File "autodown.py", line 25
    urllib.request.urlretrieve(link, f"./{saveName}")
                                                   ^
SyntaxError: invalid syntax
redapple@redapple ~/m/quickly_install_software>

**Comment by lizongzeshunshun** [comment]
@redapple0204 ..编码问题

**Comment by redapple0204** [comment]
@lizongzeshunshun 这个...我源里没有py3.6而且编译还出错...
能否转成3.x？

**Comment by lizongzeshunshun** [comment]
@redapple0204 这里用了3.6的一个新特性（print(f"xxx{xxx}")），你可以下载下来手动改成print("xxx"+xxx+"Xxx")

**Comment by redapple0204** [comment]
@lizongzeshunshun 好吧....3.6都相当于4了

**Comment by lizongzeshunshun** [comment]
。。。
