### ISSUE TITLE
啊，请问如果我要获取某个贴吧的所有帖子（或者前三页也行）要怎么做呢

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#11]
@K-Guan 用源代码似乎不太可行，因为看着很乱。。

**Comment by K-Guan** [comment]
这事别找我，我早就不在爬取贴吧上下功夫了。不过你不解析 HTML 你还想怎样？

现在去研究 BeautifulSoup ，顺便熟悉 HTML 。

**Comment by redapple0204** [comment]
@K-Guan 当我没说，不需要了（好的）

**Comment by redapple0204** [comment]
@K-Guan 当我没说，不需要了（好的）
