### ISSUE TITLE
百度好烦啊....

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#112]
百度云客户端限死10k
pcs限死700k.....
还让不让人下载东西了
@lizongzeshunshun

**Comment by lizongzeshunshun** [comment]
早已弃用。现在fq不是高峰期Google Drive都能下到7M/s

**Comment by redapple0204** [comment]
@lizongzeshunshun 我用百度云是为了下载【别人分享】的东西
我个人网盘当然不用啦。
另：GD只有15G，不符合我的要求，而且我经常要分享文件，但是GD要fq也不方便....
so...github扛着先

**Comment by lizongzeshunshun** [comment]
百度云国外速度好像不错（好久以前试过）可能海外CDN没限速。。七牛云倒是海外速度特别强，以前服务器下到过33M/s
