### ISSUE TITLE
。。。

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#113]
@redapple0204 跟他讲道理：http://tieba.baidu.com/p/4866397394?pid=102895285943&cid=102937777900#102937777900

**Comment by redapple0204** [comment]
@lizongzeshunshun 哦，这人是个喷子，今年暑假在linux吧搞事情被永封了，结果到这里了啊...
得，反正我闲着没事，吃完饭跟他喷喷= =

**Comment by redapple0204** [comment]
ps：当年似乎幸存了一个帖子
http://tieba.baidu.com/p/4793715088

**Comment by lizongzeshunshun** [comment]
666
