### ISSUE TITLE
...真是吃枣药丸

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#114]
@lizongzeshunshun 
![2017-01-22 21-00-20](https://cloud.githubusercontent.com/assets/16254644/22182660/ddbc53d6-e0e5-11e6-89de-eb0f68215972.png)

**Comment by lizongzeshunshun** [comment]
@redapple0204 1. link, please
2. 是VPN，没提SS哈哈哈...

**Comment by redapple0204** [comment]
1.http://www.williamlong.info/archives/4859.html
2.估计马上也要....

**Comment by redapple0204** [comment]
摘录...
>政府无限的权力，都是大部分人自己放弃的。假货坑爹，让政府审核。孩子管不好，让政府关网吧。有人在微博骂我，让政府去删。房价太高，让政府去限购。我们的文化实在太独特，创造出了家长式威权政府，GFW 正是在这种背景下产生的，一个社会矛盾的终极调和器，最终生活不能自理的你每天做的每一件事情都要给政府审查一遍，以免伤害到其他同样生活不能自理的人。这是一个零和游戏，越和这样的用户打交道，越对未来持悲观态度，觉得 GFW 可能永远也不会消失，而墙内的这个局域网看起来还似乎生机勃勃的自成一体，真是让人绝望。
