### ISSUE TITLE
中国的互联网啊.....excited！

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#115]
挂tunnello都没法看视频==
看来还得ss

**Comment by redapple0204** [comment]
我去挂vpn都没法上
这用了什么黑科技？？？
@lizongzeshunshun

**Comment by lizongzeshunshun** [comment]
@redapple0204 。。什么视频
另外那个人啊，还是too young ，sometimes naive,i'm angry!
(+1s

**Comment by redapple0204** [comment]
@lizongzeshunshun google-photos
不要天天想搞什么大新闻==

**Comment by lizongzeshunshun** [comment]
@redapple0204 我有ss你要吗

**Comment by redapple0204** [comment]
@lizongzeshunshun I have this ：https://doub.io/sszhfx/
ss刚刚试了下不会配置，等我晚上回来在好好研究...

**Comment by lizongzeshunshun** [comment]
@redapple0204 建议使用ssr
https://github.com/breakwa11/shadowsocks-rss

**Comment by lizongzeshunshun** [comment]
@redapple0204 兼容ss所有功能，还带混淆。

**Comment by redapple0204** [comment]
@lizongzeshunshun thx了
