### ISSUE TITLE
总觉的有些诡异

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#116]
回到家有一间房门关着
而且老发出一些奇怪的声音= = 
按理说今天的天气应该不会把房门吹关吧.....

**Comment by lizongzeshunshun** [comment]
@redapple0204 233 我也很多时候会这样

**Comment by lizongzeshunshun** [comment]
另外，那人不敢回了哈哈

**Comment by redapple0204** [comment]
反正我也仿喷子
让他恶心恶心

**Comment by redapple0204** [comment]
@lizongzeshunshun 那人又回你了==
你要学着像我一样，不要和他讲道理，和他耍无赖，让他哑口无言
