### ISSUE TITLE
寒假作业备份&完成情况

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#118]
### 语文：
- [x] 1.阅读训练：阅读套题训练6套（基础精练配套试卷）；
- [x] 2.阅读欣赏与积累：为你读诗6期；
- [x] 3.书法训练：书法纸6张；
- [x] 4.文言文背诵任务：岳阳楼记，背诵并默写（家长签字）；
- [x] 5.古诗词巩固：八下课外十首，背诵并默写（家长签字）
### 数学：
- [x] 七张试卷
### 英语：
- [x] I.阅读完成分层分级阅读B级.
- [x] II. 阅读teens13-20期, 完成PIV的Day1-5和PII-III的练习，参照后一期答案订正前一期，并在笔记本上摘录12-20期语言点荟萃。
- [x] II.预习朗读8下词汇表单词，每课10遍，家长签名。(已读※课+签名和日期)
- [x] III.复习Teens报纸1-10期词汇、短语，在听写本上分期听写签名。(已听写※课+签名和日期)
注：开学进行teens测试。请同学们认真阅读复习报纸。
### 历史：
- [x] 看大国崛起写读后感
### 生物：
- [ ] 完成《一本阅读》七年级上、下册的考点解读
### 物理：
 - [x] 新课堂B本

## PS:截止2017-02-13以前，请勿关闭该issue

**Comment by lizongzeshunshun** [comment]
地理什么鬼

**Comment by redapple0204** [comment]
@lizongzeshunshun 说复习这个学期学的内容

**Comment by redapple0204** [comment]
@lizongzeshunshun 完蛋了，才做了一半...

**Comment by lizongzeshunshun** [comment]
@redapple0204 目前完成68%，正在全速赶。。。。。。。。

**Comment by lizongzeshunshun** [comment]
我CPU已经满载了........._(:з」∠)_

**Comment by lizongzeshunshun** [comment]
我目前：

语文 - STATUS DOING - 30%
数学 - STATUS FROZEN - 65%
英语 - STATUS FROZEN - 60%
生物 - STATUS FINISHED - 100%
地理 - STATUS FROZEN - 0%
物理 - STATUS FINISHED - 100%
历史 - STATUS FROZEN - 0%

**Comment by redapple0204** [comment]
@lizongzeshunshun 我现在还在不急不慢地赶作业......
话说你不应该每颗都写一点么....
另外总感觉你们那里作业要少...
不过开学考是很悲哀的一件事情

**Comment by redapple0204** [comment]
我觉得我两天内能搞定...
赶作业的速度是惊人的

**Comment by lizongzeshunshun** [comment]
这就叫“Deadline”综合征。。

**Comment by lizongzeshunshun** [comment]
在Deadline之前效率最高

**Comment by lizongzeshunshun** [comment]
开学考我不管了，反正没啥，前5我就满意了

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.是啊，知乎上也这么说了
2.EXM？？？

**Comment by lizongzeshunshun** [comment]
2. ?

**Comment by redapple0204** [comment]
@lizongzeshunshun 年级前5...好厉害，应该是只被扣十几分吧

**Comment by lizongzeshunshun** [comment]
@redapple0204 班级。。。。。。。。

**Comment by redapple0204** [comment]
我还以为...

**Comment by lizongzeshunshun** [comment]
。。。。。。。

**Comment by redapple0204** [comment]
别关先...

**Comment by lizongzeshunshun** [comment]
点错了。。。

**Comment by lizongzeshunshun** [comment]
deadline真是第一生产力
我在寒假的最后10%完成了90%的作业。。。

**Comment by redapple0204** [comment]
@lizongzeshunshun 我也是，只剩下背诵和读后感了

**Comment by redapple0204** [comment]
@lizongzeshunshun 另外我都没到最紧急时期....
慢慢磨蹭下

**Comment by redapple0204** [comment]
终于要做完了，吼

**Comment by Guanrenfu** [comment]
test
