### ISSUE TITLE
我去！

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#120]
@lizongzeshunshun 
RE炸掉了！
![1](https://cloud.githubusercontent.com/assets/16254644/22360108/df1c89da-e487-11e6-95db-297cdc7f649b.PNG)

**Comment by lizongzeshunshun** [comment]
yes! i see just now

**Comment by redapple0204** [comment]
@lizongzeshunshun 别的项目好好的啊，为啥偏偏我们这个项目有问题？

**Comment by redapple0204** [comment]
我觉得原因有两个
1.我在RE里放了过多的个人文件，然后被发现
2.我上传了几何画板破解版，然而这玩意几何画板公司是yandade

**Comment by redapple0204** [comment]
手误

**Comment by lizongzeshunshun** [comment]
已经和Github提出交涉。等待即可

**Comment by redapple0204** [comment]
希望能恢复..要不就没有网盘可用了

**Comment by lizongzeshunshun** [comment]
...

**Comment by lizongzeshunshun** [comment]
reply from github



Hello,

That looks like a bug to me. 

I have passed it to our engineers and will update you when we roll out a fix.



> I can not access the release page of a repo(i'm a Collaborator), it reports ERROR 500
> 
> The link of the release page: https://github.com/redapple0204/my-boring-python/releases
> Repo's name: redapple0204/my-boring-python
> Main page of the repo: https://github.com/redapple0204/my-boring-python
> 
> Thanks!

**Comment by redapple0204** [comment]
@lizongzeshunshun 怎么感觉和国产软件一个德行？
另：这样的话就彻底的发现了我的网盘区域...

**Comment by lizongzeshunshun** [comment]
1. ？
2. 是啊

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.国产的软件给出的机器回复大都是这样的
2....

**Comment by lizongzeshunshun** [comment]
1. 没有啊这个回复很fashion啊。。

我试试翻译：

> 你好
> 依我看这是个Bug
> 我已经把它移交给工程部处理了，等好了我们会通知你。

**Comment by redapple0204** [comment]
这和国产软件说的
>我们已收到您反馈的消息，我们将会在第一时间修复好问题并反馈给您
有啥区别....

**Comment by lizongzeshunshun** [comment]
其实我省略了发信人的名字，后面有

**Comment by redapple0204** [comment]
但是国产软件也会回的...
例如
王xx  x年x月x日

**Comment by lizongzeshunshun** [comment]
@redapple0204 off365咋搞的

**Comment by redapple0204** [comment]
@lizongzeshunshun 

https://tpedutw-my.sharepoint.com/personal/redapple0204_tp_edu_tw/_layouts/15/guestaccess.aspx?docid=147b5f183868949e4ad447f50a72da662&authkey=AYqDWlvib-dhzAu_Ys0Rn8M

**Comment by redapple0204** [comment]
看到后请回复，我将删除上一楼

**Comment by lizongzeshunshun** [comment]
我直接删了

**Comment by redapple0204** [comment]
ok

**Comment by lizongzeshunshun** [comment]
GOOD!!

**Comment by redapple0204** [comment]
成功了？

**Comment by lizongzeshunshun** [comment]
嗯

还是低调点好

**Comment by redapple0204** [comment]
对啊...希望不要太快和谐
不过我们都申请成功了和谐应该没啥用...

**Comment by redapple0204** [comment]
其实我看中1T onedrive，office没啥用...又不能wine

**Comment by lizongzeshunshun** [comment]
233 
听说wine2.0 released

**Comment by redapple0204** [comment]
然而只能wine office2013（据说）

**Comment by redapple0204** [comment]
另外总觉得wine只是刷了个版本号

**Comment by lizongzeshunshun** [comment]
2013也不错了，算得上超大型软件了。。

**Comment by redapple0204** [comment]
但是原来都支持2010了...
但是2013又不能用365的key

**Comment by lizongzeshunshun** [comment]
@redapple0204 。。主要看中的还是1t

**Comment by redapple0204** [comment]
me too，1T在国外云盘很贵的

**Comment by lizongzeshunshun** [comment]
是啊

**Comment by lizongzeshunshun** [comment]
@redapple0204 
https://support.office.com/zh-cn/article/%E8%AE%BE%E7%BD%AE%E9%BB%98%E8%AE%A4-OneDrive-for-Business-%E5%AD%98%E5%82%A8%E7%A9%BA%E9%97%B4-cec51d07-d7e0-42a3-b794-9c00ad0f0083?ui=zh-CN&rs=zh-CN&ad=CN

看完请删除这条

**Comment by redapple0204** [comment]
？什么意思

**Comment by redapple0204** [comment]
@lizongzeshunshun 我没看出什么异常啊

**Comment by redapple0204** [comment]
看清楚了，是【设置】默认的，他怎么可能会给你更改网盘空间呢...
这样给你随便改成10000T不就完了
所以给你1T知足吧。。
