### ISSUE TITLE
release没希望了...

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#123]
对比审批速度....
这都拖了一天多了...
另：开RE可以用https://github.com/redapple0204/my-boring-python/releases/tag/【tag名】打开...
@lizongzeshunshun

**Comment by lizongzeshunshun** [comment]
........

**Comment by lizongzeshunshun** [comment]
话说这个OD For Business的API很难搞啊。。

**Comment by redapple0204** [comment]
有api么...
就算有，就微软这尿性，肯定难啦

**Comment by lizongzeshunshun** [comment]
。。。。。。。。。。。

**Comment by redapple0204** [comment]
...话说我觉得pentestbox像是另一个WSL了

**Comment by redapple0204** [comment]
在里面内置firefox for linux也是服..

**Comment by lizongzeshunshun** [comment]
。。。

**Comment by redapple0204** [comment]
@lizongzeshunshun 哇OD客户端好鸡肋啊，就像是MAC上的百度云同步盘
还不如网页端呢

**Comment by lizongzeshunshun** [comment]
网页端挺好的

**Comment by redapple0204** [comment]
是啊，而且最大竟然可以单文件10G
从没遇到过网页端能那么大的....
然而客户端还是给搞翻车了

**Comment by lizongzeshunshun** [comment]
。。。
