### ISSUE TITLE
准备制作一个自定义的archiso

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#124]
....用i3 然后添加wineqq，firefox等常用软件。。
控制x64和x86都要在700m以内。。
@lizongzeshunshun

**Comment by redapple0204** [comment]
xorg占用那么大....
药丸，看来不能添加桌面环境了，只能用fbterm勉强代替

**Comment by redapple0204** [comment]
![default](https://cloud.githubusercontent.com/assets/16254644/22404444/0ff606a4-e66c-11e6-8ad8-2ef48613ddfa.PNG)

**Comment by lizongzeshunshun** [comment]
ok

**Comment by redapple0204** [comment]
硬盘效率真低==
![default](https://cloud.githubusercontent.com/assets/16254644/22415836/523c0614-e705-11e6-8faf-aff1d2662ccf.PNG)

**Comment by redapple0204** [comment]
准备弃坑

**Comment by lizongzeshunshun** [comment]
..

**Comment by lizongzeshunshun** [comment]
Off365的OneNote不错啊，Office Online 也很好
成功对微软转粉...

还有好像大公司的产品前面都会加一个特定前缀
比如Apple: iOS iCloud iWatch...
Microsoft: OneDrive OneNote...

**Comment by redapple0204** [comment]
@lizongzeshunshun Onenote是？
另：如何下载OFF365的学生版，现在换回了win了...
微软相比国内的公司已经是非常良心了

因为前缀好看啊==
不过linux似乎没有

**Comment by redapple0204** [comment]
哦我知道了...
这和印象笔记有啥区别...

**Comment by lizongzeshunshun** [comment]
。。Google。。
还有一个东西 Chrome在我的Arch表现极差，经常卡死，OneDrive直接卡死，要切到tty2并且手动kill -9
相比，Firefox很稳定

**Comment by redapple0204** [comment]
@lizongzeshunshun arch上的chrome毛病多多......
要不是我看中了翻译谁会用他==

**Comment by redapple0204** [comment]
oh fuck
为啥自动就给我装office365
