### ISSUE TITLE
感觉百度云企业版还行

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#126]
...限速没有那么丧心病狂
![default](https://cloud.githubusercontent.com/assets/16254644/22495611/13c0c568-e87d-11e6-8275-1a59044652c5.PNG)
只可惜容量太小，只有50G==

**Comment by redapple0204** [comment]
不过总体感觉还是比OD差==

**Comment by lizongzeshunshun** [comment]
我百度云会员直接11m/s满速

**Comment by redapple0204** [comment]
你去买会员了啊....

**Comment by lizongzeshunshun** [comment]
去年不是说了吗。。去年3月

**Comment by redapple0204** [comment]
你买了一年？!
