### ISSUE TITLE
好吧，我要弄ss了

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#128]
@lizongzeshunshun 表示vpn插件开始收费了...
问题来了，话说我下载了ss-qt5，然后直接连接不行么？报错了
![default](https://cloud.githubusercontent.com/assets/16254644/22534989/e2585804-e932-11e6-9b29-8d952071779e.PNG)

**Comment by lizongzeshunshun** [comment]
上ssr啊

**Comment by lizongzeshunshun** [comment]
不要用qt  直接命令行

**Comment by redapple0204** [comment]
@lizongzeshunshun 这玩意？链接了没法上网了啊
![default](https://cloud.githubusercontent.com/assets/16254644/22535802/7621df1a-e938-11e6-8c98-6695d95f05b5.PNG)

**Comment by redapple0204** [comment]
就像这样没法上网
![default](https://cloud.githubusercontent.com/assets/16254644/22535919/26ed44b0-e939-11e6-803d-31d2e5fe2525.PNG)

**Comment by lizongzeshunshun** [comment]
没连服务器当然不行啊

**Comment by redapple0204** [comment]
@lizongzeshunshun 实际上我已经链接了，然后已连接就没法访问，已断开就能访问了

**Comment by lizongzeshunshun** [comment]
你是用ssr的那一条链接的吗

**Comment by lizongzeshunshun** [comment]
断开的时候访问肯定是直连

**Comment by lizongzeshunshun** [comment]
延迟错误说明无法连接数据有误

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.除了账号密码我都是用的默认设置
2.我换ssr以后没有延迟错误了，但是没法上网
话说你有时间tv下么//

**Comment by lizongzeshunshun** [comment]
现在在惠州 没电脑 过三天回去就行了

**Comment by redapple0204** [comment]
@lizongzeshunshun 好吧..你老家电脑全弄走了啊

**Comment by lizongzeshunshun** [comment]
不是 这不是我家 这是在惠州的一套房子

**Comment by redapple0204** [comment]
哦，去玩啊...

**Comment by redapple0204** [comment]
@lizongzeshunshun 噗....
我知道了，没法上网是因为他服务器流量用光了

**Comment by lizongzeshunshun** [comment]
。。。
