### ISSUE TITLE
免费的东西不靠谱

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#129]
挂了==
@lizongzeshunshun 
![4](https://cloud.githubusercontent.com/assets/16254644/22594712/21ee4f3c-ea5f-11e6-9f37-678a71ab4602.PNG)

**Comment by redapple0204** [comment]
终于好了...估计是抽了

**Comment by redapple0204** [comment]
这™还是心有余悸，幸好我只存放了分享的一些文件

**Comment by redapple0204** [comment]
还是翻车了==
账户被注销
![5](https://cloud.githubusercontent.com/assets/16254644/22595347/1a512daa-ea62-11e6-9d0c-a2e7fbd48980.PNG)
算了我还是乖乖地用mega吧...

**Comment by redapple0204** [comment]
神奇...突然恢复了

**Comment by lizongzeshunshun** [comment]
你登陆的位置不对

**Comment by lizongzeshunshun** [comment]
business的网盘很多地方不能登陆，因为它的api太复杂了

**Comment by redapple0204** [comment]
@lizongzeshunshun 我用了普通版的onedrive登陆==
果然不行

**Comment by lizongzeshunshun** [comment]
我的一直都很好，有一次速度飙满了

**Comment by redapple0204** [comment]
上午版一直都很好...
另：我怀疑昨天的登录失败又是几何画板公司搞的鬼，因为我把分享的文件放在了上面....
这公司查处力度好严啊，某论坛创始人因为我在上面发布破解版被查水表了= = 
![8](https://cloud.githubusercontent.com/assets/16254644/22615891/e7ccddd8-eada-11e6-9d61-32d946e1c564.PNG)

**Comment by lizongzeshunshun** [comment]
还是不要搞几何画板为好

**Comment by redapple0204** [comment]
@lizongzeshunshun 对啊，这玩意版权保护的实在是太...
什么时候微软也能这样就赚大了

**Comment by lizongzeshunshun** [comment]
。。。

**Comment by lizongzeshunshun** [comment]
我感觉几何画板功能不强啊

**Comment by redapple0204** [comment]
很多老师还是要的...
类似的工具都是英文版，老师肯定用不惯
听说有个学校因为要用几何画板然后学校的电脑老是联合破解了一个..

**Comment by lizongzeshunshun** [comment]
。。

**Comment by lizongzeshunshun** [comment]
mathematica不是很好

**Comment by redapple0204** [comment]
老师都习惯几何画板啦

**Comment by lizongzeshunshun** [comment]
..
