### ISSUE TITLE
换了win10 build9834...

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#130]
拆了时间炸弹...
另：win10的早期版本开机速度超快啊，包开机自检开机才17秒...
而且开机了也不卡。
要是win8.1，win10正式版的话，不包自检都要1min，而且还要卡个几分钟才能用...

真不清楚早期版本怎么做到的...这项技术竟然没有发挥到正式版上
@lizongzeshunshun

**Comment by lizongzeshunshun** [comment]
。。
