### ISSUE TITLE
vp基本都挂了...

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#132]
当年白买了...
还好ss没封
@lizongzeshunshun

**Comment by lizongzeshunshun** [comment]
你的tv好了吗

**Comment by redapple0204** [comment]
@lizongzeshunshun 好了...

**Comment by lizongzeshunshun** [comment]
@redapple0204 number please

**Comment by redapple0204** [comment]
@lizongzeshunshun 
ID：358 335 578
key：redapple
另外为什么ss有个很蛋疼的bug，就是如果挂着ss重启的话就上不了网了==必须要再打开ss才行

**Comment by lizongzeshunshun** [comment]
got it

**Comment by redapple0204** [comment]
ok

**Comment by redapple0204** [comment]
我看你卡在呼入链接了==

**Comment by lizongzeshunshun** [comment]
。。。

**Comment by lizongzeshunshun** [comment]
这个ssr有问题
我服务端的混淆写得是http_simple结果竟然是plain。。。

**Comment by redapple0204** [comment]
@lizongzeshunshun 那我的那个普通ss客户端呢？

**Comment by lizongzeshunshun** [comment]
@redapple0204 普通ss客户端用不了，因为auth协议是区别于ss的

**Comment by redapple0204** [comment]
好吧..

**Comment by lizongzeshunshun** [comment]
话说速度如何

**Comment by redapple0204** [comment]
很好啊..下文件速度比那种分享的快，youtube也不卡。。
我测个速

**Comment by lizongzeshunshun** [comment]
ok

**Comment by lizongzeshunshun** [comment]
我这边能测到30Mbps

**Comment by redapple0204** [comment]
@lizongzeshunshun 为啥测出来速度不行...
![15](https://cloud.githubusercontent.com/assets/16254644/22723522/2203ec4a-edfa-11e6-818d-4baf9d987d86.PNG)
把我的宽带设置高一点不知行不行
另：这个ss是全局的么？（就是除了浏览器别的系统程序例如cmd能用不）

**Comment by lizongzeshunshun** [comment]
不要设置高，如果比你的宽带高反而更慢，我再tv一下

**Comment by redapple0204** [comment]
wait！

**Comment by redapple0204** [comment]
我想起来了，我在上传文件....那再等等

**Comment by lizongzeshunshun** [comment]
ok

**Comment by redapple0204** [comment]
还是有些慢，不过勉强接受吧...
![16](https://cloud.githubusercontent.com/assets/16254644/22723651/275ff82c-edfb-11e6-8509-239a166a1d57.PNG)

**Comment by redapple0204** [comment]
另外真的有必要装chrome插件么....
直接设置全局代理也可以啊

**Comment by lizongzeshunshun** [comment]
话说这win10还挺流畅

**Comment by redapple0204** [comment]
早期预览版很好用的...
不卡，而且主题也不难看

**Comment by lizongzeshunshun** [comment]
可能是我用惯了垃圾电脑。。

**Comment by redapple0204** [comment]
不知道为啥给微软改的那么难用，硬盘还100%...

**Comment by redapple0204** [comment]
我这电脑硬盘效率比你还低

**Comment by redapple0204** [comment]
就内存大一些

**Comment by lizongzeshunshun** [comment]
我电脑的CPU和内存。。。。。。。。。。。。

**Comment by lizongzeshunshun** [comment]
特别是CPU。。。。。。。。

**Comment by redapple0204** [comment]
我的cpu也很垃圾啊...
你不是6G么？

**Comment by lizongzeshunshun** [comment]
1. 台式2G，这个6G的是W7，我妈要用
2. 至少比我的AMD Athlon XXX要好...
话说贴吧的滑稽好像都变成了“#滑稽 go die#”

**Comment by redapple0204** [comment]
1.好吧...2G用xp都卡
2.估计是百度搞得什么活动，或者是为取消滑稽做铺垫

**Comment by lizongzeshunshun** [comment]
.............

**Comment by redapple0204** [comment]
A卡的确不好...上i7
[233](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png?t=20140803)

**Comment by lizongzeshunshun** [comment]
不知道要啥时候上了。。

**Comment by redapple0204** [comment]
....反正贵的要死
另：如果在ss里设置全局代理不就不用chrome插件了？

**Comment by lizongzeshunshun** [comment]
你可以试试

**Comment by redapple0204** [comment]
的确可以==
而且速度比chrome插件要快100k左右

**Comment by lizongzeshunshun** [comment]
。。。

**Comment by redapple0204** [comment]
诶？ssr没有共享给局域网的选项？

**Comment by lizongzeshunshun** [comment]
有啊

**Comment by redapple0204** [comment]
右键菜单没有啊，ss普通版就有

**Comment by lizongzeshunshun** [comment]
选项设置里

**Comment by redapple0204** [comment]
找到了，thx
话说那么隐秘...

**Comment by lizongzeshunshun** [comment]
。。。

**Comment by lizongzeshunshun** [comment]
http://tieba.baidu.com/hottopic/browse/hottopic?topic_id=175553&topic_name=%E6%BB%91%E7%A8%BDgo%20die

**Comment by redapple0204** [comment]
上排行榜了...
才一小时啊

**Comment by lizongzeshunshun** [comment]
。。。

**Comment by lizongzeshunshun** [comment]
> 在与来自微Q星球的假滑稽对决中，滑稽高呼”此生无悔入贴吧，来世再做表情帝”，滑稽战死、消失在贴吧表情世界。去贴吧客户端发布七彩滑稽，帮助滑稽重生，赶紧贡献你的力量！

这是啥。。

**Comment by redapple0204** [comment]
彩色滑稽....

**Comment by redapple0204** [comment]
我就不信真有500万人在讨论

**Comment by lizongzeshunshun** [comment]
。。

**Comment by redapple0204** [comment]
![](http://imgsrc.baidu.com/forum/w%3D580/sign=d5c7de11890a19d8cb03840d03fb82c9/6e29c4cd7cd98d1018918b91283fb80e7aec903a.jpg)

**Comment by redapple0204** [comment]
![](http://imgsrc.baidu.com/forum/w%3D580/sign=a14603a53afa828bd1239debcd1e41cd/411d5e00213fb80e6694e6773fd12f2eb838943a.jpg)
