### ISSUE TITLE
原QQ号报废通告...

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#133]
由于原qq号被查水表，故停止使用【1459966373】，启用小号【1795066796】

**Comment by lizongzeshunshun** [comment]
1.  OK
2. 什么查水表

**Comment by redapple0204** [comment]
查水表泛指某件事情被泄露或者被父母知晓了

**Comment by lizongzeshunshun** [comment]
我知道，具体？
如果介意就不用了

**Comment by redapple0204** [comment]
就是忘记退qq了，然后我妈看到...幸好我及时去退掉了，然而我妈老逼问我密码balabala...只好紧急清空qq然后换小号

**Comment by lizongzeshunshun** [comment]
我每次离开电脑都是Ctrl+L锁定的，安全

**Comment by redapple0204** [comment]
@lizongzeshunshun 就算锁定也没办法，因为最终他看到qq还是会问密码的。。

**Comment by lizongzeshunshun** [comment]
。。。
