### ISSUE TITLE
苹果电脑要被拿回去了

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#134]
从此没有电脑能够放在客厅给我高速下载大文件了
只能用1M/s的小水管慢慢下...
@lizongzeshunshun

**Comment by lizongzeshunshun** [comment]
。。。。。。。

**Comment by lizongzeshunshun** [comment]
话说如果有巨大的文件可以给我下，然后好了你直接过来我把U盘给你

**Comment by redapple0204** [comment]
好的，thx...
不过新的笔记本应该要买了，你觉得什么笔记本比较好。。

**Comment by lizongzeshunshun** [comment]
笔记本啊，Apple或者微软的Surface吧

**Comment by redapple0204** [comment]
@lizongzeshunshun Apple不行，因为新版去掉了usb接口
Sf的话，好久没看了，应该不会预装windowsrt了吧....

**Comment by redapple0204** [comment]
我觉得surface-3还行，也不贵，毕竟我妈只是看看office啥的，而且surface-3也预装office
还是挺划算，不知实体店卖不卖

**Comment by redapple0204** [comment]
不过这类似平板，估计不好操控

**Comment by redapple0204** [comment]
我比较主张省钱，毕竟看看office不需要太好的配置。

**Comment by redapple0204** [comment]
为什么现在电脑配置都那么高...
一个i3+2G内存+64G机械硬盘足以

**Comment by lizongzeshunshun** [comment]
。。我也是建议sf，毕竟微软自家，硬件兼容肯定完爆其他产品

**Comment by redapple0204** [comment]
@lizongzeshunshun 似乎有些小贵...
只有sf3才略微便宜,我估计实体店都没有

**Comment by redapple0204** [comment]
就算有估计也要贵多个一两千的

**Comment by lizongzeshunshun** [comment]
某宝大发啊

**Comment by lizongzeshunshun** [comment]
法

**Comment by redapple0204** [comment]
我妈是不在网上买的，说什么假冒啊balabala的，非要到实体店|（就是沃尔玛，万佳什么的）

**Comment by lizongzeshunshun** [comment]
。。。。。。。。。。。

**Comment by redapple0204** [comment]
我估计超市应该没有卖微软的东西吧...

**Comment by redapple0204** [comment]
以前看到过很多thinkpad= =

**Comment by lizongzeshunshun** [comment]
不可能，不过微软好像有专营店

**Comment by redapple0204** [comment]
1.就算超市有卖，估计也是sf4，贵的要死...
2.我妈也不去专卖店，理由同上。

**Comment by redapple0204** [comment]
我觉得超市的电脑真心不好==

**Comment by lizongzeshunshun** [comment]
专营店卖假货，EXM？

**Comment by redapple0204** [comment]
她说是私人开的==

**Comment by lizongzeshunshun** [comment]
。。淘宝上的微软官方旗舰店总不至于假货吧。。

**Comment by lizongzeshunshun** [comment]
再不行上亚马逊啊，这总不可能卖假货啊
z.cn

**Comment by redapple0204** [comment]
网上的她全都不相信...都说有假，我说到M$官网去她也说.... > 最近不是有好多假的网页么？

信誉鄙视链
淘宝<网上的专卖店<专卖店<超市

**Comment by redapple0204** [comment]
超市真的没有假货吗？

**Comment by lizongzeshunshun** [comment]
...沃尔玛的过期饮料。。。。。。。。。。

**Comment by redapple0204** [comment]
...那是有保质期的
她的原话：
>沃尔玛是一个很大的公司，他的进货渠道肯定很有保证，所以肯定不会出现假货，而且以后维修也方便

**Comment by lizongzeshunshun** [comment]
。。。。

**Comment by redapple0204** [comment]
总之我还是想买sf的...感觉预配那么多东西良心。。。
他们总是说买联想，你觉得如何？

**Comment by lizongzeshunshun** [comment]
联想...........反正我是不推荐

**Comment by redapple0204** [comment]
我也不想要...
你觉得联想有啥坏处，反正上次看到新闻联想铁定win10不给换linux的新闻彻底恶心到我了
再加上这几年联想老是被曝光种种问题

**Comment by lizongzeshunshun** [comment]
性价比太低

**Comment by lizongzeshunshun** [comment]
虽说sf也不高，但是我认为还是比联想好一点的

**Comment by redapple0204** [comment]
联想好像也不贵，4，5千
sf也差不多这个样子吧，不过联想好像没有配赠office

**Comment by lizongzeshunshun** [comment]
指的就是这个

**Comment by redapple0204** [comment]
嗯，虽然随便找个office激活不是难事....
另外现在的sf操作应该不会反人类的吧

**Comment by lizongzeshunshun** [comment]
用盗版终归还是。。。。。。

**Comment by redapple0204** [comment]
WPS去广告大法好...

**Comment by lizongzeshunshun** [comment]
。。。WPS跟office工作流比还是有一点naive了

**Comment by redapple0204** [comment]
查阅一些office文档还是可以的
一大堆数学公式估计就...等等，我妈就要查看数学公式
不过听说libreoffice对数学公式兼容挺不错的

**Comment by lizongzeshunshun** [comment]
啊数学公式！
这个off肯定完爆其他的，直接用触摸笔写公式然后就立马出现格式了的公式

**Comment by redapple0204** [comment]
应该是office03+吧，我看我的office2003并没有很好的对公式进行优化

**Comment by lizongzeshunshun** [comment]
2013+才有吧

**Comment by redapple0204** [comment]
office365应该有
sf预装的16应该也有
不过就我这个垃圾cpu运行会卡的要死

**Comment by redapple0204** [comment]
话说office365学生版不知有没有

**Comment by lizongzeshunshun** [comment]
我有OneNote就够了。。

**Comment by redapple0204** [comment]
onenote能开doc，ppt？

**Comment by lizongzeshunshun** [comment]
不能，但是我很少用这些格式
我是说ON的功能跟office差不多了（当然只是基本功能）

**Comment by redapple0204** [comment]
那github的markdown够我用...
我装office还不是为了打开一大堆doc
不过考虑到OD上能在线查看和编辑office正考虑要不要卸掉office。

**Comment by lizongzeshunshun** [comment]
![image](https://cloud.githubusercontent.com/assets/10304206/22733670/c5206844-ee2d-11e6-84dd-a7aff2eaa35b.png)

公式也有。。

**Comment by redapple0204** [comment]
竟然有公式...这玩意只能保存到微软账户上吧...
应该不能做什么计划表

**Comment by lizongzeshunshun** [comment]
不，可以保存到本地

**Comment by redapple0204** [comment]
markdown的计划表我还是很喜欢的，比起我们班的人用纸一张张贴到桌子右上角不知道高到哪里去了...

**Comment by redapple0204** [comment]
格式是什么？

**Comment by redapple0204** [comment]
ont？

**Comment by lizongzeshunshun** [comment]
.one

**Comment by lizongzeshunshun** [comment]
> markdown的计划表我还是很喜欢的，比起我们班的人用纸一张张贴到桌子右上角不知道高到哪里去了...
你们学校可以用电脑？

**Comment by redapple0204** [comment]
课间可以玩玩的，顺便看看复习计划什么的==

**Comment by redapple0204** [comment]
one文件格式怪怪的

**Comment by lizongzeshunshun** [comment]
转换公式指的就是这个

![image](https://cloud.githubusercontent.com/assets/10304206/22733880/98528706-ee2e-11e6-8a0e-f18a992d4d04.png)

**Comment by redapple0204** [comment]
这个东西不是win7才有么？
另：用手按着鼠标根本写不好字
PS2：9834的微软输入法异常难用，因为没有支持所以不给用云输入

**Comment by redapple0204** [comment]
表示我们学校网络安排很奇怪
除了12-14点都能上网
12-14点去英语老师电脑上弄个vpn照样玩

**Comment by redapple0204** [comment]
本来是一个什么“上网验证系统”，然而我用lantern分分钟解决...估计学校发现了有bug，换成了这种方法，然而图样图森破，禁不了vpn

**Comment by lizongzeshunshun** [comment]
1. surface有笔

2. 用来做计划表也不错
![image](https://cloud.githubusercontent.com/assets/10304206/22734014/2000d0b8-ee2f-11e6-8620-9603313ad34a.png)

3. 对

**Comment by redapple0204** [comment]
1.那估计会好很多
2.能打勾么？

**Comment by lizongzeshunshun** [comment]
1. 嗯
2. 不能打钩怎么叫“待办事项呢。。”

**Comment by redapple0204** [comment]
不过这个框框.....很没违和感
我去看看打了勾会怎样

**Comment by lizongzeshunshun** [comment]
![image](https://cloud.githubusercontent.com/assets/10304206/22734139/a2b4ece2-ee2f-11e6-847e-c622e1a64894.png)

**Comment by redapple0204** [comment]
为啥我的跟你截然不同。。。
![18](https://cloud.githubusercontent.com/assets/16254644/22734213/dbe915b0-ee2f-11e6-8a17-9dde9cf8cfd1.PNG)

**Comment by lizongzeshunshun** [comment]
你可能用了假ON

**Comment by redapple0204** [comment]
不不不，可能测试版的不一样
或者你的win7的和win10的也不一样

**Comment by lizongzeshunshun** [comment]
..

**Comment by redapple0204** [comment]
win8.1的ON啥都干不了，就跟ios的记事本一样...

**Comment by lizongzeshunshun** [comment]
可以卸了装off365页面上那个

**Comment by redapple0204** [comment]
卸不了，预装的modern应用...
直接装exe版的算了

**Comment by redapple0204** [comment]
@lizongzeshunshun 话说回来，issue能不能删除的，我上次就看到有人能把一个色情交友的issue删了

**Comment by lizongzeshunshun** [comment]
我只知道API没有删除ISSUE的，stackOF也指出不能这样做

**Comment by redapple0204** [comment]
欸，难道我上次看的是rp？rp能删么==

**Comment by lizongzeshunshun** [comment]
不能够

**Comment by lizongzeshunshun** [comment]
举报说不定可以

**Comment by redapple0204** [comment]
我估计也是举报的
