### ISSUE TITLE
holiday.py制作exe会出问题

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#135]
一直狂弹出cmd窗口，只能任务管理器结束
如果把cls那一段去掉就什么都不会出现，但从任务管理器可以看出已经出现了程序，而且cpu占的多的要死

PS：我觉得github pages挺不错的，可惜只能搭一个博客==

**Comment by lizongzeshunshun** [comment]
。。用啥软件

**Comment by redapple0204** [comment]
py2exe啊，用pip安装的

**Comment by lizongzeshunshun** [comment]
到时候我golang移植一份

**Comment by redapple0204** [comment]
能移植么?

**Comment by lizongzeshunshun** [comment]
可以

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.ok
2.刚刚你改了啥...我没看到

**Comment by lizongzeshunshun** [comment]
移了一下位置

**Comment by redapple0204** [comment]
我又改了...

**Comment by redapple0204** [comment]
总感觉排版不好，但说不出哪里别扭

**Comment by lizongzeshunshun** [comment]
。。对

**Comment by redapple0204** [comment]
算了，让他们看我贴吧带图的...
另外我发现一搜索百度云破解 github就出来我们这个项目...
说明点击率很高，怪不得那么多star...

**Comment by lizongzeshunshun** [comment]
对，我也注意到了这第一点

**Comment by redapple0204** [comment]
我记得当年是aira2当头的
他们怎么会发现这里呢.....
希望这个方法不要和谐....

**Comment by lizongzeshunshun** [comment]
http://tech.xinmin.cn/3c/2017/02/08/30816967.html
look at this...

**Comment by redapple0204** [comment]
我去，这厉害的...
敢不敢放到火上烤？![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png?t=20140803)

**Comment by lizongzeshunshun** [comment]
。。。。

**Comment by lizongzeshunshun** [comment]
这接近绝对0度了

**Comment by redapple0204** [comment]
竟然做得出这种温度

**Comment by lizongzeshunshun** [comment]
。。
