### ISSUE TITLE
想问问免责声明真的有用么....

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#136]
@lizongzeshunshun

**Comment by lizongzeshunshun** [comment]
这个还真不知道

是从kcptun这个项目抄来的

**Comment by redapple0204** [comment]
没用的...给几个参考回答

第一个

>作者：Three诗睿
链接：https://www.zhihu.com/question/26921266/answer/125098814
来源：知乎
著作权归作者所有，转载请联系作者获得授权。

>一年之前想写这个问题，然而笔者太懒，来迟也。现在积累了一点资料和经验来回答这个问题，如有缺漏，请知友不吝赐教：
我们往往可以看到，免责声明出现于电邮正文内容之后，措辞很谨慎，而且带有警告意味。诸如题主所言的这类免责声明适用的行业范围之广，令人瞠目结舌，但是从法律合同角度来看，这样的做法毫无用处。
从国内和国外的司法实践和相关案例来看，电子邮件的免责声明在现实的法律事件的效用略等于无，更多的作用在于规范了电邮文本，体现邮件的正式性，从而提醒收件人顺便看看，做到心里有数。在国外来看，几乎没有关于邮件免责声明的判例法和相关案例；于国内而言，至今尚未有确切消息表明相关案例涉及电子邮件的免责声明。即使是热衷诉讼善于紧跟文本字眼的美国， 至今还没发现也哪个诉案是由这种自动的电邮页脚的存在与否引起的。 
从免责声明本身来看，需要收件人同意的免责声明最脆弱。最有力的那种免责声明是旨在通知收件人，以免其产生误解，或者声称产生了误解，以至于造成法律后果——但这也仅仅是提醒而已。
举个例子，你看像诸如“ "This is confidential. Do not forward. Delete and return to sender（此为机密，切勿转发，阅后即焚，且复寄者）”这样的免责声明。它们应该被认为是单方协议——由于电邮发件人与邮件收件人没有任何事先约定，这违背公平原则，故而该类免责声明不具备强制性，也就没有任何效力。
但是，也有特例，譬如美国国税局230号条例就规定，提供避税建议的邮件中必须附上免责声明。但由于这并不约束邮件的收件人，而只是对电邮发件人有行政拘束力而已。故而从所问的角度，是另一回事，讨论这个特例也没有意义。
那么，既然免责声明在现实适用里基本上形同鸡肋，没什么用处，为什么往往在商务邮件往来中还广泛使用呢？一方面，免责声明与邮件的其他内容共同组成一套规范的商务邮件礼仪，从而往往被大家约定俗成的适用了；另一方面，电子邮件上的免责声明实际上是传统法律文书的自然演进。最开始所有律师会在纸面文件或传真的封面上放上这些大同小异的文字——相关注意事项，而到了互联网时代，这些注意事项就演变成了电子邮件的免责条款。就如13年《The economist》一篇叫《Business Legal disclaimers Spare us the e-mail yada-yada 》的文章所说的，“ As with Latin vocabulary and judges' robes, once something has become a legal habit it has a tendency to stick. Might they at least remind people to behave sensibly?”一旦某行为成为一种法律习惯，该行为就会被继续坚持下去。 免责声明也是因此成了一项商务或公务习惯。至少，这些免责声明可以规范商业行为，提醒人们理智行动，并使得收件人对发件人的电邮文本上的彬彬有礼（至少表面看上去）感到舒心愉悦。而反过来，如果有公司或个人不在邮件中附上免责声明，会被认为是没有职业素养和缺乏基本礼仪。
故而，免责声明的形式意义大于实质意义。其更多被赋予了形式上的意义，譬如保持邮件信函的严肃规范和体现商务礼仪，而实质上根本没什么大用。犹如鸡肋，食之无味，弃之可惜，但大家还是要约定俗成地在电子邮件中不得不用，这也是一种蛮有趣的文化现象啊。
--------------------------------------------------------------------------------------------------------------------------------------------
2016.10.5下午手写于石景山图书馆
2016.10.5夜录入电脑，并附列当日下午图书馆所翻阅的部分有关电子邮件商务/公务礼仪和礼仪的有趣书目，感兴趣的知友可以翻一下，也许对于进一步规范商业往来和个人交往有所裨益。
【相关参考书目】：
1.《国际礼仪指南》曲蒙著 文汇出版社 2006年3月版（有关电子邮件详见P171）；
2.《黑莓帝国》Blackberry planet（加）斯维尼著 华夏出版社 2010年8月版（因为翻阅了其专利诉讼部分，觉得蛮有趣）；
3.《公务礼仪》 韩强著 鹭江出版社 2012年7月版（电子邮件部分详见P236）；
4.《过渡礼仪》（法）范热内普著 商务印书馆 2010年11月版。

第二个

>谢邀并祝春节快乐！

>如果单方写个简单声明在法律上就可以免除民事侵权责任和刑事责任，那全世界的版权律师恐怕都要失业了。是否能免责还是要是要看实际的危害结果。

>关于中国司法实践中免责声明的法律效力，我引用一段成都“番茄花园案”（09年知识产权司法保护十大案件之一）主审法官的说法：“他在每个版本上都是要求其他使用者24小时之内删除，但是现在客观上的情况是，许多用户下载了番茄版本软件之后没有删除，继续在使用。那么就造成了一个比较恶劣的影响。也就是说在全国范围内有那么多人都在使用番茄花园盗版的软件，那就侵犯了微软公司的合法利益。”

>作者：Raymond Wang
链接：https://www.zhihu.com/question/20031481/answer/13741589
来源：知乎
著作权归作者所有，转载请联系作者获得授权。

**Comment by lizongzeshunshun** [comment]
等人多了再考虑这个问题

**Comment by redapple0204** [comment]
嗯，现在好像还没什么破解版软件
一个事crossover，公司应该没找上门
另一个是几何画板，然而我没放链接，现在也没人开issue问

**Comment by redapple0204** [comment]
破解百度云限速应该不会
但是如果在上面放翻墙内容就会被请去喝茶....

**Comment by lizongzeshunshun** [comment]
。。。度

**Comment by lizongzeshunshun** [comment]
对

**Comment by redapple0204** [comment]
翻墙内容尽量放OD里吧，毕竟过一段时间会自动退出，警察也找不到证据。
上次不是有个人因为翻墙被请去喝茶了么==

**Comment by redapple0204** [comment]
[许东翻墙事件](https://pao-pao.net/article/292)

**Comment by redapple0204** [comment]
翻墙以“寻衅滋事罪”逮捕？我笑了

**Comment by lizongzeshunshun** [comment]
..

**Comment by lizongzeshunshun** [comment]
6666

**Comment by lizongzeshunshun** [comment]
还是注意为好

**Comment by redapple0204** [comment]
毕竟他还是制造翻墙软件嘛，而且基于GA还收费
被抓活该....

**Comment by redapple0204** [comment]
我们大可放心
就像微软只抓企业盗版一样

**Comment by lizongzeshunshun** [comment]
对
话说gp（ga的go版本fq速度好像也不错）：https://github.com/phuslu/goproxy

**Comment by redapple0204** [comment]
这个不能自动获取appid？
我觉得看上去还是不如ss
ss大法好，不知什么时候会被封

**Comment by lizongzeshunshun** [comment]
ssR有混淆，估计GFW还封不了

**Comment by redapple0204** [comment]
那vpn是怎么搞的，最近老是连不上，而且速度巨慢...
另外到时候墙越来越高就不好说了
还有hosts这个项目弄了那么多年搞的风水生气也没封？

**Comment by lizongzeshunshun** [comment]
vpn封得差不多了；
对啊，已经10K+的starts了

**Comment by redapple0204** [comment]
1.不知道怎么封的，正规的vpn企业也不能幸免
2.他们说这个项目有方校长在背后支持，不会挂的

**Comment by lizongzeshunshun** [comment]
THAT'S NOT POSSIBLE

**Comment by lizongzeshunshun** [comment]
除非封了GH，这个项目不可能go die

**Comment by redapple0204** [comment]
@lizongzeshunshun 
1.但事实就是这样啊....
2.那全中国的程序员要爆发了。13年不是封过一次么

**Comment by lizongzeshunshun** [comment]
1. 哪里说了

**Comment by redapple0204** [comment]
？

**Comment by lizongzeshunshun** [comment]
> 他们说这个项目有方校长在背后支持，不会挂的

**Comment by redapple0204** [comment]
我记得是在什么项目/博客中看到的...不过忘记了
要不是他支持怎么可能会泄露那么多ip...

**Comment by lizongzeshunshun** [comment]
..

**Comment by redapple0204** [comment]
@lizongzeshunshun 我发现现在天威提速了...
上传400-500k/s，下载5-6m/s了...还算良心

**Comment by lizongzeshunshun** [comment]
..
