### ISSUE TITLE
问下你ss流量有多少

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#137]
我才能根据实际情况用...@lizongzeshunshun

**Comment by lizongzeshunshun** [comment]
@redapple0204 800G

**Comment by redapple0204** [comment]
ok，那上上网页应该没问题吧。

**Comment by lizongzeshunshun** [comment]
sui bian.

**Comment by lizongzeshunshun** [comment]
hua shuo wo hai shi yong bu liao shu ru fa

**Comment by lizongzeshunshun** [comment]
wait, it's 400G
400G Upload And 400G Download but proxy use 2*it

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.按理说不可能没法用啊
2.话说ss突然变得很慢很慢....

**Comment by redapple0204** [comment]
明天11点或者下午1点帮你tv看下输入法问题

**Comment by lizongzeshunshun** [comment]
高峰期正常 ok

**Comment by redapple0204** [comment]
@lizongzeshunshun 晚上高峰期？
另外你桌面环境还是kde5吧，tv最好安装12版本的。

**Comment by lizongzeshunshun** [comment]
@redapple0204 我准备换Win了。。

**Comment by redapple0204** [comment]
你不是本来就是win么...

**Comment by lizongzeshunshun** [comment]
我说arch->win10

**Comment by redapple0204** [comment]
双系统？
另外我测试一下删楼能不能在邮箱看见。。。

**Comment by redapple0204** [comment]
嗯，可以...

**Comment by lizongzeshunshun** [comment]
1. 不是双系统

**Comment by lizongzeshunshun** [comment]
话说Win10最新版本哪里有下（ITellYou是10240的）

**Comment by redapple0204** [comment]
你要beta版？

**Comment by redapple0204** [comment]
还是红石？

**Comment by lizongzeshunshun** [comment]
149xx就可以了

**Comment by redapple0204** [comment]
![19](https://cloud.githubusercontent.com/assets/16254644/22764691/2aa5fbb0-eea7-11e6-83a2-ed47b776a3b8.PNG)

**Comment by lizongzeshunshun** [comment]
w我看看

**Comment by lizongzeshunshun** [comment]
downloading but这速度好像有点慢

![image](https://cloud.githubusercontent.com/assets/10304206/22764770/bfa2d8f0-eea7-11e6-9625-8fc96611f422.png)

**Comment by lizongzeshunshun** [comment]
话说为什么要把两个版本放一起，iso都4.xG了

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.用百度离线下再用破解办法，速度嗖嗖的。
再怎么样也不要用迅雷极速版，这玩意没有加速，好歹也要用破解版啊....
2.反正是给DVD用的，缩小的话不是浪费了？

**Comment by lizongzeshunshun** [comment]
没错，现在就是 （已经离线了）

![image](https://cloud.githubusercontent.com/assets/10304206/22764877/48de4f32-eea8-11e6-89ef-6419a850381b.png)

**Comment by lizongzeshunshun** [comment]
super fast..

![image](https://cloud.githubusercontent.com/assets/10304206/22764929/8b0b8d2a-eea8-11e6-8f27-bca6fa5804fe.png)

**Comment by redapple0204** [comment]
好快啊.....
几分钟都搞定

**Comment by redapple0204** [comment]
话说你干啥不用win8.1什么的，不是SSD上win10很蛋疼的

**Comment by lizongzeshunshun** [comment]
据说8.1代码写得比10烂。。

**Comment by lizongzeshunshun** [comment]
下完了 正在win32diskimager

**Comment by redapple0204** [comment]
干嘛不用rufus

**Comment by lizongzeshunshun** [comment]
以前都用的是w32di
![image](https://cloud.githubusercontent.com/assets/10304206/22765228/19c8d896-eeaa-11e6-9885-99d31e94a15a.png)

**Comment by redapple0204** [comment]
但是就算写得不好也不会卡啊...
而且win10的黑色主题也那么难看

**Comment by lizongzeshunshun** [comment]
我觉得挺好看啊

**Comment by redapple0204** [comment]
win32经常刻录失败

**Comment by lizongzeshunshun** [comment]
我写过20+次，没有一次失败的。。

**Comment by lizongzeshunshun** [comment]
almost done

![image](https://cloud.githubusercontent.com/assets/10304206/22765284/56419858-eeaa-11e6-9da2-a3aa3656e3af.png)

**Comment by lizongzeshunshun** [comment]
![image](https://cloud.githubusercontent.com/assets/10304206/22765335/9830fad8-eeaa-11e6-89c2-1039650b15d4.png)

ok

话说推荐可截图软件：SniPaste

**Comment by lizongzeshunshun** [comment]
好了，正在安装

**Comment by lizongzeshunshun** [comment]
继续进入赶作业状态》。。。。。。。。。。

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.我说有的发行版没法写入
2.我习惯用windows截图了...
3.安装应该很快吧，无果我还是喜欢用nt6安装
4.嗯，我也哟了

**Comment by lizongzeshunshun** [comment]
。。。。

**Comment by lizongzeshunshun** [comment]
finished Installing

**Comment by redapple0204** [comment]
干嘛不用nt6安装器。。
