### ISSUE TITLE
请问还有几何画板破解版吗？

### ISSUE THREAD

**Issue by yjiaz** [redapple0204/my-boring-python#138]

**Comment by lizongzeshunshun** [comment]
@redapple0204

**Comment by redapple0204** [comment]
@yjiaz 还真有人问...
几何画板5.01单文件：https://tpedutw-my.sharepoint.com/personal/redapple0204_tp_edu_tw/_layouts/15/guestaccess.aspx?docid=14ae3bcc3bfa747cba45e285e1ddb499a&authkey=ASTPLh8NdhZ_6dC4PAjwD6U

几何画板5.06安装破解版：https://tpedutw-my.sharepoint.com/personal/redapple0204_tp_edu_tw/_layouts/15/guestaccess.aspx?docid=1d81dec3a906c47e0b37422d6eb6a1ff9&authkey=AWB7Dgk6YYrj-1oMttkFfe4

**收到后请务必回复，我们方便删除，否则将在2-11日早上11点前删除**
@lizongzeshunshun

**Comment by lizongzeshunshun** [comment]
@yjiaz 请查收您的邮箱，定位到本ISSUE即有链接下载，谢谢

**Comment by redapple0204** [comment]
@yjiaz 如果无法找到/收到，请提供您的邮箱，我会发过去。

**Comment by yjiaz** [comment]
似乎没有收到 能不能发送到iraincok@gmail.com

**Comment by redapple0204** [comment]
@yjiaz 已发送，请查收
发件人名字【redapple02041@gmailo.com】

**Comment by yjiaz** [comment]
已收到，谢谢！
