### ISSUE TITLE
某些国产软件似乎会收集用户的翻墙信息

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#139]
真不要脸....和GFW有py交易
赶紧把国产软件卸了
@lizongzeshunshun

**Comment by lizongzeshunshun** [comment]
1. 我好像没装什么国产中型软件（除了QQ
2. I'm now in Win10

**Comment by lizongzeshunshun** [comment]
话说这更新下载好慢啊

**Comment by lizongzeshunshun** [comment]
![image](https://cloud.githubusercontent.com/assets/10304206/22767124/70b6c050-eeb4-11e6-9339-3b1a9e594456.png)

**Comment by redapple0204** [comment]
1.qq原版一样，收集得很严重，除非绿色版
2.你看着她更新慢的要死，如果关掉干点别的事就很快了

另：干啥要更新。。。

**Comment by redapple0204** [comment]
其实换了beta就没更新了，所以我才用beta...，一次更新占掉一大堆空间

**Comment by lizongzeshunshun** [comment]
根据知乎vczh，“如果不打开Windows Update，每一个更新都是逆向的工具啊”。。。

**Comment by redapple0204** [comment]
这么说现在xp打完漏洞就无忧了 ![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png?t=20140803)

**Comment by lizongzeshunshun** [comment]
....
