### ISSUE TITLE
关于win10 bash很奇怪的问题

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#14]
打开bash，输入ifconfig，就会出现“Warning: cannot open /proc/net/dev (No such file or directory). Limited output.”
用nmap扫标别的网站，就会出现“
route_dst_netlink: cannot create AF_NETLINK socket: Invalid argument”
@K-Guan 请问这是没有自带网卡还是咋的

**Comment by redapple0204** [comment]
顺便再请问一下，python怎么清屏（网上一大堆说
import os
i=os.system('cls')的）
@K-Guan

**Comment by K-Guan** [comment]
@redapple0204 Win10...真的原生支持 bash ？还是哪个第三方软件？

Python 清屏，那个方法是对的。Python 不能“直接”的操作终端程序，所以根本无法实现“单独”用 Python 清屏的。不过……调用 Shell 命令对于 Python 倒是没问题。

**Comment by redapple0204** [comment]
@K-Guan 是的，在最新预览版已经自带了bash，详情可以见http://wp.18183.com/201604/561721.html 还有http://www.tuicool.com/articles/zAjARvB ，那么，也就是说，py win和linux两个清屏是不一样的喽

**Comment by K-Guan** [comment]
@redapple0204 （吐血……）

<sub>*有问题，就 Google。*</sub>

**Comment by redapple0204** [comment]
@K-Guan 这个。。bash刚出一个月不到，都还没这方面的问题解答

**Comment by K-Guan** [comment]
清屏问题嘛……没错。当然了，你也可以先检测系统嘛：

```python
import os
os.system('clear' if os.name == 'posix' else 'cls')
```

这个，使用 **one-line if statement** 检测系统信息，如果是 POSIX 则返回 `'clear'`，否则 `'cls'`。当然，也可以选择返回 `os.system('clear')` 或 `os.system('cls')` 的方法，相比上述更加清晰：

```python
import os
os.system('clear') if os.name == 'posix' else os.system('cls')
```

当然，如果一味追求短而不要清晰了，也可以……（虽然我本人不是很推崇）：

```python
import os
os.system(('cls', 'clear')[os.name == 'posix'])
```

另外写一个完整的 `if` 语句也是可以的，不过我觉得那就没必要了。

**Comment by K-Guan** [comment]
@redapple0204 这个……我帮你找找看……

**Comment by redapple0204** [comment]
@K-Guan 我怎么没想到这一点呢，谢谢了

**Comment by K-Guan** [comment]
@redapple0204 其实也是之前学到的，不足一提。

说起 bash ，看来这个问题有些棘手。不过我 Google 了下还是找到类似你这个问题，并且…… **很多！**：

> 1. https://blogs.msdn.microsoft.com/commandline/2016/04/06/bash-on-ubuntu-on-windows-download-now-3/#comment-531
> 2. https://blogs.msdn.microsoft.com/commandline/2016/04/06/bash-on-ubuntu-on-windows-download-now-3/#comment-763
> 3. http://weblog.west-wind.com/posts/2016/Apr/13/Windows-10-Bash-Shell-Network-Connectivity-not-working#OtherNetworkProblems

总之我简单看了下，基本意思就是：

> 这玩意现在还是实验品，虽然是打算将来搞完美点，但是在目前情况下我们也只是在摸索着来。请各位别着急，问题会陆续在接下来的版本中修复的。

另外这个问题……摆明了就是根本没法联网……好像还和 DNS 什么的有关，我也没仔细看，你去研究下吧。

**Comment by redapple0204** [comment]
@K-Guan 哦，好的，我去看看。（话说可以联网啊，w3m还有ping都可以）

**Comment by K-Guan** [comment]
@redapple0204 这个……虽然不想明说，但是我还是想问：“Arch Bash 是什么？”（话说……你不说的是 Zsh ，然后只是用上了 Arch 在 Live 中那个默认主题了吧？什么时候改名叫 Arch Bash 了？）

**Comment by redapple0204** [comment]
@K-Guan 事实上呢 只要把ubuntu的内核文件替换arch就好了 具体方法嘛。具体方法嘛。。表示在我电脑上晚上告诉您一下

**Comment by redapple0204** [comment]
@K-Guan 事实上呢 只要把ubuntu的内核文件替换arch就好了 具体方法嘛。具体方法嘛。。表示在我电脑上晚上告诉您一下

**Comment by redapple0204** [comment]
理论上是支持替换所有版本的linux。。事实上都可能会出现一些问题

**Comment by redapple0204** [comment]
@K-Guan 方法是这样的：下载 archlinux 的iso，解压出sfs文件，进bash，unsquashfs解压出来，然后在外边把rootfs替换成它，再进bash就可以了

**Comment by K-Guan** [comment]
@redapple0204 哦，原来你的意思是更换内核呀。明白了。

**Comment by redapple0204** [comment]
@K-Guan 顺便，再问一下：github是否有自带的邮箱（例如是否有redapple0204@github.com）

**Comment by K-Guan** [comment]
@redapple0204 据我所知……那个邮箱只能收不能发，并且和你注册用的邮箱绑定的。

**Comment by redapple0204** [comment]
@K-Guan 好吧，那就没啥意义了（绑定的是我qq邮箱）还是用gmail好了
