### ISSUE TITLE
filesshare分支是什么鬼？

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#140]
@lizongzeshunshun

**Comment by redapple0204** [comment]
@lizongzeshunshun 大文件我都放OD或者RE上的....
lfs有流量限制吧

**Comment by lizongzeshunshun** [comment]
OD大法好！

**Comment by redapple0204** [comment]
普通版没用，要for business速度才有提升
另：似乎OD被中国封锁得很严重啊

**Comment by redapple0204** [comment]
普通版没用，要for business速度才有提升
另：似乎OD被中国封锁得很严重啊

**Comment by lizongzeshunshun** [comment]
> lfs有流量限制吧

没有

**Comment by redapple0204** [comment]
我记得有...等我看看首页

**Comment by redapple0204** [comment]
我这里只有几百k，能接受。
因为天威封了OFB，只能改hosts

**Comment by redapple0204** [comment]
另外ios没有ss很蛋疼啊，每次都只能从我电脑共享出去

**Comment by lizongzeshunshun** [comment]
ios有啊

**Comment by redapple0204** [comment]
有是有，但是因为apple的应用限制，每5分钟要重新激活客户端，否则无法连接

**Comment by redapple0204** [comment]
5分钟太频繁了..

**Comment by lizongzeshunshun** [comment]
...

**Comment by lizongzeshunshun** [comment]
越狱？

**Comment by redapple0204** [comment]
ios10.x越狱不了

**Comment by lizongzeshunshun** [comment]
看看这个
https://github.com/shadowsocksr/ShadowsocksX-NG

**Comment by redapple0204** [comment]
这不是mac的么

**Comment by redapple0204** [comment]
fdm那么垃圾，od的文件竟然获取不了

**Comment by lizongzeshunshun** [comment]
不可能

**Comment by lizongzeshunshun** [comment]
你先分享然后复制链接

**Comment by redapple0204** [comment]
返回403错误

**Comment by lizongzeshunshun** [comment]
那就用aria2啊

**Comment by redapple0204** [comment]
你不知道aria2在windows中的命令不同....
算了，我还是用浏览器下吧

**Comment by redapple0204** [comment]
chrome竟然不自带多线程下载...

**Comment by lizongzeshunshun** [comment]
一样的

aria2c -s4 -x4 -k1M "LINK"

都是相同源码编译的

**Comment by redapple0204** [comment]
好吧，我在一个下的网站下了假的aria2c...

**Comment by redapple0204** [comment]
话说回来cmd不支持ss么？

**Comment by lizongzeshunshun** [comment]
要支持cmd要下载py版的

**Comment by redapple0204** [comment]
那么烦...不能像vpn挂全局？

**Comment by lizongzeshunshun** [comment]
win10支持

**Comment by redapple0204** [comment]
我这就是win10...![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png?t=20140803)

**Comment by lizongzeshunshun** [comment]
tv

**Comment by redapple0204** [comment]
我怀疑早期版本的win10不支持吧？

**Comment by lizongzeshunshun** [comment]
我试试

**Comment by lizongzeshunshun** [comment]
。。

**Comment by redapple0204** [comment]
以后下载加上“--all-proxy="http://127.0.0.1:1080"”是吧

**Comment by lizongzeshunshun** [comment]
对

**Comment by redapple0204** [comment]
然后别的要不要设置？

**Comment by lizongzeshunshun** [comment]
其实说不定 --all-proxy="https://c4oso.me:443" 也可以

**Comment by lizongzeshunshun** [comment]
你试试

**Comment by redapple0204** [comment]
不行

Microsoft Windows [版本 6.4.9834]
(c) 2014 Microsoft Corporation. All rights reserved.

C:\Users\redapple>aria2c -s4 -x4 -k1M "https://github.com/redapple0204/my-boring-python/releases/download/007/Msg3.0.db" --all-proxy="https://c4oso.me:443"

02/09 13:13:38 [NOTICE] Downloading 1 item(s)
[#7dcbfd 0B/0B CN:1 DL:0B]
02/09 13:13:40 [ERROR] CUID#7 - Download aborted. URI=https://github.com/redapple0204/my-boring-python/releases/download/007/Msg3.0.db
Exception: [HttpConnection.cc:150] errorCode=1 Got EOF from the server.

02/09 13:13:40 [NOTICE] Download GID#7dcbfd2d35b5bdfb not complete:

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
7dcbfd|ERR |       0B/s|https://github.com/redapple0204/my-boring-python/releases/download/007/Msg3.0.db

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.

C:\Users\redapple>

**Comment by lizongzeshunshun** [comment]
竟然不支持https代理，什么垃圾东西

**Comment by redapple0204** [comment]
1.windows版垃圾
2.现在又不行了

**Comment by lizongzeshunshun** [comment]
2. 确定？

**Comment by redapple0204** [comment]
C:\Users\redapple>aria2c -s16 -x16 -k1M "https://github.com/redapple0204/my-boring-python/releases/download/007/Msg3.0.db" --all-proxy="http://127.0.0.1:1080"

02/09 13:15:19 [NOTICE] Downloading 1 item(s)
[#d39706 0B/0B CN:1 DL:0B]

**Comment by redapple0204** [comment]
话说不能把ss关了
我记得我没退啊

**Comment by lizongzeshunshun** [comment]
ok

**Comment by redapple0204** [comment]
嗯，ok

**Comment by redapple0204** [comment]
del有毒啊！
怎么会把所有这个文件名都删了
>C:\Users\redapple>del /s /q Msg3.0.db
删除文件 - C:\Users\redapple\Msg3.0.db
删除文件 - C:\Users\redapple\Documents\Tencent Files\1459966373\Msg3.0.db
删除文件 - C:\Users\redapple\Documents\Tencent Files\1795066796\Msg3.0.db
删除文件 - C:\Users\redapple\Documents\Tencent Files\573196260\Msg3.0.db

**Comment by lizongzeshunshun** [comment]
尴尬。。。

**Comment by lizongzeshunshun** [comment]
![image](https://cloud.githubusercontent.com/assets/10304206/22770305/6956adaa-eeca-11e6-8008-7b07fdf10a74.png)

**Comment by redapple0204** [comment]
要是人家不懂得话这样删就惨了....

**Comment by redapple0204** [comment]
所以就是直接del就好了
百度知道还说要del /s /q

**Comment by lizongzeshunshun** [comment]
百度是del /f /q吧

**Comment by lizongzeshunshun** [comment]
![image](https://cloud.githubusercontent.com/assets/10304206/22770332/a8227bea-eeca-11e6-84f7-ef3a4a2f7da3.png)

**Comment by redapple0204** [comment]
哦，thx
百度我上次看到的是/s /q，然后一直这样用了两年

**Comment by lizongzeshunshun** [comment]
...

**Comment by redapple0204** [comment]
话说别的软件过不过ss流量的？例如qq什么的

**Comment by lizongzeshunshun** [comment]
qq是udp的，理论上不会被代理

**Comment by redapple0204** [comment]
感觉ss和vpn还是有好大差异。。

**Comment by redapple0204** [comment]
qq好像要手动设置

**Comment by lizongzeshunshun** [comment]
。。对

**Comment by redapple0204** [comment]
话说那个ss文件夹的2.0版本是干啥的。。

**Comment by lizongzeshunshun** [comment]
那是给.net2.0用的（比如说xp）

**Comment by redapple0204** [comment]
好吧...界面应该是一样的吧

**Comment by lizongzeshunshun** [comment]
应该。。

**Comment by redapple0204** [comment]
好吧

**Comment by lizongzeshunshun** [comment]
。。

**Comment by lizongzeshunshun** [comment]
@redapple0204 
https://www.zhihu.com/question/41058261

**Comment by redapple0204** [comment]
@lizongzeshunshun 好像只有还SSD才行吧，我又不是三星的...

**Comment by redapple0204** [comment]
另外我不用achi。。

**Comment by lizongzeshunshun** [comment]
..

**Comment by redapple0204** [comment]
贴吧的人说win10引进了内存压缩功能导致的

**Comment by Guanrenfu** [comment]
teest
