### ISSUE TITLE
让我看看是怎么回事

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#147]
@lizongzeshunshun

**Comment by lizongzeshunshun** [comment]
ok

**Comment by redapple0204** [comment]
我看看邮箱

**Comment by lizongzeshunshun** [comment]
OK

**Comment by redapple0204** [comment]
没回我邮件，一切都莫名其妙

**Comment by lizongzeshunshun** [comment]
...

**Comment by lizongzeshunshun** [comment]
确定没被扔进订阅和垃圾邮件

**Comment by redapple0204** [comment]
![img_0004](https://cloud.githubusercontent.com/assets/16254644/22816940/b3a17202-ef9f-11e6-8cca-d62856e79e95.PNG)
看

**Comment by redapple0204** [comment]
话说readme中的tmp文件夹别删啊。。。

**Comment by lizongzeshunshun** [comment]
我去。。

**Comment by redapple0204** [comment]
![img_0005](https://cloud.githubusercontent.com/assets/16254644/22817035/074ad15a-efa0-11e6-8f46-067ef5eeef71.PNG)
翻译版本

怎么了？

**Comment by redapple0204** [comment]
似乎是垃圾邮件的问题

**Comment by redapple0204** [comment]
似乎...真的有人拿github来发垃圾邮件啊
我怀疑这两天我们聊天聊的太多了，然后就。。。

**Comment by redapple0204** [comment]
应该不是几何画板的问题。。。
