### ISSUE TITLE
这是怎么回事？

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#149]
您好，感谢您开 Issue 来反馈信息，在提交前，请确保您已经检查了以下内容!
- 如果您发现本项目有问题，请积极的提出您的问题，我们将会很快修复
- 如果您想要获取破解crossover的补丁，请访问[这里](http://tieba.baidu.com/p/4897237773)
- 如果您想问关于技术方面的问题，请您详细描述，最好配上图
- 如果您想获取几何画板破解版，请给出**至少一条**证据证明您不是几何画板公司的员工并提供您的邮箱，并发誓不会将次破解版传出，否则将不会发送给您，尽请原谅。

当然您也可以只是一般性的和我聊天

（建议您翻一翻issue哦，有许多有价值的技术讨论文章）

上面测试下....
下面为正文
![32](https://cloud.githubusercontent.com/assets/16254644/22820693/d8c11d04-efb2-11e6-8859-00f410d119e3.PNG)
@lizongzeshunshun

**Comment by lizongzeshunshun** [comment]
没啥问题啊

**Comment by redapple0204** [comment]
为什么我的小号在去年10月来这个项目做贡献，而且它也不是协作者啊

**Comment by lizongzeshunshun** [comment]
发了iss就是做了贡献

**Comment by redapple0204** [comment]
不过你看他是remove dir==
删了文件

**Comment by lizongzeshunshun** [comment]
commit的hash编号是多少

**Comment by redapple0204** [comment]
64f321

**Comment by lizongzeshunshun** [comment]
这就很奇怪了

**Comment by redapple0204** [comment]
对啊，这是什么鬼？
重大bug啊。。
