### ISSUE TITLE
电脑课竟然学VB...

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#156]
@lizongzeshunshun 感觉和易语言差不多，都很简单。。

**Comment by lizongzeshunshun** [comment]
我们还在 考 试>>>>>>>>>>>>>>>>>>>>>>>
另外我在学Powershell，感觉特别强大，能跟Py比了

**Comment by lizongzeshunshun** [comment]
![image](https://cloud.githubusercontent.com/assets/10304206/22883879/3179a8ea-f22d-11e6-9c47-58baedc1e1ff.png)

look，自动下载issues

**Comment by lizongzeshunshun** [comment]
源码只有这么多

```
$repo_url = Read-Host("Please Enter Repo's URL(Main Page)") 
$issues_number = Read-Host("Please enter issues number")
$issue_page = $repo_url + "/issues/"
for($i=1;$i -le $issues_number;$i++)
{
    echo ("Downloading Issues " + [string]$i)
    Invoke-WebRequest -O ([string]$i + ".html") $issue_page
}
```

**Comment by redapple0204** [comment]
我去？那么强大
可惜不能跨平台

**Comment by redapple0204** [comment]
另外我把这的整个安排到了https://app.backhub.co/ 备份，所以不用担心issue的问题

**Comment by redapple0204** [comment]
另外开学考悲哀

**Comment by lizongzeshunshun** [comment]
开源的，应该可以跨平台

**Comment by redapple0204** [comment]
噗
>
PS C:\Users\redapple\Desktop> .\1.ps1
.\1.ps1 : 无法加载文件 C:\Users\redapple\Desktop\1.ps1，因为在此系统上禁止运行脚本。有关详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkID=135170 中的 about_Execution_Policies。
所在位置 行:1 字符: 1
+ .\1.ps1
+ ~~~~~~~
    + CategoryInfo          : SecurityError: (:) []，PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

PS C:\Users\redapple\Desktop> .\1.ps1

**Comment by lizongzeshunshun** [comment]
要设置一下：
`Set-ExecutionPolicy -ExecutionPolicy bypass`
以上在powershell内执行

**Comment by redapple0204** [comment]
厉害了！
+                       ~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest]，ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameter,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

Downloading Issues 17
Invoke-WebRequest : 无法处理参数，因为参数名称“O”具有二义性。可能的匹配项包括:  -OutFile -OutVariable -OutBuffer。
所在位置 C:\Users\redapple\Desktop\1.ps1:7 字符: 23
+     Invoke-WebRequest -O ([string]$i + ".html") $issue_page
+                       ~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest]，ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameter,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

Downloading Issues 18
Invoke-WebRequest : 无法处理参数，因为参数名称“O”具有二义性。可能的匹配项包括:  -OutFile -OutVariable -OutBuffer。
所在位置 C:\Users\redapple\Desktop\1.ps1:7 字符: 23
+     Invoke-WebRequest -O ([string]$i + ".html") $issue_page
+                       ~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest]，ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameter,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

Downloading Issues 19
Invoke-WebRequest : 无法处理参数，因为参数名称“O”具有二义性。可能的匹配项包括:  -OutFile -OutVariable -OutBuffer。
所在位置 C:\Users\redapple\Desktop\1.ps1:7 字符: 23
+     Invoke-WebRequest -O ([string]$i + ".html") $issue_page
+                       ~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest]，ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameter,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

Downloading Issues 20
Invoke-WebRequest : 无法处理参数，因为参数名称“O”具有二义性。可能的匹配项包括:  -OutFile -OutVariable -OutBuffer。
所在位置 C:\Users\redapple\Desktop\1.ps1:7 字符: 23
+     Invoke-WebRequest -O ([string]$i + ".html") $issue_page
+                       ~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest]，ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameter,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

Downloading Issues 21

**Comment by lizongzeshunshun** [comment]
好吧，你把-O改成-OutFile

**Comment by redapple0204** [comment]
下载下来的文件有问题
https://tpedutw-my.sharepoint.com/personal/redapple0204_tp_edu_tw/_layouts/15/guestaccess.aspx?docid=1b60c92dc7f734714ba379fd807e5252c&authkey=Ac84J7IEDK3539mEoNZxjYA

**Comment by lizongzeshunshun** [comment]
let me see

**Comment by lizongzeshunshun** [comment]
```
$repo_url = Read-Host("Please Enter Repo's URL(Main Page)") 
$issues_number = Read-Host("Please enter issues number")
$issue_page = $repo_url + "/issues/"
for($i=1;$i -le $issues_number;$i++)
{
    echo ("Downloading Issues " + [string]$i)
    Invoke-WebRequest -OutFile ([string]$i + ".html") ($issue_page + [string]($i))
}
```

这样

**Comment by redapple0204** [comment]
可以了，thx

**Comment by lizongzeshunshun** [comment]
我试试Linux安装

**Comment by redapple0204** [comment]
linux有ps这玩意？

**Comment by lizongzeshunshun** [comment]
https://github.com/PowerShell/PowerShell/releases

**Comment by redapple0204** [comment]
还真有？试试看

**Comment by lizongzeshunshun** [comment]
我试试

**Comment by redapple0204** [comment]
ok

**Comment by lizongzeshunshun** [comment]
ss会稍微失效一段时间 然后需要重新配置，到时候我TV

**Comment by redapple0204** [comment]
ok,如果**没有意外的话**这几天我都能玩上不间断开机，顺便
tv账号：358 335 578
key：redapple
看到后删

**Comment by lizongzeshunshun** [comment]
..

**Comment by redapple0204** [comment]
。。装了个github汉化插件感觉很奇怪

**Comment by lizongzeshunshun** [comment]
截图看看

**Comment by redapple0204** [comment]
噗没有代理简直不能活了，啥都访问不了
https://tpedutw-my.sharepoint.com/personal/redapple0204_tp_edu_tw/_layouts/15/guestaccess.aspx?folderid=1f70feb3b51744790a495caff5d703269&authkey=AU8jBOHA1Sux3m3Pa8R2ggE

**Comment by redapple0204** [comment]
还是odb大法好，没被墙

**Comment by redapple0204** [comment]
那个github一下还有点赞简直神...

**Comment by lizongzeshunshun** [comment]
。。。

**Comment by lizongzeshunshun** [comment]
看起来不错

**Comment by redapple0204** [comment]
翻译得比google自带的好。。毕竟是一个项目来的

**Comment by lizongzeshunshun** [comment]
success！！

![image](https://cloud.githubusercontent.com/assets/10304206/22885574/f3884d72-f234-11e6-8206-3ebb86ca3b6c.png)

**Comment by redapple0204** [comment]
祝贺！
话说干嘛要用远程连接。。

**Comment by lizongzeshunshun** [comment]
go to bed ,
tomorrow!

**Comment by redapple0204** [comment]
ok！我先用破灯笼撑一下
