### ISSUE TITLE
考完了吧

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#157]
。。@lizongzeshunshun

**Comment by lizongzeshunshun** [comment]
yep

**Comment by redapple0204** [comment]
真悲哀啊....开学靠份量应该不高吧

**Comment by lizongzeshunshun** [comment]
开学考感觉良好。。。

**Comment by redapple0204** [comment]
那就祝贺，不知道翠园的开学考难不难，我没经历过。。。
顺便有时间弄ss了么。。

**Comment by lizongzeshunshun** [comment]
比区里的难很多，特别是英语，幸好我还比较good at 英语

另外电信比天威不知道高到哪里去了
![image](https://cloud.githubusercontent.com/assets/10304206/22929507/0fa204c2-f2f7-11e6-9035-bd8533eddd09.png)

**Comment by redapple0204** [comment]
1.英语干嘛要出那么难，按理说应该数学要难。。
2.电信出口流量没话说，但是天威便宜（贪便宜没有好下场，国外基本没法访问）

**Comment by lizongzeshunshun** [comment]
1. 英语绝对有竞赛难度了
2. 移动才叫6，随便一个vps能满速

**Comment by redapple0204** [comment]
1.中考难度？为中考做铺垫？
2.移动的听说很难翻墙。。

**Comment by lizongzeshunshun** [comment]
1. 个人觉得应该有中考难度了
2. 没ss很难，有ss超快。。

**Comment by redapple0204** [comment]
1.话说这样的话翠园应该要叫~翠园外国语学校~ 话说是谁出题啊？你们的英语老师？
2.也就是hosts不行咯。。。

**Comment by redapple0204** [comment]
另外你这windows下的字体不忍直视。。。

**Comment by lizongzeshunshun** [comment]
1. 不是，1班的老师
2. 我这是远程连接

**Comment by lizongzeshunshun** [comment]
因为我现在电脑配置不足，所以只能这样

![image](https://cloud.githubusercontent.com/assets/10304206/22929777/4e4126b2-f2f8-11e6-92ee-7b00533000f8.png)

负载均衡233

**Comment by redapple0204** [comment]
1.毕竟是重点班，就像上次期末考试我们班数学老师出死难死难的，噗
2.好吧，远程连接不会减慢速度么？

**Comment by lizongzeshunshun** [comment]
2. 稍微有一点。。

**Comment by redapple0204** [comment]
电脑配置不足，你用的win7不是6G的么。。

**Comment by redapple0204** [comment]
内网还好，像你tv一下能减慢好多

**Comment by redapple0204** [comment]
另外任务栏放在左边仿ubuntu。。

**Comment by lizongzeshunshun** [comment]
@redapple0204 这个6G的CPU烂，那个CPU好一点的内存烂，正好平衡一下

**Comment by redapple0204** [comment]
cpu烂的话应该不会影响很大吧，我的i3-2100都还能用。。
另外2G内存无法忍受，win10一开机就1.4G，还怎么玩啊

**Comment by lizongzeshunshun** [comment]
对啊。。

**Comment by lizongzeshunshun** [comment]
话说这样切iss好麻烦，直接全部这个issue讨论吧

**Comment by redapple0204** [comment]
你为啥不装linux+i3或者xp之类的。。

**Comment by redapple0204** [comment]
好

**Comment by lizongzeshunshun** [comment]
xp啥都干不了，linux不习惯，再加上win10确实不错

**Comment by redapple0204** [comment]
1.xp的话还算勉强吧，py的3.4可用，go老版本也可以，我无法容忍的是git的图形化用不了
2.同，半年不用完全忘光了
3.win10的磁盘100%和移动硬盘老是无法弹出还是一个很大的问题，不过中折了下还是用早期的beta吧。。

**Comment by lizongzeshunshun** [comment]
1. xp生命周期已经over了
2. 。。
3. 到时候我要换ssd

**Comment by redapple0204** [comment]
1.不过好像没有什么影响啊....除了软件越来越多不支持
2.ssd现在好像很贵啊。。

**Comment by lizongzeshunshun** [comment]
1. 那个界面不能忍
2. 但是速度很6啊。。听说Intel的3D XPoint的SSD速度逼近内存（预计2019出

感觉我们讨论是多线程的，别人是单线程的。。

**Comment by redapple0204** [comment]
1.确实很难看啊...可以装个美化包什么的
2.2019还好远啊...我倒觉得不如弄个内存盘（如果内存>=32G的话)来装win10
3.多线程效率高，而且那种单线程一般适用于qq之类的，本来github就像贴吧一样多线程更舒适。。

**Comment by redapple0204** [comment]
另：wvb吧真有人搞了个内存系统，据说快的飞起

**Comment by lizongzeshunshun** [comment]
1. 对
2. 然而内存是易失存储，一停电。。。。。。。。。。3D XPoint是非易失的，而且速度直追内存

**Comment by redapple0204** [comment]
不是内存可以保存到硬盘的么.... 
另外那玩意肯定很贵吧

**Comment by redapple0204** [comment]
那东西rhel6.x竟然还支持，好老的东西了。。

**Comment by lizongzeshunshun** [comment]
根据wiki“price is harf of the DRAM(普通内存)"

**Comment by redapple0204** [comment]
噗原来要到wiki上，我在百度搜了半天啥都没有

**Comment by redapple0204** [comment]
>2015年七月英特尔是指使用名称下的技术存储设备Optane而美光科技使用的名称QuantX
 
15年就计划了？

**Comment by lizongzeshunshun** [comment]
是啊

**Comment by redapple0204** [comment]
>因此封装密度将是DRAM的4倍。

封装密度是什么鬼

**Comment by lizongzeshunshun** [comment]
还有一个3D NAND看起来也不错

**Comment by lizongzeshunshun** [comment]
。。。

**Comment by redapple0204** [comment]
内存条好像就没什么优势了吧

**Comment by lizongzeshunshun** [comment]
。。。

**Comment by redapple0204** [comment]
现在ddr5都竟然有了。。

**Comment by redapple0204** [comment]
哎生物寒假作业都没写完，明天是最后期限了，看来今天凌晨要赶了。。

**Comment by redapple0204** [comment]
那么多简直超乎我的意料
