### ISSUE TITLE
谢了。。

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#158]
@lizongzeshunshun 真希望中国不要那么快封ss。。
话说调整下我电脑的开机时间
周一到周五：晚上6-8点开机，次日早上6点45分左右关机
周末：没有意外全天开机

**Comment by lizongzeshunshun** [comment]
1. OK
2. 封了ss很难封ssr（混淆大发好

**Comment by redapple0204** [comment]
直接封端口==

**Comment by lizongzeshunshun** [comment]
。。可以使用
**Iptables (TM)** 动态端口技术，专门针对封端口

**Comment by redapple0204** [comment]
到时候中国直接禁止出口流量就好晚了 ：D
看这句是吃枣药丸啊

**Comment by lizongzeshunshun** [comment]
那就成了天朝局域网了。。
不过这样后果很严重
1. 很多大型网站解析失效（DNS根服务器不在中国
2. 很多网站引用出错，Windows更新出错

**Comment by redapple0204** [comment]
那就给几个网站白名单呗，另外windws更新有中国的服务器吧

**Comment by lizongzeshunshun** [comment]
没有把，是香港和台湾了（虽然也是中国。。。

**Comment by redapple0204** [comment]
中国竟然没有服务其，这不科学

**Comment by lizongzeshunshun** [comment]
知乎上有说原因的

**Comment by redapple0204** [comment]
我看到有cdn==

**Comment by lizongzeshunshun** [comment]
move to another issue
