### ISSUE TITLE
数学考试（包含中考）将会大幅提升难度

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#159]
@lizongzeshunshun 我妈下午开了一个什么教研会，说由于深圳的数学中考过于简单导致高考全国卷的时候得分普遍低。。
所以从这个学期开始将会大幅提升出卷难度（初三的这次考试均分才40多），然后中考将也会提升难度

**Comment by redapple0204** [comment]
好像什么新政策&考试加大难度都是在我们这一届开始有的。。真是太™倒霉

**Comment by lizongzeshunshun** [comment]
我去

**Comment by redapple0204** [comment]
。。哎，真悲哀
到时数学难到死啊

**Comment by lizongzeshunshun** [comment]
。。反正要难一起难

**Comment by redapple0204** [comment]
嗯，据说全科都要难了。。
当然生物和地理不会，还好赶上了末班车。。
理化的难度提升很明显，别的科还算好。。

**Comment by lizongzeshunshun** [comment]
还有github备份工具已经写好了，**从后天开始**每天执行一次，每次将会打包以下内容
* 项目主文件的所有内容
* 所有Issues以及Pull Requests

**Comment by redapple0204** [comment]
wiki呢？

**Comment by lizongzeshunshun** [comment]
嗯，到时候加上wiki

**Comment by redapple0204** [comment]
好。。
我记得github的issue不是有api吗

**Comment by lizongzeshunshun** [comment]
正想着用api，不过我实在太烦json解析了
到时候试试

**Comment by redapple0204** [comment]
不过这样子的话就没法恢复issue了。。

**Comment by lizongzeshunshun** [comment]
？

**Comment by redapple0204** [comment]
用api备份的issue是可以恢复到另外一个项目上的。。

**Comment by lizongzeshunshun** [comment]
其实这个也可以，再写个发送程序读取iss内容发送即可

**Comment by redapple0204** [comment]
一般的发送程序不行的。。要不会像上次一样误判垃圾邮件然后被封

**Comment by lizongzeshunshun** [comment]
。。。

**Comment by redapple0204** [comment]
话说这样打包会浪费不少的空间吧。。

**Comment by lizongzeshunshun** [comment]
issues全部压缩也就1.4M，当然项目占的空间大，到时候定期上传到OD并删除服务器文件

**Comment by redapple0204** [comment]
话说OD的api不是很难找么。。
另外为啥删除的文件会保存到.git里，早知道就不删了。。

**Comment by lizongzeshunshun** [comment]
我自己保存。。

**Comment by redapple0204** [comment]
1.好吧，你服务器应该也是15G硬盘吧。。
2.那么坑，不存到github服务器？

**Comment by lizongzeshunshun** [comment]
1. 对
2. 这就是git的原理。。可以随时恢复到项目的任意时刻

**Comment by redapple0204** [comment]
git能恢复？

**Comment by redapple0204** [comment]
15G应该略小吧

**Comment by lizongzeshunshun** [comment]
是啊

**Comment by redapple0204** [comment]
按理说不应该有几百G的备用空间么

**Comment by lizongzeshunshun** [comment]
不可能。。。

**Comment by redapple0204** [comment]
好吧，看错，是传输。。
话说这种硬盘应该是ssd吧

**Comment by lizongzeshunshun** [comment]
基本上把，要不就是很快的机械（写入大概400M/s

**Comment by redapple0204** [comment]
那还不如ssd呢，，
另外这输入法怎么一卡一顿的

**Comment by redapple0204** [comment]
我看到知乎上说要github学生包纯属因为那个DO免费的50刀。。

**Comment by lizongzeshunshun** [comment]
对啊。。

**Comment by redapple0204** [comment]
话说看到有些公司丧心病狂的要看github：https://www.zhihu.com/question/29776756
感觉我们的账号都满足要求了。。

**Comment by lizongzeshunshun** [comment]
go to sleep, 8

**Comment by redapple0204** [comment]
8
