### ISSUE TITLE
请问几个关于linux的问题

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#16]
请问一下
1.有些linux低版本的源已经废掉了（例如kali1.1.0），但是我却喜欢用低版本的，造成了无法安装任何软件，然后更改成新版本的原一安装软件重启系统就崩了，如果我就是要用低版本的，请问怎么才好
2.在linux上装vbox打开的时候会出现内核驱动错误，但是使用网上的方法却没用（apt-get install linux-headers-$(uname -r)或pacman -S linux-headers-$(uname -r)是无效的），以前在用1.1.0的时候直接更新下系统就会自动出现这个内核，可是2.0就不行了。（安装dkms无效）@K-Guan

**Comment by redapple0204** [comment]
then@lizongzeshunshun 以后可能不用qq了，就在github上说算了

**Comment by redapple0204** [comment]
@lizongzeshunshun

**Comment by K-Guan** [comment]
1. 不知道，还是建议用新版的。Linux 的话不像 Windows ，不更新软件根本没法用。

2. 如下：

    ```bash
    sudo pacman -S virtualbox linux-headers --noconfirm
    sudo modprobe vboxdrv
   virtualbox
    ```

    这是在 Arch Linux 上的做法，Kali 我就不知道了。

**Comment by K-Guan** [comment]
其实，像上面有关 `virtualbox` 的安装指南英文版本的 Arch Wiki 的 virtualbox 词条都有说（中文我就不知道了），**有问题，看 Wiki** 啊。

**Comment by lizongzeshunshun** [comment]
@redapple0204 OK. 反正Githib更方便。

**Comment by redapple0204** [comment]
@K-Guan 好的，那我等下再看看vbox的wiki
