### ISSUE TITLE
crossover 有更新吗？

### ISSUE THREAD

**Issue by jicki** [redapple0204/my-boring-python#160]
crossover 下载地址在哪里！

有没有更新1.6

**Comment by lizongzeshunshun** [comment]
@jicki 
请注意看提Issue的提示，贴吧链接有下载破解补丁。经过吧友测试1.6可以破解（1.6原版需要自己安装）
如果有需要，我们可以帮助安装。

cc @redapple0204

**Comment by redapple0204** [comment]
1.6可以破解，已证实

**Comment by lizongzeshunshun** [comment]
如果还有问题，请重新打开issue。
