### ISSUE TITLE
关于crossover的讨论

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#163]
在催交作业的大前提下终于过完了一周。。。
家长群真是个可恶的东西。。。
话说你们的第一周也不好过吧
@lizongzeshunshun

**Comment by lizongzeshunshun** [comment]
yep
，体育课我觉得我要爆炸了。。。

**Comment by redapple0204** [comment]
你们体育课应该很惨吧！我记得当初要跑3还是4圈。。
感觉这样惨无人道而且没效果==

**Comment by redapple0204** [comment]
话说为啥本项目会有那么多的访问量，吃惊==
![10](https://cloud.githubusercontent.com/assets/16254644/23062670/a888eb64-f541-11e6-830b-2477efd51cde.PNG)

**Comment by lizongzeshunshun** [comment]
我去

**Comment by lizongzeshunshun** [comment]
奥，我知道了！是我的自动备份程序

**Comment by redapple0204** [comment]
他啊们是怎么找到这里的==

**Comment by redapple0204** [comment]
你看2.10号。。

**Comment by lizongzeshunshun** [comment]
。。。。

**Comment by redapple0204** [comment]
那些特殊的访问者是什么鬼==

**Comment by Silver47Gin** [comment]
我是搜索crossover 破解版过来的

**Comment by Silver47Gin** [comment]
貌似百度贴吧上你发的那个没法下载，一直没资源

**Comment by lizongzeshunshun** [comment]
@redapple0204 unique在这里不是特殊的意思，是单独的访问者

@Silver47Gin 稍后

**Comment by lizongzeshunshun** [comment]
@Silver47Gin 贴吧上的链接是可以下载的，只不过国内直连比较慢，您可以使用VPN等工具翻墙下载，如果有需要，我们可以将资源移动到微软OneDrive

**Comment by lizongzeshunshun** [comment]
cc @redapple0204

**Comment by Silver47Gin** [comment]
@lizongzeshunshun 我挂个vpn试一下，谢谢了

**Comment by Silver47Gin** [comment]
话说这个crossover破解替换用的so是不是deepin系统里面的

**Comment by lizongzeshunshun** [comment]
@Silver47Gin
这个我真不知道，你可以和@redapple0204 讨论

**Comment by redapple0204** [comment]
@Silver47Gin 不是，是另外的批量授权的so

**Comment by redapple0204** [comment]
@Silver47Gin 你可以试试在项目的readme。md中的tmp文件夹里有提取的so

**Comment by Silver47Gin** [comment]
ok，我去直接下载so吧，谢谢dalao

**Comment by redapple0204** [comment]
https://tpedutw-my.sharepoint.com/personal/redapple0204_tp_edu_tw/_layouts/15/onedrive.aspx?id=%2fpersonal%2fredapple0204_tp_edu_tw%2fDocuments%2f%E5%88%86%E4%BA%AB%2ftmp&FolderCTID=0x012000A5CA3BE026B1014B9EB822D90151DA44

**Comment by Silver47Gin** [comment]
thinks，下好了

**Comment by lizongzeshunshun** [comment]
@redapple0204 我得出去一下，8

**Comment by Silver47Gin** [comment]
已star

**Comment by redapple0204** [comment]
@lizongzeshunshun 好

**Comment by lizongzeshunshun** [comment]
@Silver47Gin 谢谢支持

**Comment by redapple0204** [comment]
thx
