### ISSUE TITLE
Stars over 10 Party

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#164]
@redapple0204 

项目Star超过10个了，特此发本Issue庆祝一下（其实是从hosts项目学来的习俗~）。

10个Star仅仅是个开始，但是仍是个不错的成绩，再此庆祝，也放松一下，本Issue可以讨论任何问题，并且将会在一周后关闭。

顺便祝本项目越做越好

**Comment by redapple0204** [comment]
@lizongzeshunshun 哈哈，祝贺祝贺
当初我是根本没想到有人会来这里的
一切的开始还是要感谢于你，本来该该项目只是计划与@K-Guan 聊天的，再加上3B科技的煽风点火，issue的地方确实火了，然而住项目还是一团糟。
到了你8月底的时候，发送了一个生死攸关的PR（ #22  ），于是项目转危为安
再加上后面完善的许多分项目，让这个主项目更加壮大了。
不过很遗憾的是，这个学期是最后一个能玩的学期了，等到过了这个学期就要到四年后才能继续玩了。

**Comment by redapple0204** [comment]
（如果以后有面试官看到我们的github肯定会很吃惊的）

**Comment by lizongzeshunshun** [comment]
1. 哈哈，3B科技。
2. 对啊，初三以后就真的没时间了（说不定高一还有点时间）。总的来说，接下来的4年必将充满困难与挑战。技术的革新呈指数性，也不知道在这4年里，会有多少新技术被发明，会发生多少变革。我们应该以乐观态度面对IT行业的发展。

1461天，说长不长，说短不短，但足以起决定性的作用。

未来总是不可预知的，但正如《三体》中的那句话：

> 光锥之内，即是命运。

发生了，只能面对，没有余地。

还是记住那句话。

> **不忘初心，方得始终。**

3. 对呀。

这学期好好玩玩吧。。

**Comment by redapple0204** [comment]
1.自从他从github（技术性）转入游戏（叫做王者什么鬼的？）就一发不可收拾了...可悲！

2.高一也别想有时间了吧...周一到周五（或周六？）累的半死，然后剩下的两天（一天？）回家，还要上补课班，oh，瞬间感觉生活没有了希望......

4，5年，总体感觉肯定非常忙碌，非常的苦，望不到头

就算小学的4-5年也好像很久的样子。

至于IT发展，等我们过了这4年与世隔绝，早都不知道发展到哪里去了，到时候就感觉是从监狱里出来的一样。

对啊，谁知道未来是怎么样的呢，就这样吧，船到桥头自会直


3.中国的教育最可悲就在这一点，累死累活的学了几年，这些应试的只是全都没用。

**Comment by lizongzeshunshun** [comment]
总感觉我们要面对大事了。。

**Comment by redapple0204** [comment]
第一件大事是1年后，还有就是4年后的....
两次大坎，过了就**彻底**解放了

**Comment by lizongzeshunshun** [comment]
对啊。我决定开个Issues。wait

**Comment by redapple0204** [comment]
ok

**Comment by lizongzeshunshun** [comment]
哎。。感觉现在已经有点压力了

**Comment by redapple0204** [comment]
应该是很大的压力
在这应试教育下没有压力才怪
每个人都不再是一个人，而是一台被肉体包裹的机器。

**Comment by lizongzeshunshun** [comment]
。。。。

**Comment by redapple0204** [comment]
话说到时候希望这个项目不要因为种种原因关掉。
留作中学时代的纪念。。。

**Comment by lizongzeshunshun** [comment]
对。

**Comment by redapple0204** [comment]
不知道github还在不在。。
毕竟一直在亏尊

**Comment by lizongzeshunshun** [comment]
.。。
