### ISSUE TITLE
你有啥需要的么。。

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#167]
最近可能要去一个亲戚家拿一些鼠标，内存条什么的，你有什么需要的么？我顺便帮你拿下。。
@lizongzeshunshun

**Comment by lizongzeshunshun** [comment]
不需要。。内存我这个貌似是DDR1（233），估计是没用的，老家带了一个i3回来，插不上主板。。。

**Comment by redapple0204** [comment]
ddr1.。那得多古老，干嘛不换下
话说你一直用那蛋疼的amd不卡么？

**Comment by lizongzeshunshun** [comment]
@redapple0204 卡得要死

顺便，你的TV Number?

**Comment by lizongzeshunshun** [comment]
不用了，知道了

**Comment by redapple0204** [comment]
哦，我看到你链接了

**Comment by redapple0204** [comment]
@lizongzeshunshun 顺便说下。。我正在下载文件，等下你链接上来的时候记得先ctrl+c在cmd中终止下载，要不会很卡的。

**Comment by redapple0204** [comment]
另我下午要出去，没有意外的话电脑不会关机，你也可以远程过来搞事情。。

**Comment by lizongzeshunshun** [comment]
ok
