### ISSUE TITLE
windows不能通过文件类型判断打开方式太垃圾了

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#171]
@lizongzeshunshun 最近在下7850，结果下了好多次用iso打开都提示损坏
然后去分享人的网盘里一看是rar格式的...
fuck.......浪费了好多时间

**Comment by lizongzeshunshun** [comment]
![image](https://cloud.githubusercontent.com/assets/10304206/23102448/5591643c-f6e4-11e6-851c-850d89d6b930.png)

**Comment by lizongzeshunshun** [comment]
没会员速度不行。。

![image](https://cloud.githubusercontent.com/assets/10304206/23102481/0137f850-f6e5-11e6-95e7-62f435e69347.png)

**Comment by lizongzeshunshun** [comment]
unstable
![image](https://cloud.githubusercontent.com/assets/10304206/23102509/a9e3022e-f6e5-11e6-8208-5afd9bce3392.png)
