### ISSUE TITLE
I found an interesting thing！

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#172]
[PanDownload_v1.1.0 .tar.gz](https://github.com/redapple0204/my-boring-python/files/787328/PanDownload_v1.1.0.tar.gz)
相当于是GUI的pcs了吧。。
@lizongzeshunshun

**Comment by lizongzeshunshun** [comment]
早就看到了。。

**Comment by redapple0204** [comment]
感觉速度还不如pcs。。不知为何

**Comment by lizongzeshunshun** [comment]
感觉go写的那个pget不错

**Comment by redapple0204** [comment]
对，作者也回应我了。。

**Comment by redapple0204** [comment]
他说这是我设置过多线程的原因

**Comment by redapple0204** [comment]
可惜不支持windows
