### ISSUE TITLE
难道我遇到了一个假so？

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#173]
一个一般的问题提出来（http://stackoverflow.com/questions/42344403/in-python3-how-do-i-choose-to-encode-in-order-to-be-able-to-read-the-page-corre ）没什么人回答，然后也没有反对...
瞬间感觉so的人的水平降低了好多？
@lizongzeshunshun

**Comment by lizongzeshunshun** [comment]
in addition to English。。好奇怪的表达。。

**Comment by redapple0204** [comment]
好想换成except会好些吧

**Comment by lizongzeshunshun** [comment]
对。。

**Comment by redapple0204** [comment]
话说刚接到消息电脑也要参加中考（或许是综合评价。。）

**Comment by lizongzeshunshun** [comment]
cool

**Comment by redapple0204** [comment]
不过我真心不想学flash，ppt什么的。。
vb和html还算勉强，不过也只是有些兴趣

**Comment by redapple0204** [comment]
要是能学python就好了

**Comment by lizongzeshunshun** [comment]
。。对啊

**Comment by redapple0204** [comment]
这就是一个很大的弊端......
为啥老学不是用的东西

**Comment by redapple0204** [comment]
包括vb学的也不实用。。

**Comment by lizongzeshunshun** [comment]
对啊

**Comment by redapple0204** [comment]
我希望大学的计算机系不要这样。。
