### ISSUE TITLE
论学python用您推荐的电子书配合着这本书学习如何？

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#18]
表示今天弄了这本书，您觉得配合着使用会不会更好呢？
![default](https://cloud.githubusercontent.com/assets/16254644/15674887/d4b0df6a-2771-11e6-9ba6-6c0051461c35.PNG)
@K-Guan

**Comment by K-Guan** [comment]
@redapple0204 不知道，没看过。其实在国外论坛混久了我其实是不是太感冒国内的教材。不过这个教材要是语法什么的都比较标准，然后教的还可以就行。

这样，你贴段里面的比较复杂的代码（以及其说明）我瞧瞧，也好评估这本书的实用性。

**Comment by redapple0204** [comment]
@K-Guan 
![default](http://imgsrc.baidu.com/forum/w%3D580/sign=3fc943e00e24ab18e016e13f05f8e69a/c89bf7fae6cd7b89f3fe9c45082442a7db330e86.jpg)

**Comment by K-Guan** [comment]
这个……还是有些地方有问题的。比如说：

    print ('stuff')

的正确写法是：

    print('stuff')

From **[PEP 8 - Pet Peeves](https://www.python.org/dev/peps/pep-0008/#pet-peeves)**:

> Immediately before the open parenthesis that starts the argument list of a function call:
    Yes: spam(1)
    No:  spam (1)

**Comment by redapple0204** [comment]
@K-Guan (所以说还是不用好了？）

**Comment by K-Guan** [comment]
@redapple0204 书都买了不看也可惜了。而且不是每个人的程序都能写到“最高境界”（不论什么类型的程序都能信手拈来，且即不会有 bug 及上面说的格式错误）。

所以，碰到类似这样的书，还是取长补短。学习好的一部分，纠正不太好一部分，剩下不好的一部分干脆别看。当然了，如果你没法分辨这些问题，我还是建议你现将这本书放在一边，用上两个星期将我给你推荐的书看完再说。

**Comment by K-Guan** [comment]
另外因为这本书我没看过，而你拍的那部分略显深奥，所以我并不知道它是否适合你这样的初学者但掌握一定基础的人。相比之下，我还是建议先去看看我前面说的两本书。

**Comment by K-Guan** [comment]
另外一提，这几张照片都是描述库……还是不是很复杂（前面的 XML parser）就是八辈子用不上（threading，从我开始学 Python 起我就没用过一次）的库的用法，我还是建议你现将基础的语法学好。比方说：

```python
sum(i if num - i > 0 else 5 for i in l if i % 2)
```
<sub>[*还记得吗？*](https://github.com/redapple0204/my-boring-python/issues/15#issuecomment-217414070)</sub>

那么现在，请写出一个可以根据命令行参数，返回 GitHub 项目链接的小程序（别告诉我你两行搞不定）：
![2016-06-01-210324_780x71_scrot](https://cloud.githubusercontent.com/assets/13862535/15710375/5f1c8652-283c-11e6-8462-4bc3dec99819.png)

进阶挑战：

1. 如果参数过多或过少，返回错误消息并退出：
    ![2016-06-01-210856_677x105_scrot](https://cloud.githubusercontent.com/assets/13862535/15710571/31bc88dc-283d-11e6-8a85-730156b0a6b2.png)

2. 不在意参数过多或过少，但是要将参数反复累加到链接的后面：
    ![2016-06-01-211209_980x141_scrot](https://cloud.githubusercontent.com/assets/13862535/15710661/97fce542-283d-11e6-9337-57e115e389b3.png)

**Comment by K-Guan** [comment]
顺带一提，我的 JavaScript 老师曾在我想学 jQuery 的时候说过这么一句话，后来我就果断放弃了。现在我把原话的前半部分贴过来，希望对你有帮助：

>  But yeah, I'd suggest focusing on JS for now. Libraries can be learnt later.

所以呢，还是先专注于基本的语法，复杂以及不常用的库什么的慢慢来。

**Comment by redapple0204** [comment]
@K-Guan 1.我买这本书的主要是为了看那些您推荐的书如果我看不懂得可以翻翻，毕竟这本书是否零基础，比较详细一点 
2.您说要拍难一点的我就顺手拍了一张难的，事实上前面还是挺简单的
3。第一个程序可以，但是后面似乎有点困难。。（话说怎么github）上传不了照片了
4.还是虫基本的慢慢来

**Comment by K-Guan** [comment]
> Attach files by dragging & dropping,  Choose Files [selecting them](<click this>), or pasting from the clipboard.

**Comment by K-Guan** [comment]
说起来，你连这种基础的程序都有困难……还是 *多多学习* 吧。

**Comment by redapple0204** [comment]
@K-Guan 1.确实，我的基础非常非常的垃圾，反正我都是跳着学的。。。
2.不，这里网络不好，传不上去

**Comment by K-Guan** [comment]
@redapple0204 哦，那把你的代码贴上来？（另外不能跳着学呀，还是得一步一个脚印。有不懂的问我就好。）

**Comment by K-Guan** [comment]
```
\```python
# put your code here
```
```

**Comment by redapple0204** [comment]
@K-Guan 1.好的
2.这样?
import sys
 
a="https://github.com/"
b=(sys.argv[1])
c=(sys.argv[2])
d="/"
print(a,b,d,c)

**Comment by redapple0204** [comment]
@K-Guan 关于第二个程序，好像错误值返回在这本书里有，等下看看，明天试试，第三个，恐怕真的有难度

**Comment by K-Guan** [comment]
你确定这个办法好？

![result](http://i.stack.imgur.com/WLYrp.png)

我说过要空格了吗？

------------------

好吧，先枪毙了你的代码，现在让我们来逐步分析下你的代码：

1. 有些时候是不需要无聊的给每个东西一个变量的。

        print("https://github.com/",(sys.argv[1]),"/",(sys.argv[2]))

    是不是一样？是不是更加简单？尤其是只用一次，且完全没必要的时候，是不需要创建一个新变量的。另外你选择的变量名也太垃圾了，比如说 `for file in files` 就比 `for i in files` 强多了。

2. 根据 PEP 8，首先在给变量赋值时，如果数值不需要放在 tuple 里就不要在周围加括号。而且赋值时 **等于号** 周围要有空格。调用函数时，用来分割参数的逗号后面需要也一个空格：

    ![before](http://i.stack.imgur.com/vidKR.png)
    ![after](http://i.stack.imgur.com/hJIg9.png)

3. 你……真的没学过怎样合并字符串？

    ![string + string + string](http://i.stack.imgur.com/M3sl6.png)

该教的都教给你了，现在自己去研究研究我用的这几个函数以及 `+` 的用法。我希望在明天晚上之前我能看到你的结果（至少完成上面第一项，应该也能完成你认为很麻烦的第三项）。

如果这些我都教给你了你还是写不出来……我感觉你还是改行的好……

**Comment by K-Guan** [comment]
至于第二项我不着急，你慢慢研究。给你一个星期的时间（当然了，是“工作日”……或者说是有空玩的日子）总可以吧？

**Comment by K-Guan** [comment]
哦，顺便一提 Python 还支持类似 C 语言的 `%s`：

![2016-06-02-230411_353x58_scrot](https://cloud.githubusercontent.com/assets/13862535/15749828/7a4879e2-2916-11e6-9803-cb3a24b83918.png)

不过 `str.format()` 就是专门来取代它的。具体请看：https://pyformat.info/ ， 介绍了两者之间的区别与详细用法。

**Comment by redapple0204** [comment]
@K-Guan 1.好的，我一定认真研究
2.第一个程序是这样？
import sys
 
print("https://github.com/"+(sys.argv[1])+"/"+(sys.argv[2]))

**Comment by redapple0204** [comment]
顺便。。第三个多个的变量好像对我来说“很有难度”

**Comment by K-Guan** [comment]
不错，但是你为什么一定要加一对没必要的括号呢？ 另外加号周围也要空格：

```python
print("https://github.com/"+(sys.argv[1])+"/"+(sys.argv[2]))      # bad
print("https://github.com/" + sys.argv[1] + "/" + sys.argv[2])    # good
```

有关第三个，没学过 *list slicing* ?

```python
print("https://github.com/" + '/'.join(sys.argv[1:]))
```

上面的这个方法同样适用于第一个。

**Comment by redapple0204** [comment]
@K-Guan 我真的怀疑我的kali很有问题。
1.如果不加括号，kali直接会输出 sys.argv[1]而不疏结果
2.表示我先前用这个方法，但是kali却。。。
python my.py retg ewwwwwwwwwwwwwwwwr ewrtttttttttt 666 666 // 输入
https://github.com/retg/ewwwwwwwwwwwwwwwwr ewr //输出结果

所以说我还是换成arch好了。

**Comment by redapple0204** [comment]
@K-Guan 话说。。请问如何查看一个list里有多少个元素

**Comment by redapple0204** [comment]
@K-Guan 关于第二个。。我的思路是
import sys

list = (sys.argv[1:])

len(list)


if( (len(list) > 2):
	print('wrong')
else:
 print('6')
可是确有错误啊
 File "my - 副本.py", line 8
    if( (len(list) > 2):
                       ^
SyntaxError: invalid syntax
冒号哪里有错？教程就是这样写的啊

**Comment by redapple0204** [comment]
@K-Guan 第二个是这样的吗？
import sys

list = (sys.argv[1:])

notlike = len(list)


if (notlike > 2):
	print('wrong')
else:
	print("https://github.com/" + '/'.join(sys.argv[1:]))

**Comment by K-Guan** [comment]
1. ……我感觉和 Kali 无关。Python 版本是什么？
2. 错！……不过不是代码错：
  1. 为什么用 `list` 做变量名？你难道不知道 `list` 是最常用的内置函数之一吗？用这玩意做变量名的话还怎么用函数？@！￥#！@%@#%……@￥……
  2. Python 同样不需要在 `if` 后面放个括号。
  3. `notlike > 2` 是错误的。原因是 `sys.argv[1:]` 不含 `sys.argv[0]` (程序文件名)，而 `> 2` 也就是 `>= 3`。所以你的程序最低要求三个参数而不是两个。解决方案是用 `sys.argv` 代替 `sys.argv[1]`，或用 `>= 2` 代替 `> 2` 之类的。
  4. 另外一提，`list` 这个变量又是个没用的变量。我的建议是：只在直接用变量的值时需要 **重复复杂的操作** （如 `result = get_result('foobar') + find_name('kevin')`。本列中调用了两个函数，如果不将结果赋值给一个变量的话就需要多次调用这两个函数，导致不必要的时间浪费。）时 **方便快速、多次调用结果** 。而且你看，你明明可以两次调用这个变量却只用了一次……难道一个变量就不占用内存空间的么？
  5. 程序除了上述错误来说还能用，不过我的要求是参数过少也要报错哦。

**Comment by redapple0204** [comment]
@K-Guan 1.版本是3.2.x
2.list，好吧顺手就选了list。。。。
3.教程里的if有加括号。。
4.好像变量只能用一次了吧
5.现在又改了下，您看看
import sys

arch = sys.argv

notlike = len(arch)


if notlike > 3:
	print('数值太多')

elif notlike <= 2:  
    print ('数值不足')
else:	
	print("https://github.com/" + '/'.join(sys.argv[1:]))

**Comment by K-Guan** [comment]
1. ………………明明最新版是 3.5。3.2 也太老了点吧？
2. **永远不要用函数名当变量名！**
3. 我建议还是把 PEP 8 认真看看，然后代码都遵循 PEP 8 的规范写。至于教程怎么写那是教程的事情了。另外有不少不错的语法检查程序你可以去找找。
4. 谁告诉你的………………
5. 嗯，这样就对了。全部考核通过！不过：
    1. `arch` 是架构的意思吧？这个变量名真的合适？
    2. 到底为什么不直接 `len(sys.argv)` 就好？
    3. 缩进不是跟你说过要用 `\`\`\``了么？ GitHub 是支持 MarkDown 的。

**Comment by redapple0204** [comment]
@K-Guan 1.确实老了一点，刚刚更新变成3.4就好了
2.好的
3.怎么pep8又被墙了。。。
4.一楼的那个书
5.(1)好像没有冲突
(2)我怎么没想到！
(3)就是键盘左上角的```?
我试试
``` print('hello')

**Comment by K-Guan** [comment]
3. 今天六四，你懂的。

4. ………………我觉得一定是你理解错了，不然这书当柴火烧都不配……

5. 其实冲突不冲突没关系，只是不适合而已。这就好比 `my_list = ('this', 'is', 'a', 'tuple', 'actually')` 一样。
  有关 Markdown ，请看：
   - [Markdown 基础](https://help.github.com/articles/basic-writing-and-formatting-syntax/)
   - [代码块的使用与高亮](https://help.github.com/articles/creating-and-highlighting-code-blocks/)

**Comment by redapple0204** [comment]
@K-Guan 1.我的vpn几乎都挂掉了，仅只有几个活着
2.我也觉得
3.原来如此
4.好的，我去看看

**Comment by redapple0204** [comment]
好不容易才用openvpn连上，您看，全部超时
![default](https://cloud.githubusercontent.com/assets/16254644/15796649/012db6ca-2a34-11e6-8b92-9cd617c0aa34.PNG)

**Comment by K-Guan** [comment]
别提了，我的 PIA 根本没法连。暂时先用 hosts 凑合着。

**Comment by redapple0204** [comment]
@K-Guan hosts的google慢的要死，10s都打不开

**Comment by K-Guan** [comment]
我这边其实还是可以的……总比没的用好不是？

**Comment by redapple0204** [comment]
@K-Guan 只能说勉强能用
我觉得windows的vpn客户端链接率比linux高好多，windows几乎都可以连接，linux全都失败了

**Comment by K-Guan** [comment]
@redapple0204 唉？首先 Github 我可以直接用，然后 `openvpn` 配合我的 PIA 简直神速，不出5秒连接 VPN 完全没问题。

（相比之下，家人用的 Windows 客户端反而费劲了。）

**Comment by redapple0204** [comment]
@K-Guan 好像是我这里的垃圾天威限制了github访问；还有就是我的vpn供应商是国内的一个企业，所以说对linux支持非常非常不好（正常情况下有一个能连上已经不错了，要知道总共几百个啊服务器啊）

**Comment by K-Guan** [comment]
所以还是国外 VPN 好用了。

**Comment by redapple0204** [comment]
@K-Guan 现在我发现国内的东西没有一样是好的

**Comment by K-Guan** [comment]
你总算知道了。说起来我的 VPN 又能用了，还是挂着 VPN 自在。

**Comment by K-Guan** [comment]
对了，再给你出道题：

这里给你一些数据：

```
name: Adam - age: 38 - score: 77
name: John - age: 23 - score: 96
name: Bill - age: 46 - score: 98
name: Sam - age: 66 - score: 50
name: Alison - age: 77 - score: 86
name: Isabella - age: 19 - score: 99
name: Kerl - age: 22 - score: 44
```

嗯，上面是一个成绩单，你需要把它放到一个文件里。总之，现在需要你将结果按照年龄 **从大到小** 来排序，然后要求的输出格式类似于这样：

```
Alison: 86 (age 77)
Sam: 50 (age 66)
Bill: 98 (age 46)
Adam: 77 (age 38)
John: 96 (age 23)
Kerl: 44 (age 22)
Isabella: 99 (age 19)
```

---------------

别说你，这个程序我觉得有些麻烦（不过还是在3分钟内以6行的成绩写出来了）。鉴于对你来说可能比较麻烦，给你先标出难点吧：

- [`sorted()`](https://docs.python.org/3/library/functions.html#sorted)
- [`str.split()`](https://docs.python.org/3/library/stdtypes.html#str.split)
- [`dict()`](https://docs.python.org/3/library/stdtypes.html#dict)

当然了，如果你的方法和我的不一样的话也许上面的几个函数你是用不到的，但是参考下总是有用的。对了，有不会的先 Google ，找不到再问我。如果觉得没有头绪的话我可以适当给你点提示……先去写写看吧！

**Comment by K-Guan** [comment]
加强题：

1. 过滤掉年龄超过 60 的（这个……高强度的劳动会使老年人受不了的），以及分数低于 60 的（根本就不及格！）。
2. 试着用 **成绩，名字来代替年龄** 进行排序。

**Comment by redapple0204** [comment]
@K-Guan 好的，我会试试，不过。。由于现在已经进入
>>> 期末复习阶段

所以每天几乎没有时间可以玩python，有可能改成需要在暑假才能完成了，请您谅解

**Comment by K-Guan** [comment]
哦，那慢慢来吧。反正我不着急。

**Comment by redapple0204** [comment]
@K-Guan 好吧。。找了大量资料，总算"可能"完成了2/3
不过只是差不多“照套”，并没有很好地理解
代码：
>>>from re import findall
f = open('1.txt').read( )



print(f)
print(u"-------以上为文件内容------------------")
data = dict()
for i,j,k in findall('name: (\w+) - age: (\d+) - score: (\d+)',f):
	data[i]=[int(j),int(k)]
print(data)
print(u"-----------以上为第一次输出-----------------")
newdata = sorted(data.iteritems() , key = lambda x: x[1][0])
print(new_data)
	
前两个做到了，但是第三个有错误！

 >>>C:\Documents and Settings\Administrator\桌面\py>2.py
name: Adam - age: 38 - score: 77name: John - age: 23 - score: 96name: Bill - age
: 46 - score: 98name: Sam - age: 66 - score: 50name: Alison - age: 77 - score: 8
6name: Isabella - age: 19 - score: 99name: Kerl - age: 22 - score: 44
-------------------------
{'Adam': [38, 77], 'Isabella': [19, 99], 'Kerl': [22, 44], 'Alison': [77, 86], '
Sam': [66, 50], 'Bill': [46, 98], 'John': [23, 96]}
----------------------------
Traceback (most recent call last):
  File "C:\Documents and Settings\Administrator\桌面\py\2.py", line 13, in <modu
le>
    newdata = sorted(data.iteritems() , key = lambda x: x[1][0])
AttributeError: 'dict' object has no attribute 'iteritems'

>>>C:\Documents and Settings\Administrator\桌面\py>

**Comment by K-Guan** [comment]
虽然你的格式有点……好吧，我还是看懂了。

别说你是照套，就是直接抄袭也就那么着了（虽然这个答案也没地抄去……）。反正只要你能做出来就行，至于你是否理解你的答案就是另一回事了。现在，我来评价下你的答案：

1. 基本正确，用 `dict` 存放数据是对的，你的正则也用的不错。不过实际在这里是不需要用正则的。**仔细研究研究 `str.split()` 的用法，然后写一个不用正则的版本出来。**

2. `dict.iteritems()` 是 Python2 的函数，Python3 直接用 `dict.items()` 就好。

3. 你的 `data` 似乎有些不妥呀。**因为他人看到你的 `data` 并不会明白其中的两个数据代表什么**。看看我的：

  ```python
  [{'age': '38', 'name': 'Adam', 'score': '77'},
   {'age': '23', 'name': 'John', 'score': '96'},
   {'age': '46', 'name': 'Bill', 'score': '98'},
   {'age': '66', 'name': 'Sam', 'score': '50'},
   {'age': '77', 'name': 'Alison', 'score': '86'},
   {'age': '19', 'name': 'Isabella', 'score': '99'},
   {'age': '22', 'name': 'Kerl', 'score': '44'}]
  ```

  当然了，`{'Kerl': {'age': '22', 'score': '44'}}` 也是不错的。研究下吧。

**Comment by redapple0204** [comment]
@K-Guan 1.用正则是因为那个教程里正好有，而且可以套用，不过，我可以试试看看能不能不用正则
2.原来我看的是python2的教程啊！
3.这个格式为什么不管我怎么输出都是很乱呢
4.好吧，我竟然忘记了
5.
这是我修改后的程序
from re import findall
f = open('1.txt').read( )



print(f)
print(u"-------------------------")
data = dict()
for i,j,k in findall('name: (\w+) - age: (\d+) - score: (\d+)',f):
	data[i]=[int(j),int(k)]
print(data)
print(u"----------------------------")
newdata = sorted(data.items() , key = lambda x: x[1][0])
print(newdata)
(f.close())


可是请问为什么第三个输出的很奇怪呢？


C:\Documents and Settings\Administrator\桌面\py>2.py
name: Adam - age: 38 - score: 77
name: John - age: 23 - score: 96
name: Bill - age: 46 - score: 98
name: Sam - age: 66 - score: 50
name: Alison - age: 77 - score: 86
name: Isabella - age: 19 - score: 99
name: Kerl - age: 22 - score: 44
-------------------------
{'Adam': [38, 77], 'Sam': [66, 50], 'Alison': [77, 86], 'Kerl': [22, 44], 'John'
: [23, 96], 'Bill': [46, 98], 'Isabella': [19, 99]}
----------------------------
[('Isabella', [19, 99]), ('Kerl', [22, 44]), ('John', [23, 96]), ('Adam', [38, 7
7]), ('Bill', [46, 98]), ('Sam', [66, 50]), ('Alison', [77, 86])]

**Comment by K-Guan** [comment]
奇怪就对了，`sorted()` 返回一个 `list`。而你需要想办法手动将数据组合。算了，也不难为你了。这个是我的程序，你参考下并写出：**我的程序是怎样工作的？** （虽然我的注释已经比较全面了）：

```python
#!/usr/bin/env python3

# open the file as `f`.
with open('data') as f:
    # read the file into a list
    data_list = f.read().splitlines()

    # use `str.split()` to split the data to get the result as a list of dicts.
    # you can try `print(result)` or replace the `dict()` function below
    # to `print()` function to see what happened here.
    result = [dict(element.split(': ') for element in person.split(' - '))
              for person in data_list]

    pprint(result)

    # replace `int(x['age'])` with `x['name']`, `int(x['score'])` to sort by
    # name or score rather than age.
    for person in sorted(result, key=lambda x: int(x['age']), reverse=True):
        """
        # skip if their age is larger than 60 or score is less than 60.
        if int(person['age']) > 60 or int(person['score']) < 60:
            continue
        """

        # print out the result
        print('{}: {} (age {})'.format(person['name'],
                                       person['score'],
                                       person['age']))
```

**Comment by redapple0204** [comment]
@K-Guan  1.好的，请等我使用电脑了就好了，因为手机好像不太方便 
2.我同学竟然直接发东西给您?@β！-！-？：：，实在是太不还意思打扰到你了

**Comment by K-Guan** [comment]
第二条什么意思？哪里？

**Comment by redapple0204** [comment]
@K-Guan 就是昨天晚上新开的issue啊

**Comment by K-Guan** [comment]
1. `with` 是所有资深 Python 程序员都会推荐的。原因是安全、方便、而且 `open + close` 需要两行，`with` 只需要一行。并且 `with` 的缩进让在哪儿打开的文件更加清晰。

2. `取代int(x['age'])` with `x['name']`, `int(x['score']) [...]` 那段的意思是，把下面 `key=lambda x: int(x['age'])` 那段中的 `int(x['age'])` 改为 `x['name']` （用名字排序）、或 `int(x['score'])` 用成绩排序。

**Comment by redapple0204** [comment]
@K-Guan 1.那么好的一个办法教程里竟然没有写，好可惜啊
2.原来如此啊，涨知识了

**Comment by K-Guan** [comment]
嗯：https://stackoverflow.com/questions/3012488/what-is-the-python-with-statement-designed-for

**Comment by redapple0204** [comment]
@K-Guan with算是一个比较重要的函数了？（比较常用的）

**Comment by K-Guan** [comment]
> `with` is a **statement**, not a **function**.

我是建议在读写文件时用 `with open('file') as f:` 代替 `f = open('file'); f.close()`。不过通常你也可以在很多需要用到 `.close()` 的地方用 `with...as` 来代替（比如数据库的读写等）。

**Comment by redapple0204** [comment]
@K-Guan 孙便，我想问问，如果不close文件会发生什么严重的后果？

**Comment by K-Guan** [comment]
一般来说……不会有事。反正具体我也解释不清楚。我唯一遇到的一次问题是在编写我的 [TEdit](https://github.com/k-guan/tedit) 时，因为我居然不知道 `mktemp` 原来还会自动打开一次文件……

总之，如果你的代码是这样的话：

```python
import os
open('file.txt', 'w')
os.system('notepad file.txt') 
```

在 Windows 下，这将会直接报错（你可以试试看）。不过在 Linux 下，好像不存在占用一类的问题：

```python
import os
open('file', 'w')
os.system('vim file') 
```

这样可以直接运行。

**Comment by K-Guan** [comment]
具体的我在 SO 有个问题，等等……

**Comment by redapple0204** [comment]
@K-Guan 真的好神奇啊，难道是windows的notepad有什么限制？
在什么情况下只open而不关闭呢

**Comment by K-Guan** [comment]
没有，打开后操作完了就得关闭。至于 Windows 到不是 Notepad 的问题，是系统机制的问题。等下我把我的问题找出来……

**Comment by redapple0204** [comment]
@K-Guan 好的
