### ISSUE TITLE
尝试安装gentoo中.....

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#180]
编译内核慢的要死.....
@lizongzeshunshun 

![14](https://cloud.githubusercontent.com/assets/16254644/23304225/906646ac-fad3-11e6-9ef0-e88bed3cb76f.PNG)

**Comment by redapple0204** [comment]
挂他个一晚上看会怎样

**Comment by lizongzeshunshun** [comment]
等到时候我换了AMD的R7 1700试试

**Comment by redapple0204** [comment]
按我这个二代i3不知道一晚上行不行

**Comment by lizongzeshunshun** [comment]
内核很快呀，我上次尝试大概是20min，要命的gcc之类的工具

**Comment by lizongzeshunshun** [comment]
然后AMD终于要翻身了。。

**Comment by redapple0204** [comment]
你那使用手动编译自定义内核吧
我这是全选所有内核模块

**Comment by lizongzeshunshun** [comment]
是啊，手动选择

**Comment by redapple0204** [comment]
手动选感觉麻烦了，所以我直接自动全选
现在硬盘灯狂闪，然而没有进度

**Comment by redapple0204** [comment]
而且万一有需要没选到不就尴尬了

**Comment by lizongzeshunshun** [comment]
那就重新编译。。

**Comment by lizongzeshunshun** [comment]
但是我感觉gentoo太烧cpu了。。

**Comment by redapple0204** [comment]
反正我虚拟机先试试，不行就算了

**Comment by lizongzeshunshun** [comment]
。。

**Comment by lizongzeshunshun** [comment]
按照我妈的说法大概下个月买。。。

**Comment by redapple0204** [comment]
那么好。。多少钱？
还有为啥不买i5，i7什么的

**Comment by lizongzeshunshun** [comment]
AMD的R7 1700多线程超越i7 7700k 46%，而且价格还更便宜
显卡随便上，反正不玩游戏，估计4000-5000吧

**Comment by redapple0204** [comment]
a卡驱动不麻烦么

**Comment by lizongzeshunshun** [comment]
等28号评测解禁再看看。。

**Comment by lizongzeshunshun** [comment]
直接上Win10.。

**Comment by redapple0204** [comment]
你硬盘跟得上么。。

**Comment by redapple0204** [comment]
反正linux驱动肯定很难找

**Comment by lizongzeshunshun** [comment]
SSD啊。。

**Comment by redapple0204** [comment]
多少G

**Comment by lizongzeshunshun** [comment]
128

**Comment by redapple0204** [comment]
真的够用么

**Comment by lizongzeshunshun** [comment]
然后把原来这块机械拆过去。。

**Comment by redapple0204** [comment]
估计只是用来防系统吧

**Comment by redapple0204** [comment]
放

**Comment by lizongzeshunshun** [comment]
是啊，也只能放系统。。

**Comment by redapple0204** [comment]
另：为啥gentoo要编译gcc？我看wiki没写啊

**Comment by redapple0204** [comment]
好吧...其实64就够了

**Comment by lizongzeshunshun** [comment]
1. 升级的时候
2. 反正是要显卡最小化，估计只能上GTX1050或者470D了。。

**Comment by lizongzeshunshun** [comment]
而且我的压岁钱要全部贡献给这个了。。

**Comment by redapple0204** [comment]
1.那我干脆不升级了...据说gentoo几年不滚都没事
2.显卡我没要求，反正不玩游戏
3.好吧...估计要几千

**Comment by lizongzeshunshun** [comment]
1. 对啊。。Gentoo软件包的更新也不算快（跟arch比）
2. 有时候我妈要用ps应该还是有点要求的，毕竟Ryzen处理器没有核显。。

**Comment by redapple0204** [comment]
1.然而内核还4.9.x
2.好吧，为啥不考虑intel？

**Comment by lizongzeshunshun** [comment]
1. 内核跟进确实还行，但是其他软件还是差点
2. 性价比太低，同价格AMD强46%

**Comment by redapple0204** [comment]
1.对....似乎py才3.4
2.性能呢？

**Comment by lizongzeshunshun** [comment]
1. 对
2. 在和I7 7700K对飙的R7 1700中（价格基本相同），I7-7700K单核比1700稍微强一点，但是多核i7直接被秒杀

**Comment by redapple0204** [comment]
好吧....硬件方面我实在不懂

**Comment by lizongzeshunshun** [comment]
反正只要能流畅运行w10+vs2017这我就知足了。。

**Comment by redapple0204** [comment]
为啥偏要win10.。

**Comment by redapple0204** [comment]
感觉黑黑的边框很恶心

**Comment by lizongzeshunshun** [comment]
审美不同。。反正我比较喜欢w10的风格

**Comment by redapple0204** [comment]
黑色主题其实我以前也比较喜欢...但由于我电脑运行win10很卡导致对win10影响不好，从而对黑色主题的厌恶

**Comment by lizongzeshunshun** [comment]
关掉UAC，UAC巨拖速度

**Comment by redapple0204** [comment]
主要是硬盘100%......

**Comment by lizongzeshunshun** [comment]
..
