### ISSUE TITLE
Project SI.

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#182]
截止项目Stars超过20前，请勿关闭本Issue。
# Project SI.

## 含义
**Project Super-Improvement**

## 目的
Stars超过20

## 需要做的工作
1. 整理项目，使整洁。
2. 添加更多有用的东西【重要】
3. 宣传

本Issues仅讨论Project SI.相关问题。

**Comment by redapple0204** [comment]
说下我的看法：
在GITHUB上火起来不非就是这几种项目
1.翻墙方法/软件/账号
2.正规的编程
3.破解软件（实际最多也就100stars）
4.一些好玩的东西

我觉得我们第一条可能勉强有办法做到，第二条没这个水平，破解软件也就这两个，好玩的东西好像也没思路........
so，很难进展啊

**Comment by lizongzeshunshun** [comment]
主要走第一条路吧。3还是少搞为好。4也可以发展一下，2能力还有点不足。

**Comment by redapple0204** [comment]
好，只要翻墙软件不要超过500stars就没人搞你

**Comment by redapple0204** [comment]
现在17了.....
