### ISSUE TITLE
请求帮忙弄下linux的ss..

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#183]
换回了linux..然而还是搞不定
@lizongzeshunshun 
tv号：144 109 485
密码和上个一样

**Comment by redapple0204** [comment]
话说能不能用chrome里的procx插件代理？

**Comment by redapple0204** [comment]
@lizongzeshunshun Some errors.
>Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
redapple@redapple-pc ~> sudo bash sschrome.sh 
[sudo] redapple 的密码：
redapple@redapple-pc ~> sudo bash startss.sh  
[sudo] redapple 的密码：
loaded collections.OrderedDict
IPv6 support
2017-02-26 09:31:13 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.2
2017-02-26 09:31:13 ERROR    daemon.py:75 already started at pid 26460
redapple@redapple-pc ~> sudo bash sschrome.sh 
sschrome.sh: 行 1:  8722 非法指令            google-chrome --proxy-server="socks://127.0.0.1:1080"
redapple@redapple-pc ~>

**Comment by redapple0204** [comment]
神器，现在好了

**Comment by redapple0204** [comment]
但是局域网共享还是不行

**Comment by lizongzeshunshun** [comment]
确定？

**Comment by lizongzeshunshun** [comment]
无法TV

**Comment by redapple0204** [comment]
我先重启下==

**Comment by redapple0204** [comment]
用cmd开启的方法：http://jingyan.baidu.com/article/4f34706edcc317e387b56df3.html
