### ISSUE TITLE
调一个信道差别那么大

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#189]
由于linux共享wifi的需求，我就必须要把信道调成11或以下
然后调了11，发现测的速度只有400k/s
原来13信道有1.5甚至2M/s的....
（一个信道为啥差别那么大啊。。。）
@lizongzeshunshun

**Comment by redapple0204** [comment]
现在才2.2mbps...
上个网还老断线，下载个文件慢的要死

**Comment by redapple0204** [comment]
另：ss有时候没法用，运行了sudo bash startss.sh以后在运行chrome什么的sh还是中国的ip

**Comment by lizongzeshunshun** [comment]
1. 对啊，信道还是让他自己选好
2. OK，晚上。

**Comment by redapple0204** [comment]
1.很可惜13不行。。。
2.OK，话说这玩意可能有bug，有时候无法使用，要等到注销了才能用

**Comment by redapple0204** [comment]
找到bug了。
你的sschrome有bug，有时候无法走代理
在系统设置里设置代理就好了

**Comment by lizongzeshunshun** [comment]
k

**Comment by redapple0204** [comment]
其实我觉得直接在系统里面社区设置全局代理会好些==

**Comment by lizongzeshunshun** [comment]
但是看国内视频或者下载全部都走ss流量太大

**Comment by redapple0204** [comment]
不是嘛，反正要用就开全局代理，不用就关了。
要不然用个sh脚本来开还是bug好多（经常无法走代理）
或者说我在一个特殊的页面不方便在开代理==

**Comment by redapple0204** [comment]
而且全局代理好像能用到别的程序==

**Comment by lizongzeshunshun** [comment]
浏览器用插件最方便啊。。

![default](https://cloud.githubusercontent.com/assets/10304206/23363571/482a876c-fd36-11e6-9d9f-b8fb90b5607a.png)

**Comment by redapple0204** [comment]
都有4个插件了。。再多就打开都卡的要死
还好dde有自带socks代理==

**Comment by lizongzeshunshun** [comment]
1. i3有那么烂吗。。
如果要全局我有这个：
![default](https://cloud.githubusercontent.com/assets/10304206/23363601/6d3c874e-fd36-11e6-8a3d-d66ba0291e9c.png)

**Comment by redapple0204** [comment]
1.不是卡的问题，是chrome的问题。。（maybe）
2.好吧...多装一个软件感觉很臃肿

**Comment by redapple0204** [comment]
另外windows的ssr右键就有全局代理啊

**Comment by lizongzeshunshun** [comment]
1. FF大法好。。
2. 那个不全的，只是修改IE代理，对于某些程序没用

**Comment by lizongzeshunshun** [comment]
2补充. 事实上大部分程序都不行

**Comment by redapple0204** [comment]
1.ff没法像chrome一样装个插件可以开手机app（笑）
2.那我这样应该对所有程序有效吧
![qq 20170227215032](https://cloud.githubusercontent.com/assets/16254644/23363707/f44cb416-fd36-11e6-93b1-4938cc534c94.png)

**Comment by lizongzeshunshun** [comment]
不了解Linux。。

**Comment by redapple0204** [comment]
八成....难说，我先试试

**Comment by redapple0204** [comment]
终端不行

**Comment by lizongzeshunshun** [comment]
对啊。。

**Comment by redapple0204** [comment]
终端号想要另外搞
这玩意走的代理是tcp？

**Comment by lizongzeshunshun** [comment]
？？？

**Comment by redapple0204** [comment]
走的是什么代理

**Comment by lizongzeshunshun** [comment]
SOCKS5基于TCP啊。。

**Comment by redapple0204** [comment]
好吧，好像很多应用都不走tcp吧。。

**Comment by redapple0204** [comment]
例如qq

**Comment by lizongzeshunshun** [comment]
不是 SOCKS5基于TCP，但是可以转发UDP啊（UDP封装成TCP Package）而ssr做到了这一点

**Comment by redapple0204** [comment]
但是还是很多应用没法代理，不知道走的是什么流量

**Comment by lizongzeshunshun** [comment]
那是因为那些应用不知道要走代理而不是走不了
如果真的要全局代理（真的全局！）请用redsocks

**Comment by redapple0204** [comment]
终端也学

**Comment by lizongzeshunshun** [comment]
这玩意相当于Win挂VPN

**Comment by redapple0204** [comment]
linux挂vpn也真全局啊。。

**Comment by redapple0204** [comment]
vpn又走的啥。。

**Comment by lizongzeshunshun** [comment]
但是vpn已经over了啊。。

这个就相当于截获网卡所有流量然后全部重定向到代理

**Comment by lizongzeshunshun** [comment]
ss-redir也有同样效果

**Comment by redapple0204** [comment]
vpn又怎么做到的封锁。。很强势嘛
按理说openvpn或者上次不小心我把vpn拉到黑名单的udp打洞不也可以链？

**Comment by lizongzeshunshun** [comment]
VPN特征明显很好搞啊。。
OPENVPN是所有VPN里面特征最明显的。。

**Comment by lizongzeshunshun** [comment]
手滑

**Comment by redapple0204** [comment]
不是pptp么？
udp打洞呢

**Comment by lizongzeshunshun** [comment]
pptp特征没ovpn明显，因为ovpn是开源的
udp流量一大秒封（很多地区都这样）

**Comment by redapple0204** [comment]
噗开源容易被封
所以ssr当时不开源算得上有理由

**Comment by redapple0204** [comment]
另外还有一些vpn协议不容易被封，然而速度比ss满多了

**Comment by lizongzeshunshun** [comment]
而且udp是二等公民，向天威这种isp丢包率高于50%但是TCP丢包率高于0.5%基本就算不上一个isp了

**Comment by lizongzeshunshun** [comment]
那是因为它线路好。。

**Comment by lizongzeshunshun** [comment]
搞个台湾香港的ss照样满速

**Comment by redapple0204** [comment]
垃圾天威
反正越靠近中国速读越快嘛

**Comment by redapple0204** [comment]
用vpn香港的都差不多能满速

**Comment by lizongzeshunshun** [comment]
但是香港vps巨贵，512m+10m宽带都100+/mon

**Comment by redapple0204** [comment]
话说vpn真可以突破物理网。。
学校上传1m/s用lantern就30m/s了。。。

**Comment by redapple0204** [comment]
对啊。。

**Comment by redapple0204** [comment]
台湾还好吧

**Comment by redapple0204** [comment]
我觉得日本要好，还有那个docker

**Comment by lizongzeshunshun** [comment]
肯定是学校跟vpn厂商有py交易，否则不可能

**Comment by redapple0204** [comment]
估计是。。有限速

**Comment by lizongzeshunshun** [comment]
日本跟香港比还是too young。。我这里ping香港2ms

**Comment by lizongzeshunshun** [comment]
i'm going to go to bed.

**Comment by redapple0204** [comment]
才2ms不现实。。百度都不止

**Comment by redapple0204** [comment]
ok，8
