### ISSUE TITLE
竟然大事碰一起了。。

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#196]
@redapple0204 

我们要换座位了，本来我们这一行4个人玩得很好了，结果一拆，要“分道扬镳”了。。。。。
哎。。

**Comment by redapple0204** [comment]
我觉得这周真是倒霉，碰上了一大堆考试还有一人转学...
一行？不是一个组么.....
这就是命.........

**Comment by lizongzeshunshun** [comment]
不是，我们一行本来就玩得特别好。。组是另一回事。。

**Comment by redapple0204** [comment]
很少见到有“行”这一说法的
另外你们不是每周都要换座位吗

**Comment by lizongzeshunshun** [comment]
不是啊。。半学期一次

**Comment by redapple0204** [comment]
我说的是前后轮换，难道我记错了？

**Comment by lizongzeshunshun** [comment]
前后轮换到没事，一行都是在一起的

**Comment by redapple0204** [comment]
好吧。。为啥要拆？

**Comment by lizongzeshunshun** [comment]
每次考试以后打乱座位。。惯例啊。。

**Comment by redapple0204** [comment]
没有考试啊....

**Comment by lizongzeshunshun** [comment]
大考，这次是开学考

**Comment by redapple0204** [comment]
哦对你们还有开学考....
话说反正打散了你们还是在一个班...如果出国的话就基本上再也见不到了

**Comment by lizongzeshunshun** [comment]
反正感觉不爽。。

**Comment by redapple0204** [comment]
不过也是...毕竟如果关系只是一般的层次的话分开了应该不会再找了....
怎么有股奇怪的感觉，即使出国的那位同学跟我不算是很熟但也突然感到悲伤

**Comment by lizongzeshunshun** [comment]
我们这行真是完美的结合，关系当然都是非常好了，但是距离拉远了就。。。

**Comment by redapple0204** [comment]
拉的多远？

**Comment by lizongzeshunshun** [comment]
隔了1组吧。。

**Comment by redapple0204** [comment]
也就第一组和第三住的差距？

**Comment by lizongzeshunshun** [comment]
对。。

**Comment by redapple0204** [comment]
那么远...那就很难搞了

**Comment by lizongzeshunshun** [comment]
最近心情很差。。。好多烦心事碰在一起

**Comment by redapple0204** [comment]
@lizongzeshunshun 我不一样...这一周好多烦心事
一大堆考试还有班长（同桌）心情不好+有一人转学
