### ISSUE TITLE
你觉得亚马逊的免费一年vps如何？

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#198]
准备搞一个玩玩
@lizongzeshunshun

**Comment by lizongzeshunshun** [comment]
那个我试过的，要信用卡

**Comment by redapple0204** [comment]
@lizongzeshunshun 信用卡的话随机生成个不就好了

**Comment by lizongzeshunshun** [comment]
要扣掉1美元。。而且需要信用卡上的CSV验证代码

**Comment by redapple0204** [comment]
@lizongzeshunshun 我咋记得昨天只要求输入信用卡然后就过去了。x

**Comment by lizongzeshunshun** [comment]
@redapple0204 我妈以前申请过一年的，确实要扣1do，然后后面不小心流量超额然后直接扣掉10+dollors

**Comment by redapple0204** [comment]
@lizongzeshunshun 你指的是申请还是注册环节？

**Comment by lizongzeshunshun** [comment]
@redapple0204 注册后面就有

另外，终于要换电脑了，受够了速龙II。。。。

**Comment by redapple0204** [comment]
好吧...最终注册不通过
电脑到了么？
