### ISSUE TITLE
It seem ss is boom....

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#199]
@lizongzeshunshun

**Comment by lizongzeshunshun** [comment]
yep，到期了

**Comment by redapple0204** [comment]
你的域名解析竟然还在工作！
>
C:\Users\redapple>ping c4oso.me

>正在 Ping c4oso.me [23.236.74.55] 具有 32 字节的数据:
请求超时。

>23.236.74.55 的 Ping 统计信息:
    数据包: 已发送 = 1，已接收 = 0，丢失 = 1 (100% 丢失)，
>Control-C
^C
>C:\Users\redapple>

那我先用着免费的共享账号好了....
