### ISSUE TITLE
vmware上下载tools的问题

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#20]
在下载tools的时候，出现了这个问题
>There was a problem updating a software component. Try again later and if the problem persists, contact VMware Support or your system administrator

本来想照着这个安装tools的
https://wiki.archlinux.org/index.php/VMware_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)#Preventing_crashes_and_freezes_when_checking_for_updates
但是它提供的网址是主程序而不是tools
（去谷歌上依旧。。。nothing）

@K-Guan

**Comment by redapple0204** [comment]
ps：搜索到的什么用su之类的全都无效！

**Comment by K-Guan** [comment]
照你这么说，你是在虚拟机内，也就是 Arch 里安装 Tools 了？如果是这样的话：

> 本文是关于在 Arch 中安装 VMware，你也许想寻找的是 [**在 VMware 中安装 Arch Linux**](https://wiki.archlinux.org/index.php/Installing_Arch_Linux_in_VMware_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87))

<sub>你提供的网址第一行</sub>

点过去后，嗯，你自己研究研究吧：https://wiki.archlinux.org/index.php/VMware/Installing_Arch_as_a_guest_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)#VMware_Tools_versus_Open-VM-Tools

**Comment by redapple0204** [comment]
@K-Guan 不不不，在arch上安装了vmware，但是vmware要下载tools，下载出错了。

**Comment by K-Guan** [comment]
需要吗？难道不是直接在虚拟机内装好 tools 就行了？那我看看……

**Comment by redapple0204** [comment]
@K-Guan 算了不管了。。。。

**Comment by redapple0204** [comment]
@K-Guan 话说。。请问下，“parrot security os”这玩意怎么汉化，谷歌上压根就没有方法/。
