### ISSUE TITLE
似乎现在的墙非常高了

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#202]
@lizongzeshunshun 我用hosts只能看google，别的网站全挂，只有ss才行了....

**Comment by lizongzeshunshun** [comment]
@redapple0204 我有新的ss了，请在你的私有项目联系我

**Comment by redapple0204** [comment]
你tv下吧。。
358 335 578
key还是原来的

**Comment by redapple0204** [comment]
@lizongzeshunshun 抱歉刚刚出去了下没看到...
IDM还挺快的，单线程的话好像要一段时间才能提速

**Comment by lizongzeshunshun** [comment]
对

**Comment by redapple0204** [comment]
我觉得用pget应该能更快。。
