### ISSUE TITLE
论mbit/s与mb/s的区别？

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#207]
@lizongzeshunshun

**Comment by lizongzeshunshun** [comment]
1Byte=8bit

∴1MB/s=8Mb/s

**Comment by lizongzeshunshun** [comment]
MB中B是Byte
Mb中B是Bit

**Comment by redapple0204** [comment]
@lizongzeshunshun thx！
此外，我就发现了，现在百度云破解全失效了....

**Comment by redapple0204** [comment]
@lizongzeshunshun 等等，我找到一个方案可以破解了。
用aget的99*亿*线程配合2M分段即可下载全速
但是很考验配置。。
