### ISSUE TITLE
经过dd以后的磁盘还有可能恢复数据吗？

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#21]
表示今天突然想备份一下系统，查了下dd的用法（dd if=/dev/sda of=/dev/sdc），然后想也没想就用我的移动硬盘了;执行玩15秒钟左右突然发现先不对：dd好像是直接删掉整个分区来备份的，于是连忙停止，但是为时已晚，已经复制了700m左右的文件，请问这块硬盘回复数据的可能性还有多大呢
@K-Guan

**Comment by redapple0204** [comment]
哦对了，话说这个真的可以安装吗？
![2016-06-27 12 29 17](https://cloud.githubusercontent.com/assets/16254644/16368636/0849965e-3c63-11e6-8461-fa762d676ec6.png)

**Comment by redapple0204** [comment]
@K-Guan 环境变量好像有问题！
redapple@kali:~/Desktop$ pip3
bash: /usr/bin/pip3: 没有那个文件或目录
redapple@kali:~/Desktop$ which pip3
/usr/local/bin/pip3

**Comment by redapple0204** [comment]
@K-Guan 新问题：卸载掉“kali-linux-full"这个包会怎样呢？好像也不是gnome

**Comment by redapple0204** [comment]
顺便问一下有没有好一点的备份方式：dd。。太危险！
tar压缩方式：不完全而且恢复有困难还容易失败
ghost：占空间太大

**Comment by K-Guan** [comment]
于是你到底想问什么？还有这都20天后了，问题解决没？

**Comment by redapple0204** [comment]
@K-Guan 解决是解决了，不过。。
arch上的yaourt是什么鬼东西
根本就没有dpkg，google-chrome，wineqq这些包，而且还要报“curl error: Problem with the SSL CA cert (path? access rights?)
”错误
基本和没安装一样。。。
ps：网上说要改源，但是无效

**Comment by redapple0204** [comment]
@K-Guan 现在就只有dpkg不能撞了。但是manjaro明明有dpkg啊，我也改了manjaro的yaourt源，但是没用

**Comment by redapple0204** [comment]
@K-Guan 反正我yaourt -Ss了下，发现没有aur的包，只有pacman的，而且还报错
curl error: Problem with the SSL CA cert (path? access rights?)

**Comment by redapple0204** [comment]
@K-Guan git手动安装也出问题
fatal: unable to access 'https://aur.archlinux.org/package-query.git/': error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none

ps：arch好多问题！翻墙也不行了！

**Comment by redapple0204** [comment]
@K-Guan 我的意思其实是：用yaourt安装的时候没法用aur源

**Comment by redapple0204** [comment]
@K-Guan 就想这样，没有aur的包
[root@AAAAAAAAAmyarch redapple]# yaourt vmware
1 extra/xf86-input-vmmouse 13.1.0-2 (xorg-drivers xorg)
    X.org VMWare Mouse input driver
2 extra/xf86-video-vmware 13.1.0-3 (xorg-drivers xorg)
    X.org vmware video driver
3 community/libview 0.6.6-4
    A collection of widgets that were developed at VMware
4 community/open-vm-tools 6:10.0.7-5
    The Open Virtual Machine Tools (open-vm-tools) are the open source 
    implementation of VMware Tools
5 archlinuxcn/vmware-horizon-client 4.1.0-1
    VMware Horizon Client connect to VMware Horizon virtual desktop
6 archlinuxcn/vmware-horizon-pcoip 4.1.0-1
    VMware Horizon Client connect to VMware Horizon virtual desktop - PCoIP 
    and BLAST remote desktop connections
7 archlinuxcn/vmware-horizon-rtav 4.1.0-1
    VMware Horizon Client connect to VMware Horizon virtual desktop - 
    Real-Time Audio-Video (webcam and audio-in)
8 archlinuxcn/vmware-horizon-smartcard 4.1.0-1
    VMware Horizon Client connect to VMware Horizon virtual desktop - 
    smartcard authentication
9 archlinuxcn/vmware-horizon-usb 4.1.0-1
    VMware Horizon Client connect to VMware Horizon virtual desktop - USB 
    device redirection
10 archlinuxcn/vmware-horizon-virtual-printing 4.1.0-1
    VMware Horizon Client connect to VMware Horizon virtual desktop - virtual 
    printing
curl error: Problem with the SSL CA cert (path? access rights?)
==> 输入 n° 以安装需要的软件包（例如：1 2 3 或者是 1-3）
==> ---------------------------------
==>

**Comment by redapple0204** [comment]
@K-Guan 手动安装还缺依赖包，而且pacman也没有！@#￥%%……&……& aur里也是没有

**Comment by redapple0204** [comment]
curl error: Problem with the SSL CA cert (path? access rights?)
@K-Guan 我认为问题主要处在这里
但是搜索了什么办法都没有

**Comment by redapple0204** [comment]
@K-Guan 还有就是内核太新了，有没有办法降到3.x

**Comment by redapple0204** [comment]
现在手动装也有问题了，就是curl的祸
curl: (77) error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none

搜出来一大堆关于PHP的

**Comment by redapple0204** [comment]
@K-Guan 找了整整一天，终于找到办法了！，办法很简单，就是
> sudo /usr/bin/update-ca-trust

**Comment by redapple0204** [comment]
对了，话说这种字体能不能改下，好难看
![2016-07-19 07-54-47](https://cloud.githubusercontent.com/assets/16254644/16934140/2930f7c0-4d86-11e6-8d2e-164599977988.png)
当然安装字体速效，chrome里改也没效，gnome-tool里改也是一样。
ps：我开启testing源滚了下就这样了

**Comment by redapple0204** [comment]
@K-Guan 还有就是这个问题，我在makepkg的时候与到了这个错误，那么长我该去哪里问呢，怎么问呢？
>Determining if the pthread_create exist failed with the following output:
Change Dir: /tmp/yaourt-tmp-redapple/aur-conky-lua/src/conky-1.10.1/CMakeFiles/CMakeTmp

>Run Build Command:"/usr/bin/make" "cmTC_08e83/fast"
/usr/bin/make -f CMakeFiles/cmTC_08e83.dir/build.make CMakeFiles/cmTC_08e83.dir/build
make[1]: 进入目录“/tmp/yaourt-tmp-redapple/aur-conky-lua/src/conky-1.10.1/CMakeFiles/CMakeTmp”
Building C object CMakeFiles/cmTC_08e83.dir/CheckSymbolExists.c.o
/usr/bin/cc    -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong     -o CMakeFiles/cmTC_08e83.dir/CheckSymbolExists.c.o   -c /tmp/yaourt-tmp-redapple/aur-conky-lua/src/conky-1.10.1/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_08e83
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_08e83.dir/link.txt --verbose=1
/usr/bin/cc  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong     -Wl,-O1,--sort-common,--as-needed,-z,relro  CMakeFiles/cmTC_08e83.dir/CheckSymbolExists.c.o  -o cmTC_08e83 -rdynamic 
CMakeFiles/cmTC_08e83.dir/CheckSymbolExists.c.o：在函数‘main’中：
CheckSymbolExists.c:(.text.startup+0x6)：对‘pthread_create’未定义的引用
collect2: 错误：ld 返回 1
make[1]: *** [CMakeFiles/cmTC_08e83.dir/build.make:98：cmTC_08e83] 错误 1
make[1]: 离开目录“/tmp/yaourt-tmp-redapple/aur-conky-lua/src/conky-1.10.1/CMakeFiles/CMakeTmp”
make: *** [Makefile:126：cmTC_08e83/fast] 错误 2

>File /tmp/yaourt-tmp-redapple/aur-conky-lua/src/conky-1.10.1/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

>int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

>Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /tmp/yaourt-tmp-redapple/aur-conky-lua/src/conky-1.10.1/CMakeFiles/CMakeTmp

>Run Build Command:"/usr/bin/make" "cmTC_fd2c9/fast"
/usr/bin/make -f CMakeFiles/cmTC_fd2c9.dir/build.make CMakeFiles/cmTC_fd2c9.dir/build
make[1]: 进入目录“/tmp/yaourt-tmp-redapple/aur-conky-lua/src/conky-1.10.1/CMakeFiles/CMakeTmp”
Building C object CMakeFiles/cmTC_fd2c9.dir/CheckFunctionExists.c.o
/usr/bin/cc    -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong  -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_fd2c9.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.5/Modules/CheckFunctionExists.c
Linking C executable cmTC_fd2c9
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_fd2c9.dir/link.txt --verbose=1
/usr/bin/cc  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong  -DCHECK_FUNCTION_EXISTS=pthread_create   -Wl,-O1,--sort-common,--as-needed,-z,relro  CMakeFiles/cmTC_fd2c9.dir/CheckFunctionExists.c.o  -o cmTC_fd2c9 -rdynamic -lpthreads 
/usr/bin/ld: 找不到 -lpthreads
collect2: 错误：ld 返回 1
make[1]: *** [CMakeFiles/cmTC_fd2c9.dir/build.make:98：cmTC_fd2c9] 错误 1
make[1]: 离开目录“/tmp/yaourt-tmp-redapple/aur-conky-lua/src/conky-1.10.1/CMakeFiles/CMakeTmp”
make: *** [Makefile:126：cmTC_fd2c9/fast] 错误 2


>Determining if the pipe2 exist failed with the following output:
Change Dir: /tmp/yaourt-tmp-redapple/aur-conky-lua/src/conky-1.10.1/CMakeFiles/CMakeTmp

>Run Build Command:"/usr/bin/make" "cmTC_38a58/fast"
/usr/bin/make -f CMakeFiles/cmTC_38a58.dir/build.make CMakeFiles/cmTC_38a58.dir/build
make[1]: 进入目录“/tmp/yaourt-tmp-redapple/aur-conky-lua/src/conky-1.10.1/CMakeFiles/CMakeTmp”
Building C object CMakeFiles/cmTC_38a58.dir/CheckSymbolExists.c.o
/usr/bin/cc  -D_LARGEFILE64_SOURCE -D_POSIX_C_SOURCE=200809L  -std=c99 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong     -o CMakeFiles/cmTC_38a58.dir/CheckSymbolExists.c.o   -c /tmp/yaourt-tmp-redapple/aur-conky-lua/src/conky-1.10.1/CMakeFiles/CMakeTmp/CheckSymbolExists.c
/tmp/yaourt-tmp-redapple/aur-conky-lua/src/conky-1.10.1/CMakeFiles/CMakeTmp/CheckSymbolExists.c: 在函数‘main’中:
/tmp/yaourt-tmp-redapple/aur-conky-lua/src/conky-1.10.1/CMakeFiles/CMakeTmp/CheckSymbolExists.c:8:19: 错误：‘pipe2’未声明(在此函数内第一次使用)
   return ((int*)(&pipe2))[argc];
                   ^~~~~
>/tmp/yaourt-tmp-redapple/aur-conky-lua/src/conky-1.10.1/CMakeFiles/CMakeTmp/CheckSymbolExists.c:8:19: 附注：每个未声明的标识符在其出现的函数内只报告一次
make[1]: *** [CMakeFiles/cmTC_38a58.dir/build.make:66：CMakeFiles/cmTC_38a58.dir/CheckSymbolExists.c.o] 错误 1
make[1]: 离开目录“/tmp/yaourt-tmp-redapple/aur-conky-lua/src/conky-1.10.1/CMakeFiles/CMakeTmp”
make: *** [Makefile:126：cmTC_38a58/fast] 错误 2

>File /tmp/yaourt-tmp-redapple/aur-conky-lua/src/conky-1.10.1/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <unistd.h>

>int main(int argc, char** argv)
{
  (void)argv;
#ifndef pipe2
  return ((int*)(&pipe2))[argc];
#else
  (void)argc;
  return 0;
#endif
}

>Determining if the function iw_sockets_open exists failed with the following output:
Change Dir: /tmp/yaourt-tmp-redapple/aur-conky-lua/src/conky-1.10.1/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_579d1/fast"
/usr/bin/make -f CMakeFiles/cmTC_579d1.dir/build.make CMakeFiles/cmTC_579d1.dir/build
make[1]: 进入目录“/tmp/yaourt-tmp-redapple/aur-conky-lua/src/conky-1.10.1/CMakeFiles/CMakeTmp”
Building C object CMakeFiles/cmTC_579d1.dir/CheckFunctionExists.c.o
/usr/bin/cc  -D_LARGEFILE64_SOURCE -D_POSIX_C_SOURCE=200809L  -std=c99 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong  -DCHECK_FUNCTION_EXISTS=iw_sockets_open   -o CMakeFiles/cmTC_579d1.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.5/Modules/CheckFunctionExists.c
Linking C executable cmTC_579d1
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_579d1.dir/link.txt --verbose=1
/usr/bin/cc  -std=c99 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong  -DCHECK_FUNCTION_EXISTS=iw_sockets_open   -Wl,-O1,--sort-common,--as-needed,-z,relro  CMakeFiles/cmTC_579d1.dir/CheckFunctionExists.c.o  -o cmTC_579d1 -rdynamic 
CMakeFiles/cmTC_579d1.dir/CheckFunctionExists.c.o：在函数‘main’中：
CheckFunctionExists.c:(.text.startup+0xe)：对‘iw_sockets_open’未定义的引用
collect2: 错误：ld 返回 1
make[1]: *** [CMakeFiles/cmTC_579d1.dir/build.make:98：cmTC_579d1] 错误 1
make[1]: 离开目录“/tmp/yaourt-tmp-redapple/aur-conky-lua/src/conky-1.10.1/CMakeFiles/CMakeTmp”
make: *** [Makefile:126：cmTC_579d1/fast] 错误 2

**Comment by redapple0204** [comment]
@K-Guan arch问题太多了
1.开机5小时以后终端无法打开
2.开机5小时以后cpu占用始终100%
3.开机5小时以后部分程序变成英文，gnome自带的所有程序都变成了英文

**Comment by redapple0204** [comment]
@K-Guan arch按键盘上的屏幕截图键后无法开启中端
找了半天没有和我一样的.......偶发性？

**Comment by redapple0204** [comment]
@K-Guan 也不能说是按了截图吧...反正10分钟内必须出现这种情况

**Comment by redapple0204** [comment]
话说段错误 (核心已转储)是什么东西，再打开网易云音乐的时候出现的
网上全是c++程序的错误，根本没用

**Comment by redapple0204** [comment]
@K-Guan 没错了，找到了问题的根源
gvfsd-smb-brows服务占用cpu100%
而且不能关闭，要不会导致终端无法打开（终端依赖这个服务）
还会导致无法读取ntfs分区

**Comment by redapple0204** [comment]
而且也找不到可用的解决办法

**Comment by redapple0204** [comment]
@K-Guan 我必须要手动启动服务啊，好烦人！
/usr/lib/gnome-terminal/gnome-terminal-server

**Comment by redapple0204** [comment]
好吧，这是我提的三个问题，都没人回答
https://bbs.archlinux.org/viewtopic.php?pid=1642440#p1642440
http://unix.stackexchange.com/questions/296995/gnome-terminal-start-error
https://bugs.archlinux.org/task/50106

**Comment by redapple0204** [comment]
用了zsh倒是可以打开终端了，但是gnome组件全都变成English！

**Comment by redapple0204** [comment]
好吧，刚刚去贴吧问了下，发现至少5人和我情况一样，难道是重大bug？

**Comment by redapple0204** [comment]
哦我的天哪，archlinux，linux吧都有好多人遇到这个问题，难道真的是bug？
