### ISSUE TITLE
终于考完了

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#215]
@lizongzeshunshun

**Comment by lizongzeshunshun** [comment]
哈哈我们5.2/5.3考

**Comment by qu123xxx** [comment]
大佬，你的这个pcs bat似乎被封掉了？下载下来的文件是乱码诶，提示err122

**Comment by lizongzeshunshun** [comment]
@qu123xxx 是的目前百度云盘封杀的很厉害，正在寻找解决方案

**Comment by qu123xxx** [comment]
有个PanDownload_v1.1.0似乎还行

**Comment by lizongzeshunshun** [comment]
这个好像已经收录在教程中了

**Comment by qu123xxx** [comment]
似乎没有，还有那些个啥百度云破解版也还有点用。但是需要第三方登录且速度不太稳定。

**Comment by lizongzeshunshun** [comment]
详见教程方法2

**Comment by qu123xxx** [comment]
不好意思我刚刚看到了，我这有个百度云客户端似乎还有点效果。但是需要第三方登录，下载速度不太稳定。

**Comment by qu123xxx** [comment]
![Uploading QQ图片20170419125949.png…]()

**Comment by lizongzeshunshun** [comment]
其实百度云从服务端限速什么破解方法一点用都没有。。所以最好的方法还是会员。。我在想到时候做一个工具：
非会员账户文件->分享->转存到有会员的账户->获取外链->下载

**Comment by qu123xxx** [comment]
但是这样的话那个会员账号不会很容易被封号呢......当然如果个人使用那倒是没问题
哈哈，这个想法是没有办法的办法啦~

**Comment by lizongzeshunshun** [comment]
不被发现应该没事。。
国内的网盘实在是太坑。。

**Comment by qu123xxx** [comment]
小范围用一般没事，如果是大范围的话那肯定会被发现的。
毕竟大家不是把它当做网盘来用，而是当作下载软件嘛~

**Comment by lizongzeshunshun** [comment]
是的。百度云已经形成一种生态了，可以说是一种形式的垄断

**Comment by qu123xxx** [comment]
其实还有115，只不过是百度免费嘛。

**Comment by lizongzeshunshun** [comment]
但是现在大多数分享都是百度云。。
要我说，如果是百度云重度用户，还不如买个会员，也不贵，一了百了

**Comment by qu123xxx** [comment]
百度云封资源，115好点。买个会员是好，问题是会员之上还有超级会员。。。。。。

**Comment by redapple0204** [comment]
@qu123xxx 别急...我这不是考完了嘛，晚上就更新（最晚明天）

**Comment by redapple0204** [comment]
@lizongzeshunshun 话说你们那么晚考.....
我们考完好轻松

**Comment by redapple0204** [comment]
@qu123xxx 好啦，你看看新方法，不会断断续续的啦！

**Comment by redapple0204** [comment]
@lizongzeshunshun 顺便，你的这种新方法已经在“百度云老司机”（好像是）这个项目实现了，然而项目的作者还是不堪重负，所以....也挂了

**Comment by redapple0204** [comment]
虽然说百度云不贵，但是对于我们学生来说自己负担还是不太行....关键是我有钱没处花，不是跟你说过嘛
@lizongzeshunshun

**Comment by qu123xxx** [comment]
@redapple0204 好的哦，谢谢你啦
