### ISSUE TITLE
50M宽带用方法五只有1M/s左右怎么破。。。。。。

### ISSUE THREAD

**Issue by blackcomb7** [redapple0204/my-boring-python#218]
您好，感谢您开 Issue 来反馈信息，在提交前，请确保您已经检查了以下内容!

* 如果您发现本项目有问题，请积极的提出您的问题，我们将会很快修复
* 如果您想要获取破解crossover的补丁，请访问[这里](http://tieba.baidu.com/p/4897237773)
* 如果您想问关于技术方面的问题，请您详细描述，最好配上图，我们尽力解答。
* 如果您想获取几何画板破解版，请您：
 - 提供信息证明您**不是几何画板公司的员工**
 - 保证您不会泄露破解文件
 
 说明：建议有条件者还是支持正版，毕竟开发出这样的软件不容易。
 
 谢谢您的配合。
 
当然您也可以只是一般性的和我聊天。

（建议您翻一翻Issues哦，有许多有价值的技术讨论文章）

PS: Issues处理时间：

* 周一至周五(Weekday): 12:00~13:00和17:30~18:10和21:00~22:00
* 周六至周日(Weekend): 时间不定，随时可能回复

**Comment by redapple0204** [comment]
@blackcomb7 请尝试把aria2c -c -s10 改成aria2c -c -s16，如果仍然不行，请等待我周末发绝招![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png?t=20140803)

**Comment by redapple0204** [comment]
@blackcomb7 绝招（方法一）已发，请查看。
