### ISSUE TITLE
screenshots for ”aget百度云破解"

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#219]
![default](https://cloud.githubusercontent.com/assets/16254644/25278784/1b2ce186-26d7-11e7-9f52-171e7c4335b5.PNG)
![1](https://cloud.githubusercontent.com/assets/16254644/25278785/1b2e8748-26d7-11e7-9daa-384c065c1dc4.PNG)
![2](https://cloud.githubusercontent.com/assets/16254644/25278788/1b2fd594-26d7-11e7-9a8c-9b51d654fae8.PNG)
![3](https://cloud.githubusercontent.com/assets/16254644/25278786/1b2ec8d4-26d7-11e7-90f1-5b6a91951061.PNG)
![4](https://cloud.githubusercontent.com/assets/16254644/25278787/1b2f8b5c-26d7-11e7-80b7-1ab848ca8a80.PNG)
![5](https://cloud.githubusercontent.com/assets/16254644/25278789/1b314924-26d7-11e7-89d0-aa929e67683d.PNG)
![6](https://cloud.githubusercontent.com/assets/16254644/25278791/1b66bbea-26d7-11e7-8467-961f64fe6a54.PNG)
![7](https://cloud.githubusercontent.com/assets/16254644/25278792/1b6bf952-26d7-11e7-8429-ddaea970959e.PNG)
![8](https://cloud.githubusercontent.com/assets/16254644/25278793/1b6c3ee4-26d7-11e7-8632-f373a61abfec.PNG)
![9](https://cloud.githubusercontent.com/assets/16254644/25278794/1b6d112a-26d7-11e7-970e-a9b224c22429.PNG)
![10](https://cloud.githubusercontent.com/assets/16254644/25278796/1b6e5d00-26d7-11e7-888a-77df2fbf2532.PNG)
![11](https://cloud.githubusercontent.com/assets/16254644/25278795/1b6dafae-26d7-11e7-97a4-7ed53b4eb54b.PNG)
![12](https://cloud.githubusercontent.com/assets/16254644/25278797/1b9d4b6a-26d7-11e7-8b1c-bcf1ee64e588.PNG)
![13](https://cloud.githubusercontent.com/assets/16254644/25278798/1ba47584-26d7-11e7-8273-d2b8d21494c5.PNG)
![14](https://cloud.githubusercontent.com/assets/16254644/25278800/1ba7674e-26d7-11e7-8f62-d0ea35e3ab01.PNG)
![15](https://cloud.githubusercontent.com/assets/16254644/25278799/1ba73b52-26d7-11e7-813f-6fc30004f07a.PNG)
![16](https://cloud.githubusercontent.com/assets/16254644/25278801/1ba83444-26d7-11e7-999e-a09a29af36f4.PNG)
![17](https://cloud.githubusercontent.com/assets/16254644/25278802/1bb10330-26d7-11e7-86b1-3e1268664066.PNG)
![18](https://cloud.githubusercontent.com/assets/16254644/25278803/1be83300-26d7-11e7-8e99-a1ab7febd98c.PNG)
![19](https://cloud.githubusercontent.com/assets/16254644/25278804/1bee75a8-26d7-11e7-8235-dde760eff5bb.PNG)
![20](https://cloud.githubusercontent.com/assets/16254644/25278805/1beeb554-26d7-11e7-97f1-d46907ecfd58.PNG)
![21](https://cloud.githubusercontent.com/assets/16254644/25278806/1befa1da-26d7-11e7-9675-6636873b301c.PNG)
![22](https://cloud.githubusercontent.com/assets/16254644/25278808/1bf49e38-26d7-11e7-9148-8c4527d8b124.PNG)
![23](https://cloud.githubusercontent.com/assets/16254644/25278807/1bf0f6a2-26d7-11e7-9cb8-0a4f1a04736e.PNG)
![24](https://cloud.githubusercontent.com/assets/16254644/25278809/1c216b52-26d7-11e7-8d57-5a3c3634f4a4.PNG)
![25](https://cloud.githubusercontent.com/assets/16254644/25278810/1c298d8c-26d7-11e7-8a53-6a7501ed97de.PNG)
![26](https://cloud.githubusercontent.com/assets/16254644/25278811/1c2cb3f4-26d7-11e7-9eff-05681db527dd.PNG)
![27](https://cloud.githubusercontent.com/assets/16254644/25278813/1c2e75f4-26d7-11e7-9703-3f27c7c740cc.PNG)
![28](https://cloud.githubusercontent.com/assets/16254644/25278812/1c2dfcaa-26d7-11e7-95fb-121ae32d0274.PNG)
![29](https://cloud.githubusercontent.com/assets/16254644/25278814/1c30e99c-26d7-11e7-8250-47e0057c92a0.PNG)
![30](https://cloud.githubusercontent.com/assets/16254644/25278815/1c567ad6-26d7-11e7-8ca1-a10b6450c510.PNG)
![31](https://cloud.githubusercontent.com/assets/16254644/25278817/1c612e7c-26d7-11e7-82bf-ee00f62bdac2.PNG)
![32](https://cloud.githubusercontent.com/assets/16254644/25278816/1c604426-26d7-11e7-82e4-4896e17cee9f.PNG)
![33](https://cloud.githubusercontent.com/assets/16254644/25278818/1c6934dc-26d7-11e7-9485-7bad82f435fc.PNG)
![34](https://cloud.githubusercontent.com/assets/16254644/25278819/1c6a4ec6-26d7-11e7-8144-b7ac526bf37f.PNG)
![35](https://cloud.githubusercontent.com/assets/16254644/25278820/1c6ba24e-26d7-11e7-854e-cc6fed525a3e.PNG)
![36](https://cloud.githubusercontent.com/assets/16254644/25278821/1c8beb94-26d7-11e7-9c77-fe916d31e0d7.PNG)
![37](https://cloud.githubusercontent.com/assets/16254644/25278822/1c96d1f8-26d7-11e7-9713-bdfd85fc92c0.PNG)
![38](https://cloud.githubusercontent.com/assets/16254644/25278823/1c981888-26d7-11e7-8fa6-449962f0c572.PNG)
![39](https://cloud.githubusercontent.com/assets/16254644/25278824/1ca129a0-26d7-11e7-9c40-2407e414bb8e.PNG)
![40](https://cloud.githubusercontent.com/assets/16254644/25278825/1ca3ec1c-26d7-11e7-963d-c58e08f76d33.PNG)
![41](https://cloud.githubusercontent.com/assets/16254644/25278826/1ca4d2a8-26d7-11e7-8016-3e0458ac7494.PNG)
![42](https://cloud.githubusercontent.com/assets/16254644/25278827/1cc45cb8-26d7-11e7-9e00-64f16be863cf.PNG)
![43](https://cloud.githubusercontent.com/assets/16254644/25278828/1ccedf58-26d7-11e7-9906-c0a2d233f110.PNG)
![44](https://cloud.githubusercontent.com/assets/16254644/25278829/1cd5a310-26d7-11e7-8d61-9c2ed08ee2b7.PNG)
![45](https://cloud.githubusercontent.com/assets/16254644/25278830/1cd5e2c6-26d7-11e7-8049-1a1c3a87b83c.PNG)
![46](https://cloud.githubusercontent.com/assets/16254644/25278831/1cdabb20-26d7-11e7-9d56-07f5ec65bee3.PNG)
![47](https://cloud.githubusercontent.com/assets/16254644/25278832/1cdf874a-26d7-11e7-90cb-83163302ec9f.PNG)
![48](https://cloud.githubusercontent.com/assets/16254644/25278833/1cf98fb4-26d7-11e7-96c3-befbd81ec9ff.PNG)
![49](https://cloud.githubusercontent.com/assets/16254644/25278834/1d05a2ea-26d7-11e7-92ea-97fd526bdd76.PNG)
![50](https://cloud.githubusercontent.com/assets/16254644/25278836/1d0e5868-26d7-11e7-851b-40cfd2440593.PNG)
![51](https://cloud.githubusercontent.com/assets/16254644/25278835/1d0e2f14-26d7-11e7-826e-bc7c41d3c101.PNG)
![52](https://cloud.githubusercontent.com/assets/16254644/25278837/1d178834-26d7-11e7-92f2-8292d7cef966.PNG)
![53](https://cloud.githubusercontent.com/assets/16254644/25278838/1d2e9d1c-26d7-11e7-91a7-fbcbf4a12f0e.PNG)

**Comment by lizongzeshunshun** [comment]
why not add to the main file container?

**Comment by redapple0204** [comment]
太多了.....
