### ISSUE TITLE
是否有办法提权？

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#220]
表示我弄了个没有管理员账户的vps（windows）
然后什么软件都运行不了，提示输入管理员密码.....
然后我把我的get system程序传上去，结果没法用....
然后我试着用奇异果破解密码，结果打开也提示输入密码.........
所以....有什么办法破解密码啊....
@lizongzeshunshun

**Comment by lizongzeshunshun** [comment]
1. windows几
2. 把get system发一下。。我弄丢了

**Comment by redapple0204** [comment]
1.win2012
2.
[system.zip](https://github.com/redapple0204/my-boring-python/files/949449/system.zip)

**Comment by lizongzeshunshun** [comment]
@redapple0204 
ok

server ip/key给我

**Comment by redapple0204** [comment]
只能下载这个远程链接配置:[AppOnFly for Windows users.rdp.tar.gz](https://github.com/redapple0204/my-boring-python/files/949459/AppOnFly.for.Windows.users.rdp.tar.gz)
账户:1459966373@qq.com
密码你懂得
thx啦
