### ISSUE TITLE
linus六月份要来北京？

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#221]
@lizongzeshunshun 
他不是说了他不想来中国吗....
![qq 20170426213037](https://cloud.githubusercontent.com/assets/16254644/25437068/c44c3cb4-2ac7-11e7-876b-1f8a1305900c.png)

**Comment by lizongzeshunshun** [comment]
interesting

**Comment by redapple0204** [comment]
@lizongzeshunshun 话说你还有什么好用的ss吗...现在那种共享网站的慢的要死

**Comment by redapple0204** [comment]
PS：我看到罗湖区的试卷答案都发出来了，你们还没考？

**Comment by lizongzeshunshun** [comment]
@redapple0204 nope 答案在哪。。

**Comment by lizongzeshunshun** [comment]
哦不对，我们自己出

**Comment by redapple0204** [comment]
好吧...
