### ISSUE TITLE
搞了个ss服务玩

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#222]
30元/月 md这才叫科学上网！

![tim 20170429144426](https://cloud.githubusercontent.com/assets/10304206/25553603/559afa2e-2cea-11e7-8021-33c8873bec1c.png)

你有什么私聊的工具到时候我给你

**Comment by redapple0204** [comment]
@lizongzeshunshun 我到qq上找你好了....

**Comment by redapple0204** [comment]
此外，我也弄到了一个vps，下次试试看效果如何（5美元一个月）
