### ISSUE TITLE
似乎gentoo的使用并没有想象中那么麻烦

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#223]
@lizongzeshunshun 编译的速度很快....
你所说的chromium编译速度慢，然后我用chrome代替了，安装速度还挺快的....
输入法还是有点毛病....不过总体还好
现在我看看编译wine要多久...
![5](https://cloud.githubusercontent.com/assets/16254644/25561012/f89e806a-2d94-11e7-9908-2a3ea9d7bfc8.PNG)

**Comment by lizongzeshunshun** [comment]
但是用chrome替代就失去了gentoo的意义啊。。主要我担心损耗cpu

**Comment by lizongzeshunshun** [comment]
ss等我回深圳tv

**Comment by redapple0204** [comment]
你是想要纯开源？.....
好

**Comment by lizongzeshunshun** [comment]
@redapple0204 gentoo的意义就在编译的可定制性 直接用二进制包就没意思了

**Comment by redapple0204** [comment]
然而chromium好像也不能自定义什么吧....

**Comment by redapple0204** [comment]
话说这32位库真是烦死人，谷歌的说法全是说装个什么emu什么鬼的，结果后来在贴吧上问到了正确的方法....
好讽刺的感觉....

**Comment by redapple0204** [comment]
此外不知道emerge搞的是什么鬼！用它来装软件一大堆错误，我直接编译就好好的....

**Comment by lizongzeshunshun** [comment]
@redapple0204 tv number pls

**Comment by redapple0204** [comment]
还是原来那个358 335 578
