### ISSUE TITLE
推荐软件 Wallpaper Engine

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#224]
..动态桌面 EG：
![giphy](https://cloud.githubusercontent.com/assets/10304206/25570060/7d0d4854-2e53-11e7-9ea5-8e35f826b86e.gif)

**Comment by redapple0204** [comment]
看不清图片.....
具体可以干啥？

**Comment by lizongzeshunshun** [comment]
动态桌面 桌面直接播放视频

**Comment by redapple0204** [comment]
似乎不错，我看看
