### ISSUE TITLE
easyaccess

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#225]
@redapple0204 如果还留着的话发给我一下，谢谢

**Comment by redapple0204** [comment]
this?
[es.tar.gz](https://github.com/redapple0204/my-boring-python/files/970276/es.tar.gz)

**Comment by lizongzeshunshun** [comment]
tkx

**Comment by lizongzeshunshun** [comment]
密码多少来自

**Comment by redapple0204** [comment]
redapple+现在时间的小时*10
例如说现在20点就是redapple200

**Comment by lizongzeshunshun** [comment]
thx
