### ISSUE TITLE
未找到 'aget' 命令

### ISSUE THREAD

**Issue by tiexo** [redapple0204/my-boring-python#227]
![qq 20170506214755](https://cloud.githubusercontent.com/assets/8164505/25772864/56d87544-32a6-11e7-9ac0-e72827f334e0.png)

版本是win10 1703
按照步骤做，提示未找到aget命令...

**Comment by lizongzeshunshun** [comment]
你用的windows的linux子系统？

**Comment by tiexo** [comment]
是的

**Comment by lizongzeshunshun** [comment]
应该是环境变量的问题

**Comment by lizongzeshunshun** [comment]
尝试一下重启子系统

**Comment by lizongzeshunshun** [comment]
@tiexo 目前没有很好的解决办法 这似乎是挂载系统的一个bug 还是暂时用虚拟机或者docker把

**Comment by redapple0204** [comment]
@lizongzeshunshun why？
@tiexo 我的bash转成archlinux后（使用这个项目https://github.com/alwsl/alwsl）使用正常，可以考虑下

**Comment by tiexo** [comment]
@lizongzeshunshun 好的，多谢

**Comment by tiexo** [comment]
@redapple0204 非常感谢，安装的时候一直卡在“renaming shortcut”你有遇到吗？

![default](https://cloud.githubusercontent.com/assets/8164505/25781706/9039e92a-336f-11e7-8e9b-652e6371b1f0.PNG)

**Comment by redapple0204** [comment]
@tiexo 解决了？

**Comment by tiexo** [comment]
@redapple0204 遇到新问题了。。。

![default](https://cloud.githubusercontent.com/assets/8164505/25812806/020b03a6-344a-11e7-88c6-56a6636598d1.PNG)

**Comment by lizongzeshunshun** [comment]
网络链接太慢 挂代理

**Comment by redapple0204** [comment]
@tiexo 参照https://github.com/redapple0204/my-boring-python/blob/master/tutorial/Arch-Install-Guide/ARCH-INSTALL-GUIDE4.0%20RTM.doc中的改源

**Comment by tiexo** [comment]
@redapple0204 真快崩溃了....
现在应该只剩最后一个问题了，我安装完python和pip
应该输入哪条命令安装aget？
`pip3 install aget`
这个好像没用...

**Comment by redapple0204** [comment]
pip install aget

**Comment by redapple0204** [comment]
安装使用的命令是sudo pacman -S python python-pip

**Comment by tiexo** [comment]
![default](https://cloud.githubusercontent.com/assets/8164505/25853708/50995c1e-3500-11e7-9db0-d5a450c2cec8.PNG)

你看看。  @redapple0204

**Comment by redapple0204** [comment]
看看你的PATH....
> echo $PATH

**Comment by tiexo** [comment]
`root@FMBM-NG8ODO:~# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program Files/MacType:/mnt/c/Program Files/nodejs:/mnt/c/Program Files/Git/cmd:/mnt/c/Users/jianw/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/jianw/AppData/Roaming/npm`

@redapple0204

**Comment by redapple0204** [comment]
@tiexo 看起来很难处理啊...连import都识别不了也是奇怪....
不过抱歉啊...今天我没啥时间了，作业还没写完
等到明天我再查找下，话说方法5没法用么？

**Comment by tiexo** [comment]
@redapple0204 麻烦了，实在不行就算了，我也是被烦的不行。
方法5用是能用，速度不够快，不到两兆。

**Comment by redapple0204** [comment]
试试nano /usr/sbin/pip
然后开头加上#!/usr/bin/python

**Comment by redapple0204** [comment]
@tiexo

**Comment by tiexo** [comment]
文件里面有这行 @redapple0204

**Comment by redapple0204** [comment]
把`给删了

**Comment by tiexo** [comment]
是没有这个符号。。。
我刚刚插入代码弄的==

**Comment by lizongzeshunshun** [comment]
@redapple0204 看起来pip的指令被bash识别了

**Comment by redapple0204** [comment]
@lizongzeshunshun 是的，但是按照/usr/sbin/pip的开头那个#!/usr/bin/python来看不应该啊
@tiexo 试试终端执行python，看会怎样

**Comment by tiexo** [comment]
@redapple0204 
`bash: /usr/sbin/python: cannot execute binary file: Exec format error`

**Comment by redapple0204** [comment]
你会不会装到x86的python了？
查看/etc/pacman.d/mirrorslist 和 /etc/pacman.conf中的内容

**Comment by redapple0204** [comment]
你会不会装到x86的python了？
查看/etc/pacman.d/mirrorslist 和 /etc/pacman.conf中的内容

**Comment by redapple0204** [comment]
话说回来.../usr/sbin/python这个位置有点奇怪
试试执行/usr/bin/python，/bin/python，/usr/python，看哪个能成功的？
或者ls看看/usr/sbin/python从那链接过去的？

**Comment by tiexo** [comment]
![default](https://cloud.githubusercontent.com/assets/8164505/25900236/59d64ace-35c5-11e7-9710-4992651297b6.PNG)

![default](https://cloud.githubusercontent.com/assets/8164505/25900327/ac7fd948-35c5-11e7-95b5-5ec266b0b757.PNG)

```
root@FMBM-NG8ODO:~# /usr/bin/python
bash: /usr/bin/python: cannot execute binary file: Exec format error
root@FMBM-NG8ODO:~# /bin/python
bash: /bin/python: cannot execute binary file: Exec format error
root@FMBM-NG8ODO:~# /usr/python
bash: /usr/python: No such file or directory

```
@redapple0204

**Comment by redapple0204** [comment]
@tiexo 为什么会是i686呢？wsl是只支持x86_64的
稍等，我到项目内看一下

**Comment by tiexo** [comment]
当时你跟我说要改源，就随便找了个网易的i686
后来安装出了问题，搜索要把architecture改成i686才解决

**Comment by redapple0204** [comment]
@tiexo 不能用i686，请全部改回x86_64，包括网易后面的i686
因为wsl只支持x86_64
然后sudo pacman -Rssn python python-pip（彻底卸载python）
再pip install aget
(你早说嘛....害得我还下载那个sfs文件看看是不是出错了，然后xp又下载不了，还挂了个虚拟机....)

**Comment by redapple0204** [comment]
ps:你是不是执行了pacman -Syu 如果是的话就要重新安装wsl了....

**Comment by tiexo** [comment]
@redapple0204 我重装了两遍，真要吐血了，解决一个问题又会冒出三个问题。
现在到了最后一步又报错了，搜索半天也没啥好办法解决
```
root@FMBM-NG8ODO:~# pip install aget
/usr/bin/python: /usr/lib/libc.so.6: version `GLIBC_2.25' not found (required by /usr/lib/libpython3.6m.so.1.0)
```

**Comment by lizongzeshunshun** [comment]
@tiexo 

> pacman -S glibc

**Comment by tiexo** [comment]
@lizongzeshunshun @redapple0204 非常感谢两位的耐心帮助
安装完glibc后又报错SSL问题，又安装了openssl才解决，真是问题一个接一个。
好在应该全部弄好了...谢谢两位

截图这种情况是正常的吗？不是报错吧？

![default](https://cloud.githubusercontent.com/assets/8164505/25946712/ee3787dc-367e-11e7-9298-a1781dad671b.PNG)

**Comment by redapple0204** [comment]
不会的，我问过项目负责人了@tiexo

**Comment by redapple0204** [comment]
https://github.com/PeterDing/aget/issues/5

**Comment by tiexo** [comment]
妈了个蛋，又出问题了。。。我准备放弃这个
用虚拟机试试...
现在一打开archlinux就提示
```
错误: 0x8007001f
按任意键继续...

```
cmd里面输入bash也提示这个。

**Comment by redapple0204** [comment]
@tiexo 真是服了，这破wsl咋那么多问题
我记得当初我也出现了这个问题，多重装wsl几次貌似就好了...
不过既然你想稳定真心推荐虚拟机。。。

**Comment by tiexo** [comment]
@redapple0204 嗯嗯...问题太多了，好在成功用了一次。。。
勉强能够安慰自己

**Comment by lizongzeshunshun** [comment]
@redapple0204 到时候我会搞个docker镜像放出来

**Comment by redapple0204** [comment]
@lizongzeshunshun ok，thx

**Comment by tiexo** [comment]
额，还的麻烦两位，我用虚拟机方案
遇到的问题和上面一样，也要求安装glibc，这点可以在wiki里面说明下。
但是这里要求root用户才行，怎么弄
![default](https://cloud.githubusercontent.com/assets/8164505/25952758/1f15441a-3694-11e7-85e7-ad09d97aea9f.PNG)

**Comment by redapple0204** [comment]
@tiexo 命令前加sudo
此外看不到你的回复，被删了？

**Comment by tiexo** [comment]
@redapple0204  我发现了。。。忘记加sudo这个原因
但是问题依然还有很多很多，本来一个问题的现在变成好几个问题了T.T好想哭

安装完openssl后，我输入sudo pip install aget就提示下面这个
![default](https://cloud.githubusercontent.com/assets/8164505/25954587/611c1cb2-3699-11e7-8c12-7064ad7bb1e4.PNG)
现在我输入带sudo的命令都提示这个...

然后....我关掉putty，发现连putty都打不开了
提示Server unexpectedly closed network connection
搜索半天修修改改，现在又变成network error:connection refused

至于为什么不用xshell，因为我根本安装不了，一打开安装包就停止运行。。。
我先重装一遍，再总结下问题反馈过来。

**Comment by tiexo** [comment]
我感觉首先要解决的问题是，无论输入任何sudo命令，都会报错如下
```
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: unable to load /usr/lib/sudo/sudoers.so: libssl.so.1.0.0: cannot open shared object file: No such file or directory
sudo: fatal error, unable to load plugins 
```
发现了一个同类案例 https://bbs.archlinux.org/viewtopic.php?id=225237
安装openssl好像就这样了，你俩能看懂咋解决的么。

**Comment by lizongzeshunshun** [comment]
@tiexo  看起来你的openssl存在问题。。我看了两个链接，基本意思是从arch的安装iso中重新安装openssl，但是对于win10的wsl看起来有些困难

我现在想了一个方案，你可以试试（不保证可以，因为我也没试过）：

首先下载arch的iso：https://www.archlinux.org/download/
然后用vmware或者hyper-v从iso引导进入arch的LIVE
然后挂载wsl的文件系统（我不确定这个是否可行，你可以找些资料）
然后执行`pacman --root <挂载目录> -S openssl

**Comment by lizongzeshunshun** [comment]
查了一下，wsl的文件系统应该是在以下两个目录的其中一个

`%localappdata%\Lxss\rootfs`

or

`C:\Users\Username\AppData\Local\Lxss\rootfs`(记得替换username为你的用户名)

如果还找不到，也许可以通过c盘全盘搜索'dev'等linux关键词查找

**Comment by tiexo** [comment]
@lizongzeshunshun  我现在用的是虚拟机
应该和wsl没关系吧？

**Comment by redapple0204** [comment]
@tiexo sudo pacman -S libssl试试

**Comment by lizongzeshunshun** [comment]
@redapple0204 pacman本身需要openssl所以这个操作是无效的

**Comment by tiexo** [comment]
不行，任何sudo命令都会报错。。。

**Comment by lizongzeshunshun** [comment]
@tiexo 虚拟机好办

先下载一个arch镜像然后进liveCD

然后挂载你的文件系统然后

`pacman --root <挂载目录> -S openssl`
