### ISSUE TITLE
反监控任务清单

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#228]
使用语言:python3&vbs
Step1:编写监测系统访问网站
Step2:局域网发送消息
Step3:客户端
Step4:设法安装服务端

**Comment by lizongzeshunshun** [comment]
Step1-3: DONE

**Comment by redapple0204** [comment]
Step4：ERROR：学校内网和教室网络不同网段，正在尝试
try：跨网段传输
except error
外网传输
