### ISSUE TITLE
pip3 install aget错误

### ISSUE THREAD

**Issue by 2006bt** [redapple0204/my-boring-python#229]
错误提示：
Downloading/unpacking aget
  Downloading aget-0.1.12.tar.gz
  Running setup.py (path:/tmp/pip_build_2006bt/aget/setup.py) egg_info for package aget
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_2006bt/aget/setup.py", line 13, in <module>
        raise RuntimeError("aget requires Python 3.5.0+")
    RuntimeError: aget requires Python 3.5.0+
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_2006bt/aget/setup.py", line 13, in <module>

    raise RuntimeError("aget requires Python 3.5.0+")

RuntimeError: aget requires Python 3.5.0+

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_2006bt/aget
Storing debug log for failure in /home/2006bt/.pip/pip.log

**Comment by lizongzeshunshun** [comment]
@2006bt 你用的是vmware还是wsl

**Comment by redapple0204** [comment]
那么明显的错误看不到？？？？
>aget requires Python 3.5.0+

**Comment by lizongzeshunshun** [comment]
@redapple0204 但是理论上按照我们的步骤应该就是装的3.5+啊

**Comment by redapple0204** [comment]
@lizongzeshunshun 不一定，ubuntu14 for windows（win10创意者更新以前）就不行
