### ISSUE TITLE
请问您的vim插件和配置是怎么弄的。

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#23]
@K-Guan 看到了您的vim截图，感觉比我默认的好几百倍（语法高亮，自动补全，貌似还有提示错误的功能？），我尝试用您上次给我的那个家目录的备份，我把.vimrc和.vim复制到了我的家目录。打开普通文件还好，如果打开了.py文件，一打开就会提示一大堆插件错误。无法使用。

ps：我不知道您为什么从六月份开始就突然消失，虽然您可能再也无法看到这个issue，甚至再也不会回来了。但是我还是衷心的感谢您，在我以前什么都不会的时候耐心的指导我。
我永远期待着您的回复！

**Comment by redapple0204** [comment]
替换好了，但是还有一个小问题，请问为什么这里乱码了
![qq 20160830135806](https://cloud.githubusercontent.com/assets/16254644/18077682/e44ae26a-6eb9-11e6-8bdd-8dce6f266f46.png)

**Comment by lizongzeshunshun** [comment]
@redapple0204 我上次也是，听说要装个什么字体

**Comment by redapple0204** [comment]
@lizongzeshunshun 这个还要字体....什么字体？

**Comment by K-Guan** [comment]
@redapple0204 咳咳，我还活着。

**Comment by K-Guan** [comment]
首先一大堆错误你倒是把错误贴出来……

然后这个是powerline，需要装powerline自己的字体……我怎么记得我跟你说过一次？

**Comment by redapple0204** [comment]
@K-Guan 1.那么就不见，我还以为.....
~~话说您的arch那么久没滚要挂了吧~~
2.没有啊.....话说现在是不是就行了？
![2016-12-01 18-28-33](https://cloud.githubusercontent.com/assets/16254644/20790619/12c7341c-b7f4-11e6-8f63-d863cbbafb60.png)
3.话说我还真有个问题要问.....
在chrome中，鼠标轻触到某个地方的时候，会有黑框....
如图：
![e40da18b87d6277fc0144a1221381f30e924fca6](https://cloud.githubusercontent.com/assets/16254644/20790687/714847a6-b7f4-11e6-93bf-45cb51710ca4.jpg)

ps：GUP：intel，已安装显卡驱动
system：arch x64

**Comment by redapple0204** [comment]
Oops.....看起来又......

**Comment by redapple0204** [comment]
IT SEEM.....
OOPS，MAYBE YOU CAN NOT COME BACK
BYE....
CLOSE THE ISSUE 
2016/12/02 21:48
BY REDAPPLE0204
（IF YOU SEE THIS ISSUE , PLEASE REPLY IT, THX!)

**Comment by lizongzeshunshun** [comment]
what's wrong

**Comment by redapple0204** [comment]
@lizongzeshunshun Maybe he died again....

**Comment by K-Guan** [comment]
噗走开哦，我的Arch偶尔重装一次= =。最近用上了i3wm，好用极了~
![image](https://cloud.githubusercontent.com/assets/13862535/20870383/1c7a05ea-bac2-11e6-9021-6b9e9cc46ffa.png)
咳咳，不过你这个是咋回事？

啊还有，浏览器是什么？桌面环境呢？

**Comment by redapple0204** [comment]
@K-Guan 桌面管理器玩不6，反正不喜欢平铺....容易被查水表
话说这个....我也觉得奇怪
另外
![2016-12-05 19-38-07](https://cloud.githubusercontent.com/assets/16254644/20883686/6179c38c-bb22-11e6-8daa-924987c9b26d.png)

~~话说您走那么多个月感觉说话口气完全变了，不会上学去了吧~~

**Comment by K-Guan** [comment]
噗……

1. 我的是标签式不是平铺来着……虽然可以自由切换。

2. 咳咳，反正我还是我，至少我的水平你一时半会也赶不上~

3. 口气嘛，你习惯习惯昂。

4. 试着调试下Chrome？禁用所有插件重启？或者直接试试重装？（记得从AUR下载包）

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.哦？wm一直被我误认为平铺....
2.没错
3.恩.....
4.archlinuxcn不行？

**Comment by K-Guan** [comment]
wm是Window Manager（窗口管理器）的缩写呀。。然后当然还是AUR咯，为什么要去Arch Linux CN。

**Comment by redapple0204** [comment]
@K-Guan 因为archlinuxcn有打包好的啊，aur弄来弄去很烦

**Comment by redapple0204** [comment]
顺便，求个i3配置，gnome最近越来越难用了，既然i3不只有平铺那我就准备用i3了。

**Comment by K-Guan** [comment]
昂，i3基本不用配置。官方有文档，你学学就会了。要不有空我发我的给你看。
