### ISSUE TITLE
这个暑假开始，我就要恢复用github跟你交流了

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#241]
表示这个学期跟你在qq上交流是因为这学期我是组长，所以遇到很多事情需要和大家讨论，然后才经常使用qq的。
下个学期我不当组长了，所以也就同样的没有了这个问题，于是就恢复到以前上qq的频率为10次/学期的频率了，所以先通知你下......
btw，这个学期末和暑假我会迎来三件非常困难的事情，届时我情绪可能会非常的不稳定，所以做出的一些行为请你谅解，谢谢。
@lizongzeshunshun

**Comment by lizongzeshunshun** [comment]
@redapple0204

1）好的，加油！

2）我暑假没啥事，应该会搞几个大~新~（项）~闻~（目）。同时我很期待暑假嘛。。虽然只有2个月，但是还是可以爽一番。

**Comment by redapple0204** [comment]
@lizongzeshunshun 
1.谢谢你的鼓励。
2.那....有什么比较好的方向吗，此外，这个暑假是最后一个能够爽的暑假了（因为明年这个时候要上一堆的补课班），而且还不知道要不要军训....

**Comment by lizongzeshunshun** [comment]
@redapple0204 

我现在就有点虚军训了。。

**Comment by redapple0204** [comment]
@lizongzeshunshun 的确，上次4月份那个劳技强度大约是军训的1/10都恶心到我了.......
而且暑假直接到军训这巨大的心里反差......
我们电教组的说初三不军训，不知道是不是真的

**Comment by lizongzeshunshun** [comment]
@redapple0204 反正我们会去

**Comment by redapple0204** [comment]
@lizongzeshunshun 你觉得如何。。
上次初一去的时候好像说初三的就是去玩玩？

**Comment by lizongzeshunshun** [comment]
@redapple0204 不可能的。。

**Comment by redapple0204** [comment]
你觉得你最怕的是哪里。。

**Comment by lizongzeshunshun** [comment]
@redapple0204 感觉都很可怕

**Comment by redapple0204** [comment]
5Days真的挺痛苦...

**Comment by redapple0204** [comment]
而且还要占用暑假。。
觉得军训根本就没啥用。。

**Comment by lizongzeshunshun** [comment]
对啊

**Comment by redapple0204** [comment]
军训其实和那种戒网场所没啥区别。。

**Comment by lizongzeshunshun** [comment]
是的

**Comment by redapple0204** [comment]
有没有办法可以躲过啊....

**Comment by lizongzeshunshun** [comment]
@redapple0204 贴吧有人设计逃脱方案

**Comment by redapple0204** [comment]
where？

**Comment by redapple0204** [comment]
装病估计还是有希望的

**Comment by redapple0204** [comment]
但是逃离估计不显示

**Comment by lizongzeshunshun** [comment]
http://tieba.baidu.com/p/4751308972?pid=101452296073&cid=0#101452296073

**Comment by redapple0204** [comment]
这样子真的不会被抓吗，以前营坪山有几个学生逃跑最后被抓回来然后加训了很多东西.....

**Comment by lizongzeshunshun** [comment]
不好说，但我构想过一个方案，到时候写出来

**Comment by redapple0204** [comment]
教官不是会每隔几个小时查人吗

**Comment by lizongzeshunshun** [comment]
凌晨的时候

**Comment by redapple0204** [comment]
凌晨不是2h查一次么。。

**Comment by redapple0204** [comment]
btw....在大鹏军训的话旁边就是大鹏古城，然后会有很多巴士和的士的...

**Comment by lizongzeshunshun** [comment]
那也有2h，把控好时间间隔，2h一般够走很远了

**Comment by lizongzeshunshun** [comment]
有个手机滴滴更好。。

**Comment by redapple0204** [comment]
1.2h确实能走挺远的，到大鹏古城没有问题，然后的话如果拦不到的士甚至可以到我同学的老家那里......
2.手机不是一军训就会被收吗
