### ISSUE TITLE
要会考了.....你会紧张吗

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#243]
表示今天早上看了那本考前必备小册整个人就不好了.....
发现很多内容都没有过关，而且总共62页花了两个小时才看了19页....
@lizongzeshunshun

**Comment by lizongzeshunshun** [comment]
感觉良好。。

**Comment by lizongzeshunshun** [comment]
做了14、15、16的卷子感觉信息大增

**Comment by redapple0204** [comment]
往年卷子确实挺简单的，但是今年说会加难，然后试做了下第三方的卷子，整个人就不好了....

**Comment by lizongzeshunshun** [comment]
要难一起难，怕啥

**Comment by redapple0204** [comment]
说得有道理....不过就怕到时候那些学校关于生地的分数线不降
他说今年的难度会像广东省那样，然后我看了下广东省的卷子.........

![gcynuu2 u b8ph65 nmi7](https://user-images.githubusercontent.com/16254644/27504840-bdcd6892-58c4-11e7-88e8-f236eee2251c.png)

**Comment by lizongzeshunshun** [comment]
发一下我看看

**Comment by redapple0204** [comment]
https://wenku.baidu.com/view/a0efb5195fbfc77da269b1e5.html

**Comment by lizongzeshunshun** [comment]
不可能这么难的，如果这么难分数线还不降估计招不到几个人

**Comment by redapple0204** [comment]
就不知道他所谓的靠拢是什么概念
btw，你们那里上个月有没有叫几个学生去参加一场秘密考试？我估计可能和生地会考以及中考有关。

**Comment by Guanrenfu** [comment]
test

**Comment by redapple0204** [comment]
test

2017-06-24 18:35 GMT+08:00 Guanrenfu <notifications@github.com>:

**Comment by redapple0204** [comment]
@lizongzeshunshun 貌似这个邮件发送更方便。。还带有桌面通知

2017-06-24 18:36 GMT+08:00 Bc A <redapple02041@gmail.com>:

**Comment by Guanrenfu** [comment]
不过话说回来。。在邮件中直接回复而不用验证密码真的好吗。。万一邮箱被盗了不就完了

2017-06-24 18:36 GMT+08:00 redapple0204 <notifications@github.com>:

**Comment by redapple0204** [comment]
怎么串号了。。。。

2017-06-24 18:39 GMT+08:00 Guanrenfu <notifications@github.com>:

**Comment by lizongzeshunshun** [comment]
666

**Comment by redapple0204** [comment]
真的是服了.....桌面提示竟然还会bug。

2017-06-24 18:56 GMT+08:00 LIZONGZE <notifications@github.com>:
