### ISSUE TITLE
测试题分数统计

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#245]
1.《初中学业水平考试》生物模拟题（1）
得分：38/50
《初中学业水平考试》地理模拟题（1）
得分：42/50
总分：80/100

2.《邦德》生物模拟题（4）
得分：42/50
《邦德》地理模拟题（4）
得分：45/50
总分：87/100

3.《邦德》生物模拟题（5）
得分：44/50
《邦德》地理模拟题（5）
得分：41/50
总分：85/100

**Comment by redapple0204** [comment]
@lizongzeshunshun 你有没有这样一种感觉，好像市面上的题目都是往年会考难度的两倍，甚至两倍以上。

**Comment by lizongzeshunshun** [comment]
@redapple0204 还好
