### ISSUE TITLE
答复

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#252]
@lizongzeshunshun 我妈答应明天晚上整理一些这样的题目，请等待......

**Comment by redapple0204** [comment]
btw，会考分析你看了吧
http://mp.weixin.qq.com/s?__biz=MzI5MTAzOTkxNw==&mid=505031390&idx=1&sn=d637feac4b334d6d33ffcf84a667adf1&chksm=77f8351c408fbc0a7a2f0527de3fddb3e064e3503aacef1b58e2d01bd19628a000e010a031c2&mpshare=1&scene=23&srcid=0628rvW4PD9pBm0aBLr2s8DE#rd

**Comment by lizongzeshunshun** [comment]
@redapple0204 

1）好的谢谢

2）看了

**Comment by redapple0204** [comment]
@lizongzeshunshun 
我妈整理出了一些易错，易考题
但是难题没有整理完，目前这份**只有最后一题**比较难
[题目](https://tpedutw-my.sharepoint.com/personal/redapple0204_tp_edu_tw/_layouts/15/guestaccess.aspx?docid=15dd221807e594054adb2397fcab11c0b&authkey=AR5cwCQn-MMlA3uDCei_-Xg)

还有你那个ss boom了啊，搞了一个多小时都不行，只好发到onedrive上了

**Comment by lizongzeshunshun** [comment]
@redapple0204 非常感谢

ss没钱续费了。。。

**Comment by redapple0204** [comment]
@lizongzeshunshun 怪不得。。

**Comment by redapple0204** [comment]
@lizongzeshunshun btw，建议你到菁优网上看看一些难题。。这里面有些题还是不错的。。
以数学为例：http://www.jyeoo.com/math/ques/search
