### ISSUE TITLE
考的还好吧

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#254]
@lizongzeshunshun 
btw，发现个好玩的事，我们可以直接登陆老师的账号然后改卷。。

**Comment by lizongzeshunshun** [comment]
@redapple0204 
1. 不错不错
2. 嘿嘿嘿

**Comment by redapple0204** [comment]
@lizongzeshunshun 
1.语文阅读题太恶心！！！考的是期中罗湖区联考的题目！
2.明天考完以后....嘿嘿嘿

**Comment by lizongzeshunshun** [comment]
@redapple0204 
???难道我们不是同卷？

**Comment by redapple0204** [comment]
@lizongzeshunshun 你们期中没有参加统考.....

**Comment by redapple0204** [comment]
（罗湖区的统考是4.20号）

**Comment by lizongzeshunshun** [comment]
@redapple0204 那我们是一套卷子吗

ps: 语作文题目《期待的眼神》

**Comment by redapple0204** [comment]
@lizongzeshunshun 是的

**Comment by lizongzeshunshun** [comment]
666

**Comment by redapple0204** [comment]
你自己看看。。。
[当时的答案，注意看第二个阅读题](http://pan.stnts.com/s/HGotZD5)

**Comment by lizongzeshunshun** [comment]
@redapple0204 话说你有英语答案吗

**Comment by redapple0204** [comment]
有！http://pan.stnts.com/s/e5C3cQ0

**Comment by lizongzeshunshun** [comment]
@redapple0204 我们前面的题不一样啊

**Comment by redapple0204** [comment]
@lizongzeshunshun 这是当时的题（其中的），等下我给你发下上午的

**Comment by redapple0204** [comment]
早上的语文：http://pan.stnts.com/s/ZDjXG7h
