### ISSUE TITLE
两位对github应该很熟吧？讨教个问题

### ISSUE THREAD

**Issue by tiexo** [redapple0204/my-boring-python#255]
github直接通过邮件回复评论怎么玩的？
当我收到一个github的邮件通知提醒时，下面写着“reply to this email directly”，应该是能通过邮件直接回复评论的吧？并且在issue里面添加一条回复。

![bd8fb83533fa828b36b0a540f71f4134960a5a36](https://user-images.githubusercontent.com/8164505/27790216-2d4d5448-6022-11e7-8f30-b6340ecc106f.jpg)

像这张图，其中
gaosen地址是notifications@github.com 
0x5e/youku_speed_up是youku_speed_up@noreply.github.com 
唐门很太是我的邮箱
mention是mention@noreply.github.com 

我直接回复只发送给了gaosen，然后去github看了下并没有回复到issue里面
接着我试着“全部回复”

发至了gaosen和0x5e/youku_speed_up
抄送了mention
可是issue里面依然没有回复...

这是咋回事啊？难道是邮箱限制？不支持qq邮箱回复吗

**Comment by tiexo** [comment]
就是这种

![default](https://user-images.githubusercontent.com/8164505/27790364-b9eaacd4-6022-11e7-96c3-2f0455b2fd46.PNG)

**Comment by lizongzeshunshun** [comment]
没怎么使用过这个功能

@redapple0204 用过，他应该会知道

我自己测试下

**Comment by redapple0204** [comment]
@tiexo 请稍等到明天，谢谢。因为明天我们还有考试.....

**Comment by tiexo** [comment]
@lizongzeshunshun @redapple0204 好的，两位加油，祝旗开得胜。

**Comment by redapple0204** [comment]
@tiexo 哈哈哈谢谢了

**Comment by redapple0204** [comment]
@tiexo 其实的话是这样的：
首先我先收到你的回复，会发到邮箱里
![qq 20170704182136](https://user-images.githubusercontent.com/16254644/27826459-a3810196-60e5-11e7-9e2a-ceee7b5616fa.png)
然后直接回复不就好了？
![qq 20170704182153](https://user-images.githubusercontent.com/16254644/27826472-b043f168-60e5-11e7-8475-b4f92278e3ba.png)

**Comment by redapple0204** [comment]
这是一个测试

2017-07-03 20:14 GMT+08:00 唐门很太 <notifications@github.com>:

**Comment by tiexo** [comment]
我可能懂了...
用网页版qq邮箱，直接回复会发送失败，提示地址有误
用第三方邮箱管理app发送，可以成功，但是不会回复到issue里面，也就是说回复地址不同

正常应该是回复到

"b0wman"<reply+007c9499380e49449f0c376ca9a142def2e2c016e6e4f77992cf0000000115732e5b92a169ce0e503d3c@reply.github.com>;

这个地址qq邮箱不支持，而第三方app直接回复是发送到了

b0wman <notifications@github.com>

看来要换个邮箱来试试

**Comment by redapple0204** [comment]
@tiexo 没错，qq邮箱回复一些境外邮件经常会失败.....

**Comment by tiexo** [comment]
测试
 ------------------
来自 魅族 PRO 6 Plus


------------------ Original ------------------

**Comment by tiexo** [comment]
@redapple0204  嗯，测试确实是这样，我用腾讯企业邮箱回复成功了。
以后应该就好了，多谢配合啦。
