### ISSUE TITLE
计划有变。。。

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#258]
@lizongzeshunshun 我们下学期竟然要换班主任。。也就意味着组长不会马上换掉（至少要到第一次月考，也就是开学第二周以后才换掉），所以说这个暑假我还是用qq跟你交流好了。。。毕竟虽然github聊起天来看起来很舒服但是不适合当即时工具来用。

**Comment by lizongzeshunshun** [comment]
@redapple0204 好的
