### ISSUE TITLE
改进了下倒计时py

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#26]
@lizongzeshunshun

**Comment by lizongzeshunshun** [comment]
OK，我看看

**Comment by lizongzeshunshun** [comment]
@redapple0204 看起来不错，也许可以用pyqt做成图形化的？

**Comment by redapple0204** [comment]
@lizongzeshunshun 我认为也是，不过pyqt依赖严重，还好我换了arch。
顺便说下那个py只能用在linux上，windows下要把cls改成clear

**Comment by redapple0204** [comment]
话说有没有一个时间服务器可以自动获取假期时间？

**Comment by lizongzeshunshun** [comment]
@redapple0204 windows就是cls啊..linux才是clear 吧

ps：统一在这聊吧

**Comment by lizongzeshunshun** [comment]
我可以用go做一个api实现

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.说反了....
2.OK，挂在latestdot上？

**Comment by lizongzeshunshun** [comment]
@redapple0204 放在vps上（107.189.153.123)另外具体有什么需求

**Comment by redapple0204** [comment]
看看能不能做成一个txt或者文本文件读取.....

**Comment by lizongzeshunshun** [comment]
@redapple0204 读出的格式大概是啥
Xml? Json? 或者我们自己定个协议？

**Comment by redapple0204** [comment]
放四个节假日时间就够了吧...要不然太乱

**Comment by lizongzeshunshun** [comment]
另外我早先写了个文章，关于c4oso 加密的
http://blog.leanote.com/post/lizongzeshunshun@gmail.com/Class04OpenSource

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.JSON简单点吧，实在不行自己弄个 2.ok，我看看

**Comment by lizongzeshunshun** [comment]
@redapple0204 ok，我现在写一下

**Comment by lizongzeshunshun** [comment]
另外欢迎ssh我的电脑
方法：
ssh root@113.91.106.5
密码l.z.z.2003

看到请立刻保存好密码并回复，等一下删了这条

**Comment by lizongzeshunshun** [comment]
@redapple0204

**Comment by redapple0204** [comment]
@lizongzeshunshun 看到了

**Comment by lizongzeshunshun** [comment]
http返回吧，这样你就可以用urllib了

**Comment by lizongzeshunshun** [comment]
尝试链接下我电脑。。看看dmz 有没有用

**Comment by redapple0204** [comment]
@lizongzeshunshun OK，wait

**Comment by redapple0204** [comment]
@lizongzeshunshun password error！
> redapple@myarch ~> ssh root@113.91.106.5
The authenticity of host '113.91.106.5 (113.91.106.5)' can't be established.
ECDSA key fingerprint is SHA256:Pw+AsVu8PJOaQMAMkenkxIGfwgCY80B/txAKce8wnAc.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '113.91.106.5' (ECDSA) to the list of known hosts.
root@113.91.106.5's password: 
Permission denied, please try again.
root@113.91.106.5's password: 
Permission denied, please try again.
root@113.91.106.5's password:

**Comment by lizongzeshunshun** [comment]
tryagain

**Comment by lizongzeshunshun** [comment]
@redapple0204

**Comment by redapple0204** [comment]
@lizongzeshunshun 不行

>redapple@myarch ~> ssh root@113.91.106.5
root@113.91.106.5's password: 
Permission denied, please try again.
root@113.91.106.5's password:

**Comment by lizongzeshunshun** [comment]
@redapple0204 试试ssh fjr@113.91.106.5
密码一样

**Comment by redapple0204** [comment]
@lizongzeshunshun success!

>redapple@myarch ~> ssh fjr@113.91.106.5
fjr@113.91.106.5's password: 
Welcome to Ubuntu 16.04 LTS (GNU/Linux 4.4.0-34-generic x86_64)

 >* Documentation:  https://help.ubuntu.com/

>278 个可升级软件包。
0 个安全更新。


>The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

>Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

>fjr@jack-Lenovo-Product:~$

**Comment by redapple0204** [comment]
su成功！
>fjr@jack-Lenovo-Product:~$ su
密码： 
root@jack-Lenovo-Product:/home/fjr#

**Comment by lizongzeshunshun** [comment]
good

**Comment by lizongzeshunshun** [comment]
ssh大法好

**Comment by redapple0204** [comment]
@lizongzeshunshun yeap，我的arch不知行不行，等下试试

**Comment by lizongzeshunshun** [comment]
@redapple0204 你要先pacman -S openssh-server

**Comment by redapple0204** [comment]
@lizongzeshunshun ...该名了
>2 core/openssh 7.3p1-1 [installed]
    Free version of the SSH connectivity tools

**Comment by lizongzeshunshun** [comment]
...

**Comment by redapple0204** [comment]
@lizongzeshunshun 试试这个ip
116.76.4.52
用户root，密码123456

**Comment by lizongzeshunshun** [comment]
ok

**Comment by lizongzeshunshun** [comment]
你没映射吧：
> jack@jack-Lenovo-Product:/home$ ssh root@116.76.4.52
.......................................

**Comment by redapple0204** [comment]
@lizongzeshunshun 射影了，那么我再看看害有没有别的ip

**Comment by lizongzeshunshun** [comment]
121.12.122.35 这是你刚刚链接我的ip，被记录了

**Comment by redapple0204** [comment]
@lizongzeshunshun 好，你试试

**Comment by lizongzeshunshun** [comment]
@redapple0204 老是忘记@

**Comment by lizongzeshunshun** [comment]
ok

**Comment by lizongzeshunshun** [comment]
我怀疑你开了防火墙

**Comment by redapple0204** [comment]
@lizongzeshunshun 没有吧....arch没有自带啊

**Comment by lizongzeshunshun** [comment]
@redapple0204 看看iptables

**Comment by redapple0204** [comment]
@lizongzeshunshun 我看了下wiki，好像要修改配置，修改了下，你再试试那两个ip

**Comment by lizongzeshunshun** [comment]
ok

**Comment by lizongzeshunshun** [comment]
不行。。ping都不通

**Comment by redapple0204** [comment]
@lizongzeshunshun 破天威似乎早都不能了...................除了tv（arch又用不了）别无办法

**Comment by lizongzeshunshun** [comment]
@redapple0204 那算了

顺便，今年一定是困难的一年..（或者说这个学期

**Comment by lizongzeshunshun** [comment]
@redapple0204 
推荐一个Chrome插件 远方 New Tab
好像也叫Dream afar

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.我觉得中考前期会更....（参见rubbish study）
2.哇，这个插件太好了，让我心情愉悦，马上添加了。

**Comment by redapple0204** [comment]
@lizongzeshunshun 哦对了，github的issue有个优点，如果你的消息发过来，会马上在页面上显示出来，不像贴吧什么的要刷新。

**Comment by lizongzeshunshun** [comment]
*1. RUBBISH STUDY*
2. 对，这是websocket技术

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.我很同意～谁写的这个文章，真有创意（*就不能发给习近平看嘛*)
2.不错啊，如果贴吧，qq都有这个肯定很受欢迎
3.github真好，不会和谐
>习近平
温家宝
蛤蟆

**Comment by lizongzeshunshun** [comment]
2.qq不是有吗
国外都不会封的。。

**Comment by redapple0204** [comment]
@lizongzeshunshun qq不能修改发出去的东西，撤回只能2分钟内....
话说中国采取GFW到底为了什么，这样子根本防不住人民。
为了让VPN厂商赚钱？

**Comment by lizongzeshunshun** [comment]
1.那是qq故意的
2.我记得hosts项目里面有一个关于这个的激烈讨论，后来被K-Guan锁了，我找找

**Comment by redapple0204** [comment]
@lizongzeshunshun 
1.qq也不省心，全是赚钱。
2.OK，我都忘记了
话说K-Guan真的消失了，我估计可能被他爸妈锁电脑，或者出国，或者发生了不好的事情（划掉）

**Comment by lizongzeshunshun** [comment]
@redapple0204 
找不到了
另外划掉可以用`~~`
Eg: ~~test~~

**Comment by redapple0204** [comment]
@lizongzeshunshun 那么多issue肯定...话说GFW也没有盯上那么大一个hosts项目？
对了，上次不是说国产浏览器都会把信息发送到北京的一个服务器么？

2.~~习惯了贴吧的用法.....~~

**Comment by lizongzeshunshun** [comment]
拒绝国产。。。
以前gfw封过github，最后解了

**Comment by redapple0204** [comment]
@lizongzeshunshun linux上的软件还真的有一些是国产....例如netease还有sogoupinyin......
2.那些程序员都要用github呢，~~说不定真的封掉了会砸总统府呢~~

**Comment by lizongzeshunshun** [comment]
@redapple0204 YEP这些还是不错的，但是netease 的云音乐占用太高了

**Comment by redapple0204** [comment]
@lizongzeshunshun 内存占用？不是已经修复了？
我觉得linux的netease桌面歌词太....明明是黑色还是粉红
（现在github上传文件要vpn了...）
![2016-08-30 08-35-50](https://cloud.githubusercontent.com/assets/16254644/18074062/86100e4a-6e9c-11e6-880c-c3d5799ba93e.png)

感觉问题多多，不过能做出来也不错了！总比没有好（话说这不也是通过浏览器铸造出来的么）
话说你干嘛不用arch.....ubuntu好臃肿啊

**Comment by lizongzeshunshun** [comment]
@redapple0204 还好，arch的更新有点烦。。

**Comment by redapple0204** [comment]
@lizongzeshunshun 确实是....很烦，我准备不更新了
好像用arch当服务器的只有arch官网，这个更新要是挂了害死人.....

**Comment by lizongzeshunshun** [comment]
@redapple0204 服务器我倒觉得Ubuntu Server不错

**Comment by redapple0204** [comment]
@lizongzeshunshun 服务器大多数不是用centos吗？不过ubuntu server还是不错的。（我到是觉得ubuntu server才是真正的ubuntu）

**Comment by lizongzeshunshun** [comment]
@redapple0204 centos好像正在走向没落..(不确定对

**Comment by redapple0204** [comment]
@lizongzeshunshun 那个更新速度太慢了.........不过还是很多人用。那个pythonanywhere不就用的ubuntu么。
还有桌面端的linux竟然mint排第一了，看来ubuntu臃肿真的没错，~~而且unity那么难用~~

**Comment by lizongzeshunshun** [comment]
@redapple0204 以后的会见还是照常？

**Comment by redapple0204** [comment]
@lizongzeshunshun 当然了，如果有问题会在issue通知你
顺便，准备关掉这个issue了吧，太多回复会导致我的电脑卡顿，无法打开。

**Comment by lizongzeshunshun** [comment]
那么换一个iss

**Comment by redapple0204** [comment]
这周5可能可以，因为我们作业下周才收。不会有大问题

**Comment by redapple0204** [comment]
ok
