### ISSUE TITLE
是否考虑强行清理Commits历史

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#260]
@redapple0204 

鉴于最近审查力度的不断加强，可能危及我们安全。

目前项目内的敏感信息已经清理完毕，但是每一次更改均被Github记录并存储，是否考虑重置.git文件夹以清除全部提交历史？

**Comment by redapple0204** [comment]
我在考虑能不能删掉某些铭敏感的commits，因为有些commits我还是要看看的。

**Comment by lizongzeshunshun** [comment]
好像可以

**Comment by redapple0204** [comment]
我记得git命令版本可以，要不你试试？。。

**Comment by lizongzeshunshun** [comment]
如何操作

**Comment by redapple0204** [comment]
git reset ?

**Comment by redapple0204** [comment]
https://segmentfault.com/q/1010000002898735

**Comment by redapple0204** [comment]
貌似有个更好的办法

**Comment by redapple0204** [comment]
https://www.youtube.com/watch?v=B5Ss4xNYWDY
