### ISSUE TITLE
深圳的两位小伙伴你们好啊

### ISSUE THREAD

**Issue by Archeb** [redapple0204/my-boring-python#262]
![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png) 看你们用Issues聊的这么欢乐我也忍不住来open一个

**Comment by redapple0204** [comment]
哈哈哈
我issue都没来得及清理呢![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png)

**Comment by Archeb** [comment]
用Gayhub聊天这主意真是有毒 你们没qq或者tg的么![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png)

**Comment by lizongzeshunshun** [comment]
![image](https://user-images.githubusercontent.com/10304206/28247140-78e1e8e8-6a5d-11e7-94cb-273545c79187.png)搞事搞事

**Comment by Archeb** [comment]
![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png) 太有毒了 这tm还是即时通信啊

**Comment by redapple0204** [comment]
![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png) @Archeb 现在不是qq了啊

**Comment by redapple0204** [comment]
对啊

**Comment by Archeb** [comment]
![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png) 那telegram呢

**Comment by redapple0204** [comment]
不喜欢![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png)

**Comment by redapple0204** [comment]
下次我要用私人库聊天了![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png)

**Comment by Archeb** [comment]
### 自带Markdown的IM 有点6 但是手机怎么样

**Comment by Archeb** [comment]
![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png)

**Comment by redapple0204** [comment]
手机有手机界面啊

**Comment by Archeb** [comment]
![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png) 两位是今年新初三么

**Comment by redapple0204** [comment]
你猜猜![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png)

**Comment by Archeb** [comment]
![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png) 各种考试和体育中考的消息我在1越的issue看到过 所以要么新高一要么新初三

**Comment by redapple0204** [comment]
![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png) 显而易见的啦

**Comment by Archeb** [comment]
![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png) 并不 所以到底是哪个

**Comment by redapple0204** [comment]
![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png) 这都看不出？？？

**Comment by Archeb** [comment]
![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png) 看不出 我猜高一

**Comment by redapple0204** [comment]
![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png) ![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png)![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png)![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png)![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png)![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png)![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png)![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png)![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png)![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png)

明白了么？

**Comment by Archeb** [comment]
![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png) 那看来我猜对了

**Comment by redapple0204** [comment]
猜对了我为什么会如此的得意洋洋的呢
![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png)

**Comment by Archeb** [comment]
![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png) 你们真™无聊

**Comment by Archeb** [comment]
![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png) 我溜了

**Comment by redapple0204** [comment]
那是钦定的
![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png)

**Comment by Archeb** [comment]
![](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png)
