### ISSUE TITLE
谷歌翻译笑死人了！

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#29]
@lizongzeshunshun 
垃圾研究（EN）

我一直认为，

高中招生考试，

或高考，

什么是它们之间不同的科举考试，

它只是变成八股文进入中国，数学，英语，历史，地理，生物，政治，化学和物理学。

它只是变成武术科举考试进入体检。

中国，一直是，

“如果你不学习很努力了你不会得到一个美好的生活。”

现在的大学生都覆盖全中国，研究学生也是在我们身边。

我不喜欢中国的教育。

中国的研究，为自己，为很多钱。

但外国人学习（事业不是全部）是发现，发现什么，我们不知道。

这就是差。

我们是国家的花朵。

然而，我们对在年初书的海洋淹没。

我有一个姐姐，她immigranted到foregin。我askd她的朋友，

我说：“那你在学校做什么？”

“我们有更多的练习时间超过图书阅读时间”，她回答说。

他们的研究还活着，

但我们的，已经死了。

为什么出来的研究是死了吗？

我们起床，每天早上去上学比太阳更早。

而且回来以后比太阳在晚上。

晚，

始终晚上，

总是暗黄色路灯。

什么？

哪里是中午？你askd我。

*在中午时分，我们踏上在阳光下黄泉路。*

这是夏天。

TODO：这里很多内容现在都没有翻译。

但是我们呢？

累了，累了，无法入睡，甚至超过7个小时！

家庭作业 ？是的，每个老师总是认为他们没有给学生很多的功课。

但，

俗话说，

“很多一点点做一个小数怕长计”！

如果每一个教师，

给2页的作业给学生。

一点功课，是吗？

但是，我们有九门学科！

并且有在每一个页面的15个问题。

因此，2页有30个问题。

270问题与九门学科。

什么？

我们还需要每天做考试。

和记笔记的类。

这意味着我们需要采取泛每天超过400次。

所以，请老师不要说“早睡晚上”了。

我们希望更早睡觉，太。

但时间是休息和你在一起！

好吧，让我们谈谈大考。

首先，它destory家庭。

而且它的可损害儿童的心脏魔鬼！

这也是恶人让学生DIE！

即使他们不知道如果他们通过与否，死吧。

未通过，死吧。

压力过大，死吧。

死

死

死

为什么

为什么

为什么

我们研究，研究了9年，12年，只是试卷，为MARK，FOR PRIDE。

青年时代是在纸上。

时间是在纸上。

随着一切在纸上。

这是中国。

自由！

自由！

自由！

这就是我们爱

从两名学生在github上，@ redapple0204＆@lizongzeshunshun

**Comment by lizongzeshunshun** [comment]
@redapple0204 你试试百度就知道什么叫6了

**Comment by redapple0204** [comment]
@lizongzeshunshun 哈哈哈更好笑了
垃圾研究（中文）
我总是认为，
高中入学考试，
或高考，
他们和科举考试的区别是什么，
它只将八篇文章转化为语文、数学、英语、历史、地理、生物、政治、化学和物理。
它只是把武术帝国考试变成物理考试。
中国，一直是，
“如果你不努力学习，你就不会得到一个好的生活。”
现在的大学生都覆盖了中国所有的，而且研究的学生也都在我们身边。
我不喜欢中国的教育。
中国的学习，为自己，为很多钱。
但外国人的学习（原因不是全部）是发现，发现我们不知道。
这是不同的。
我们是国家的花朵。
然而，我们被淹没在一开始的书的海洋。
我有一个姐姐，她immigranted到国外。我问她的朋友，
我说：“你在学校做了什么？”
“我们有更多的练习时间比书阅读时间”，回答她说。
他们的研究还活着，
但我们的，是死了。
为什么学习是死的？
我们每天早上起床，比太阳早一天去上学。
和回来比太阳在晚上。
晚上，
永远的夜，
总是暗黄的路灯。
什么？
中午在哪里？你问我。
中午，我们踏上了太阳的死亡之路。
这是夏天。
待办事项：这里的很多内容没有翻译。
但我们呢？
累了，累了，睡不着7个多小时！
家庭作业吗？是的，每一个老师总是认为他们不给学生很多作业。
但，
俗话说，
“积少成多！”
如果每一个老师，
给学生做2页作业。
小家庭作业，是吗？
但我们有九个科目！
每一页都有15个问题。
所以2页有30个问题。
和270个问题九个科目。
什么？
我们也需要每天做考试。
在课堂里做笔记。
这意味着我们需要每天400次以上的锅。
所以请老师不要说“晚上睡得早”了。
我们也要早点睡觉。
但时间是休息与你！
好吧，让我们谈谈大考试。
首先，它破坏家庭。
它是可以伤害孩子们的心的恶魔！
这也是邪恶的人使学生死亡！！
即使他们不知道他们是否通过或不去，去死。
不通过，去死。
压力太大，去死。
死
死
死
为什么
为什么
为什么
我们研究，研究了9年，12年，只是为一个考试文件，为马克，为自豪。
青春是在纸上。
时间在那纸。
在那纸上的一切。
这是中国人。
自由！
自由！
自由！
这是我们所爱的
从GitHub上的两个学生，@ @ lizongzeshunshun redapple0204 &

**Comment by lizongzeshunshun** [comment]
@redapple0204 2fix

**Comment by lizongzeshunshun** [comment]
https://github.com/redapple0204/my-boring-python/commit/f976996cfcc3764610b07ba7eada99e1643e50f6

**Comment by lizongzeshunshun** [comment]
205503f

**Comment by redapple0204** [comment]
@lizongzeshunshun ok！

**Comment by redapple0204** [comment]
@lizongzeshunshun 还有mac！

**Comment by lizongzeshunshun** [comment]
@redapple0204 mac is Linux

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.ok
2.bug：
>距离暑假结束只剩下
23:39:21.859045
距离16年中秋节还有
15 days, 9:39:21.859045
距离16年国庆还有
31 days, 9:39:21.859045
距离17年元旦还有
123 days, 9:39:21.859045
Traceback (most recent call last):
  File "test1.py", line 21, in <module>
    os.system('clear')
AttributeError: 'str' object has no attribute 'system'

**Comment by lizongzeshunshun** [comment]
@redapple0204 wait

**Comment by lizongzeshunshun** [comment]
变量名取错了，代替os了

**Comment by lizongzeshunshun** [comment]
@redapple0204 
https://github.com/redapple0204/my-boring-python/commit/74bf86d31c16578c4d7286b3f297b696ba60fba3

**Comment by redapple0204** [comment]
@lizongzeshunshun ok

**Comment by redapple0204** [comment]
@lizongzeshunshun 0.5间隔太长，导致卡顿，不好看，还是回复0.05吧

**Comment by lizongzeshunshun** [comment]
@redapple0204 ok

**Comment by redapple0204** [comment]
@lizongzeshunshun freebsd好像没加上....不知道要不要。cygwin呢？

**Comment by lizongzeshunshun** [comment]
@redapple0204 
https://github.com/redapple0204/my-boring-python/commit/89bf502898b6a7b5c284ec97cf63d1eb31891552

fb很少人用吧。。

**Comment by lizongzeshunshun** [comment]
https://github.com/redapple0204/my-boring-python/commit/5cb91cae83cb52dd91bda83d6f384cc6c486137d

这个就相当于全部了

**Comment by redapple0204** [comment]
@lizongzeshunshun ok，谢了。
话说能不能不要这样控制时间，感觉这样很麻烦
这样行么
例如我想要停顿0.5秒，就python3 xxx.py -5
不加参数默认0.05

**Comment by lizongzeshunshun** [comment]
ok

**Comment by redapple0204** [comment]
上次用过这个函数....脑抽忘记了

**Comment by lizongzeshunshun** [comment]
@redapple0204 
https://github.com/redapple0204/my-boring-python/commit/6fb0b7062e32a595500f7b01b232d45568e41f1d

**Comment by redapple0204** [comment]
@lizongzeshunshun 好的，thx，我试试

**Comment by redapple0204** [comment]
@lizongzeshunshun bug！
>  File "test1.py", line 5, in <module>
    if len(os.Args) == 2:
AttributeError: module 'os' has no attribute 'Args'

**Comment by lizongzeshunshun** [comment]
@redapple0204 习惯golang 了，稍后

**Comment by lizongzeshunshun** [comment]
@redapple0204 
https://github.com/redapple0204/my-boring-python/commit/689d83424f0c56fcf591f2800fd8fe50cb653d56

**Comment by redapple0204** [comment]
@lizongzeshunshun 还是有bug啊.......
>Traceback (most recent call last):
  File "test1.py", line 10, in <module>
    print('Sleep time: ' + 0.05 + 's')
TypeError: Can't convert 'float' object to str implicitly

顺便，我把arch GUIDE直接做成一个文档算了

**Comment by lizongzeshunshun** [comment]
@redapple0204 我去，闹抽了

**Comment by redapple0204** [comment]
@lizongzeshunshun ...好吧

**Comment by lizongzeshunshun** [comment]
@redapple0204 
https://github.com/redapple0204/my-boring-python/commit/fdfbcf8beed32c95b7e2335ff840815d66009f0d

**Comment by redapple0204** [comment]
@lizongzeshunshun thx，顺便，讨论以下，你觉得那个提示是要每次都有还是第一次提示以后取消比较好？

**Comment by lizongzeshunshun** [comment]
@redapple0204 哪个提示

**Comment by redapple0204** [comment]
@lizongzeshunshun 
>You can use time.py <sleep_time> to set sleep time.

**Comment by lizongzeshunshun** [comment]
@redapple0204 那要配置文件，太麻烦了，还是就这样吧

**Comment by redapple0204** [comment]
@lizongzeshunshun 没错，我也嫌麻烦了.....

**Comment by lizongzeshunshun** [comment]
@redapple0204 。。

**Comment by redapple0204** [comment]
@lizongzeshunshun 现在怎么那么多网站部支持linux....还得我要用user agent

**Comment by lizongzeshunshun** [comment]
@redapple0204 哪些

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.腾讯视频等
2.我有改了下英文版讨厌学习，原来那个“中午踏上黄泉路”实在是太....

**Comment by lizongzeshunshun** [comment]
@redapple0204 他的原文其实表达的差不多是这个意思，
另外，你可以翻译一下TODO部分的。。

**Comment by redapple0204** [comment]
@lizongzeshunshun OK

**Comment by lizongzeshunshun** [comment]
。。。。。换一下iss
