### ISSUE TITLE
请问wget没法下载github的东西吗？

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#3]
@K-Guan ？

**Comment by K-Guan** [comment]
怎么不行？

**Comment by redapple0204** [comment]
@K-Guan 他说host not fing

**Comment by K-Guan** [comment]
@redapple0204 网络是否连接正常？链接是否正确？

**Comment by redapple0204** [comment]
@K-Guan 都是正常，只不过wget是wibdows单文件命令行的

**Comment by K-Guan** [comment]
@redapple0204 完整的错误报告是什么？

**Comment by redapple0204** [comment]
@K-Guan 大概是这样的 ple0204/my-boring-python.git
--14:50:03--  ftp://https:21/%2Fgithub.com/redapple0204/my-boring-python.git
           => `my-boring-python.git'
Connecting to https:21...
https: Host not found

**Comment by K-Guan** [comment]
1. `wget` 默认只是发送一个GET请求，并将获取到的内容保存下来。其可以获取到的内容与浏览器正常访问无二。而你的这个网址到像是git链接，你是想用 `git clone`？

2. 这哪们子网址？`ftp://https:21/%2Fgithub.com/`？到底是`ftp://`还是`https://`？那个`21/%2F`又是什么？

**Comment by K-Guan** [comment]
![screenshot from 2016-02-06 15-04-59](https://cloud.githubusercontent.com/assets/13862535/12865314/840500d4-cce3-11e5-9ea1-8eb514fafb84.png)

**Comment by redapple0204** [comment]
@K-Guan 那么请问如果要获取您的hosts要怎么做呢？

**Comment by K-Guan** [comment]
1. hosts又不是我的，一般是说racaljk hosts。
2. 这个页面：https://github.com/racaljk/hosts/blob/master/hosts，右边的[**RAW**按钮](https://raw.githubusercontent.com/racaljk/hosts/master/hosts)，用`wget`下载这个网址。

**Comment by redapple0204** [comment]
@K-Guan  还是不行啊

**Comment by K-Guan** [comment]
嗯？错误是什么？

**Comment by redapple0204** [comment]
@K-Guan --16:49:17--  ftp://https:21/%2Fraw.githubusercontent.com/racaljk/hosts/master/h
osts
           => `hosts'
Connecting to https:21...
https: Host not found

**Comment by K-Guan** [comment]
你的这个网址到底哪门子网址？试试：

    wget https://raw.githubusercontent.com/racaljk/hosts/master/hosts

**Comment by redapple0204** [comment]
@K-Guan 就是这样的啊C:\Documents and Settings\Administrator\桌面\hosts>wget https://raw.githubuserco
ntent.com/racaljk/hosts/master/hosts
--17:14:07--  ftp://https:21/%2Fraw.githubusercontent.com/racaljk/hosts/master/h
osts
           => `hosts'
Connecting to https:21...
https: Host not found

C:\Documents and Settings\Administrator\桌面\hosts>

**Comment by K-Guan** [comment]
@redapple0204 Err...你的 `wget` 绝对有问题……

**Comment by redapple0204** [comment]
@K-Guan 补过可以wget百度哦

**Comment by K-Guan** [comment]
建议：Google下“GNU wget for Windows”，换个版本用。

**Comment by redapple0204** [comment]
@K-Guan 好的，我试试看，谢谢了
