### ISSUE TITLE
继续！

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#31]
@redapple0204

**Comment by redapple0204** [comment]
ok！

**Comment by redapple0204** [comment]
有没有需要兼容py2，因为有一些发行版+mac只有自带2.x

**Comment by lizongzeshunshun** [comment]
@redapple0204 
这个可以。。稍后

**Comment by lizongzeshunshun** [comment]
@redapple0204 OK

**Comment by redapple0204** [comment]
@lizongzeshunshun OK，thx。我明天把vim配置也发上去得了

**Comment by redapple0204** [comment]
@lizongzeshunshun 忘记了，我的破天威不能上传文件到github，f**k

**Comment by lizongzeshunshun** [comment]
@redapple0204 online?

**Comment by redapple0204** [comment]
@lizongzeshunshun yeap

**Comment by lizongzeshunshun** [comment]
@redapple0204 ok

**Comment by lizongzeshunshun** [comment]
@redapple0204 还有什么要改进的？

**Comment by redapple0204** [comment]
@lizongzeshunshun 目前应该没有了.....

**Comment by redapple0204** [comment]
@lizongzeshunshun 我要把一些杂物&私人物品清理出去，反正也没用了

**Comment by lizongzeshunshun** [comment]
@redapple0204 ok 我正在把你的arch向导改成md的

**Comment by redapple0204** [comment]
@lizongzeshunshun ok，thx！

**Comment by redapple0204** [comment]
@lizongzeshunshun 我该了下成绩查询，原来那个不忍直视......

**Comment by lizongzeshunshun** [comment]
@redapple0204 是，到处import

**Comment by redapple0204** [comment]
@lizongzeshunshun 原来那个时候都不知道import作用....顺便我还更改了下readme.md，加入了vim的向导

**Comment by lizongzeshunshun** [comment]
@redapple0204 ok

**Comment by redapple0204** [comment]
@lizongzeshunshun 顺便，我更改了“自杀”的英文

**Comment by lizongzeshunshun** [comment]
@redapple0204 ok

**Comment by lizongzeshunshun** [comment]
@redapple0204 还没玩程

**Comment by lizongzeshunshun** [comment]
@redapple0204 你先看看

**Comment by redapple0204** [comment]
@lizongzeshunshun OK，THX，我看看

**Comment by redapple0204** [comment]
@lizongzeshunshun 不错，不过那个贴吧的链接有点问题，我更改了下

**Comment by lizongzeshunshun** [comment]
@redapple0204 没错，原本上面的也有问题

**Comment by redapple0204** [comment]
@lizongzeshunshun 设置语言那里有点乱，我改下

**Comment by lizongzeshunshun** [comment]
@redapple0204 ok

**Comment by redapple0204** [comment]
@lizongzeshunshun  ok

**Comment by lizongzeshunshun** [comment]
@redapple0204 还有什么东西要完善的吗

**Comment by lizongzeshunshun** [comment]
@redapple0204 我准备写一个FQ全指南

**Comment by redapple0204** [comment]
@lizongzeshunshun 里面有些错了，例如wine不是开启testing，是muilt

**Comment by redapple0204** [comment]
OK

**Comment by redapple0204** [comment]
@lizongzeshunshun 似乎我的电脑马上要炸了.......
![2016-08-31 09-42-08](https://cloud.githubusercontent.com/assets/16254644/18113038/4ac7efce-6f5f-11e6-87fc-a3079057b7f9.png)
cpu的响声掩盖了音乐的声音。

**Comment by lizongzeshunshun** [comment]
@redapple0204 刚刚出去了以下

**Comment by redapple0204** [comment]
@lizongzeshunshun 哦？

**Comment by redapple0204** [comment]
@lizongzeshunshun 下午就要报道了.................................................................................................................................................................................................................................................................................

**Comment by lizongzeshunshun** [comment]
@redapple0204 。。。

**Comment by redapple0204** [comment]
@lizongzeshunshun ..................
>距离暑假结束只剩下
3:24:15.573228
距离16年中秋节还有
14 days, 13:39:15.573228
距离16年国庆还有
30 days, 13:39:15.573228
距离17年元旦还有
122 days, 13:39:15.573228

看看哪能不能加这个功能：检测暑假时间小于1day就在旁边提示：暑假即将结束
还有2天到假期就提示：yes！，马上可以放假了
但是有个问题，这个是有英文的（day），没办法直接加减，也不能直接计算

**Comment by redapple0204** [comment]
等等！这个时间计算逻辑有问题！中秋节是15号，应该还有15天半，怎么只剩下14天了？

**Comment by lizongzeshunshun** [comment]
我看看

**Comment by lizongzeshunshun** [comment]
奇怪

**Comment by redapple0204** [comment]
@lizongzeshunshun 这个逻辑好奇怪.....好像...有没有分大小月，还是只是全部月数默认30days？

**Comment by lizongzeshunshun** [comment]
@redapple0204 不知道，但是sql的是分了的

**Comment by redapple0204** [comment]
i@lizongzeshunshun 我想一下，20160915-20160831在怎么样都不可能是14啊。
顺便，你把时间调到14：01分，会发现很神奇的事情
>距离暑假结束只剩下
-1 day, 23:17:28.908142
距离16年中秋节还有
14 days, 13:32:28.908142
距离16年国庆还有
30 days, 13:32:28.908142
距离17年元旦还有
122 days, 13:32:28.908142

所以：时间逻辑有问题！

**Comment by lizongzeshunshun** [comment]
@redapple0204 。。。。。。。。。。。。。。。。。。。。。。。。。。

**Comment by redapple0204** [comment]
怎么变成了-2天了......，这个怎么计算的

**Comment by lizongzeshunshun** [comment]
@redapple0204 看看py的wiki

**Comment by redapple0204** [comment]
@lizongzeshunshun 

好像time不能这样写.......

**Comment by redapple0204** [comment]
@lizongzeshunshun 
用这个？
>datetime.datetime(2005, 2, 16)

**Comment by redapple0204** [comment]
strptime是什么鬼？

**Comment by redapple0204** [comment]
@lizongzeshunshun 似乎字符有问题...难道是py2函数？
>Traceback (most recent call last):
  File "test.py", line 5, in <module>
    b = datetime.datetime('2016-08-31  14:00:00', '%Y-%m-%d %H:%M:%S')
TypeError: an integer is required (got type str)

**Comment by lizongzeshunshun** [comment]
@redapple0204 他说他要数字，你给了他字符串

**Comment by redapple0204** [comment]
@lizongzeshunshun 我把它直接丢到py3里，结果输出了这个鬼东西
>datetime.datetime(2005, 2, 12, 0, 0)
似乎不能用这个

**Comment by lizongzeshunshun** [comment]
@redapple0204 http://blog.chinaunix.net/uid-200142-id-3494741.html

**Comment by redapple0204** [comment]
@lizongzeshunshun 我看得那一个文章是2005年的了.....肯定是py2函数

**Comment by lizongzeshunshun** [comment]
@redapple0204 查查文档

**Comment by lizongzeshunshun** [comment]
https://docs.python.org/3/library/datetime.html

**Comment by redapple0204** [comment]
@lizongzeshunshun 正在看....

**Comment by redapple0204** [comment]
@lizongzeshunshun 看，第五条
>的字符串表示timedelta的对象也同样归其内部表示。这导致负timedeltas有点不寻常的结果。例如：

>>>
>>> timedelta （小时= - 5 ）
datetime.timedelta（-1，68400）
>>> 印刷（_ ）
-1天，十九点00分00秒

**Comment by lizongzeshunshun** [comment]
@redapple0204 对

**Comment by redapple0204** [comment]
@lizongzeshunshun 所以说....这是个bug？

**Comment by lizongzeshunshun** [comment]
@redapple0204 自己写个算法解决？

**Comment by redapple0204** [comment]
@lizongzeshunshun 自己的算法......可能也会bu吧.刚刚用我的windows bat试了下还是会

**Comment by lizongzeshunshun** [comment]
@redapple0204 我写一下，你先不要改，不然会冲突

**Comment by redapple0204** [comment]
@lizongzeshunshun ok
