### ISSUE TITLE
看

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#32]
@redapple0204 
https://github.com/redapple0204/my-boring-python/commit/09b9ea4822fd56112f149cca0b79b5eab908ecc3

**Comment by lizongzeshunshun** [comment]
https://github.com/redapple0204/my-boring-python/commit/de6e43273cc1d21ae474e1494c21b86b7cfd2438

**Comment by redapple0204** [comment]
@lizongzeshunshun 这个....只显示天数不太好吧....而且那个bug还是没有修复
>


距离暑假结束只剩下
0
距离16年中秋节还有
14(no repair)
距离16年国庆还有
30
距离17年元旦还有
122

**Comment by lizongzeshunshun** [comment]
@redapple0204 。。。

**Comment by redapple0204** [comment]
@lizongzeshunshun .....github的合并按钮好奇怪

**Comment by lizongzeshunshun** [comment]
@redapple0204 Merge?

**Comment by lizongzeshunshun** [comment]
@redapple0204 79commits 了，好快

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.yeap
2.那当然，忘记我们聊天总共几十上百万字了吗
ps：暑假倒计时进入1小时！
![2016-08-31 11-45-22](https://cloud.githubusercontent.com/assets/16254644/18115248/74276938-6f70-11e6-8c5f-5e07b7bd229d.png)
~~还好下午不用交作业~~

**Comment by lizongzeshunshun** [comment]
@redapple0204 ............

**Comment by redapple0204** [comment]
@lizongzeshunshun 如果前面多一个45days我会高兴地发疯....

**Comment by redapple0204** [comment]
@lizongzeshunshun arch也是龟速....终端无法打开的bug暑假刚开始就有了，现在还没有修复

**Comment by lizongzeshunshun** [comment]
@redapple0204 ..

**Comment by redapple0204** [comment]
@lizongzeshunshun 我感觉刚刚发完这个帖子..........
http://tieba.baidu.com/p/4680398462?pid=94237764969&cid=0#94237764969

**Comment by lizongzeshunshun** [comment]
@redapple0204 .........................

**Comment by redapple0204** [comment]
@lizongzeshunshun 无聊写了下本项目的wiki

**Comment by lizongzeshunshun** [comment]
@redapple0204 ok

**Comment by redapple0204** [comment]
@lizongzeshunshun OK，下午去报道了，你们也去了吗？

**Comment by lizongzeshunshun** [comment]
@redapple0204 前天就报了，明天正是上学

**Comment by redapple0204** [comment]
@lizongzeshunshun 我竟然没发现......其实晚一点报道也不是很好，早一点至少可以休息一下.......
晚上好想没什么事情要做....听歌好了
（netease大法好

**Comment by redapple0204** [comment]
@lizongzeshunshun 话说我还是想办法把vim配置上传上来，要怎么做呢？
ps：网上的教程竟然....全部是windows的
