### ISSUE TITLE
现在电脑课

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#34]
@redapple0204 
666，装了chrome
![image](https://cloud.githubusercontent.com/assets/10304206/18154452/477ccbe0-7037-11e6-9b1e-e684af912ad8.png)

**Comment by redapple0204** [comment]
.......XP.....你们电脑课真好，我们都不给网络

**Comment by lizongzeshunshun** [comment]
@redapple0204 我可能会时不时留些日记在这个库

**Comment by redapple0204** [comment]
@lizongzeshunshun OK

**Comment by redapple0204** [comment]
@lizongzeshunshun 怀念下当时的star只有2个...fork只有一个的一个无人问津的小小项目...

**Comment by lizongzeshunshun** [comment]
。。。
