### ISSUE TITLE
changing to windows

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#36]
@redapple0204 
换系统强迫症。。

**Comment by redapple0204** [comment]
@lizongzeshunshun 好吧.....并不是所有人能适应Linux，反正我做到了.....
话说关于那个时间.py的话，原来的算法是没有错误的，我脑抽算错了.....
so，现在要怎么办？

**Comment by lizongzeshunshun** [comment]
@redapple0204

我还是想重新实现一下。说实话，原先的代码有点.....

将要改进

* 节日和日期放文件
* 如果节日多可以考虑使用sqlite
* 至少要array放节日日期
* 除此之外，我想做个golang实现
* 显示代码重构

**Comment by lizongzeshunshun** [comment]
最近有点忙，正在计划ETransV2。

流传输确实有点麻烦

**Comment by redapple0204** [comment]
@lizongzeshunshun 关于第一个.....这样做会不会有点太庞大了？弄的有点像真正的一个程序了
2.传输.....是挺麻烦的

**Comment by lizongzeshunshun** [comment]
@redapple0204
那就不用sqlite了

**Comment by redapple0204** [comment]
@lizongzeshunshun 关于节日的问题，是要保持原先的离线功能（优点：用户可能不需要节假日的时间，例如计算别的日期的时间）还是在线获取节假日时间？（优点：用户不用自己调整时间）

**Comment by lizongzeshunshun** [comment]
@redapple0204 可以设置

**Comment by redapple0204** [comment]
@lizongzeshunshun []联网获取信息
