### ISSUE TITLE
ETransV2服务端编译成功

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#38]
![image](https://cloud.githubusercontent.com/assets/10304206/18222956/cb6c4252-71d9-11e6-8117-5bfabdafa326.png)

**Comment by lizongzeshunshun** [comment]
@redapple0204

**Comment by redapple0204** [comment]
@lizongzeshunshun OK，祝贺你，thx

**Comment by lizongzeshunshun** [comment]
@redapple0204 thx 客户端编写中

**Comment by redapple0204** [comment]
@lizongzeshunshun 是否有服务器？

**Comment by lizongzeshunshun** [comment]
@redapple0204 yes

**Comment by lizongzeshunshun** [comment]
@redapple0204 ready to compile

**Comment by redapple0204** [comment]
@lizongzeshunshun ok，祝你早日成功！

**Comment by lizongzeshunshun** [comment]
@redapple0204 ok,but something's wrong

```
d:\gowsp\src\ETransV2\client>client 127.0.0.1:9876 1.txt
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x401082]

goroutine 1 [running]:
panic(0x4e51a0, 0xc042004090)
        D:/ProgrammingLanguage/go/src/runtime/panic.go:500 +0x1af
main.checkError(0x0, 0x0)
        D:/gowsp/src/ETransV2/client/client.go:11 +0x42
main.connectToServer(0xc04204e3c0, 0xe, 0x0, 0xc042020101)
        D:/gowsp/src/ETransV2/client/client.go:22 +0x81
main.main()
        D:/gowsp/src/ETransV2/client/client.go:43 +0x5e
```

**Comment by redapple0204** [comment]
@lizongzeshunshun 内存寻址错误？

**Comment by lizongzeshunshun** [comment]
@redapple0204 好像是

**Comment by lizongzeshunshun** [comment]
@redapple0204 也许问题出在服务端上

**Comment by lizongzeshunshun** [comment]
@redapple0204 果然
fixed

**Comment by redapple0204** [comment]
@lizongzeshunshun 祝贺！

**Comment by lizongzeshunshun** [comment]
@redapple0204 传输测试成功！！

**Comment by redapple0204** [comment]
@lizongzeshunshun 太棒了！！！！！！！！！！！！！！！！！

**Comment by redapple0204** [comment]
@lizongzeshunshun 协议是？

**Comment by lizongzeshunshun** [comment]
@redapple0204 tcp

**Comment by redapple0204** [comment]
@lizongzeshunshun tcp......应该还好，不会老是断线吧

**Comment by lizongzeshunshun** [comment]
@redapple0204 等下，我改一些细节的bugs

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.ok
2.UDP打洞.....

**Comment by lizongzeshunshun** [comment]
@redapple0204 wait.. retesting

**Comment by redapple0204** [comment]
@lizongzeshunshun OK。。。。

**Comment by lizongzeshunshun** [comment]
@redapple0204 测试结束，所有bug均解决，准备上传

**Comment by lizongzeshunshun** [comment]
@redapple0204 现在做一下大文件传输

**Comment by lizongzeshunshun** [comment]
@redapple0204 Excellent!!!
传输arch镜像(750MB)最高内存占用仅2.5MB，局域网内传输速度达80Mbps(9M/s)

**Comment by redapple0204** [comment]
@lizongzeshunshun 祝贺！！太好了！！（你的内网速度好快，我才1m）

**Comment by lizongzeshunshun** [comment]
@redapple0204 go真好用。。

**Comment by redapple0204** [comment]
@lizongzeshunshun yeap...

**Comment by lizongzeshunshun** [comment]
@redapple0204 等会上传。我们来试一试

**Comment by lizongzeshunshun** [comment]
@redapple0204 wait

**Comment by lizongzeshunshun** [comment]
@redapple0204 也许你要自己编译一下。。

**Comment by redapple0204** [comment]
@lizongzeshunshun OK

**Comment by lizongzeshunshun** [comment]
@redapple0204 首先安装golang （具体arch我不知道，百度一下）
然后vim client.go 内容如下：

```
package main

import (
	"bufio"
	"log"
	"net"
	"os"
)

func checkError(err error) {
	if err != nil {
		log.Fatalln("[FATAL]", err) // will exit when Error happended
	}
}

func checkArgs() {
	if len(os.Args) != 3 {
		log.Fatalln("[FATAL] Usage:", os.Args[0], "<server-ip:port>", "<filepath>")
	}
}

func sendFile(c net.Conn, filepth string) {
	f, err := os.Open(filepth)
	checkError(err)
	defer f.Close()
	buf := make([]byte, 1024)
	bfRd := bufio.NewReader(f)
	for {
		n, err := bfRd.Read(buf)
		if err != nil {
			break // break when finish reading
		}
		c.Write(buf[:n])
	}
}

func main() {
	checkArgs()
	conn, err := net.Dial("tcp", os.Args[1]) //connect to server
	checkError(err)
	log.Println("[INFO] Successfully connected to server")
	defer conn.Close() // finally close the connection
	sendFile(conn, os.Args[2])
	log.Println("[INFO] Successfully send file")
}
```

然后go build client.go
然后 client 113.91.107.241:9876 <你要发的文件>

**Comment by redapple0204** [comment]
@lizongzeshunshun 百度说sudo pacmna -S go，但是找不到....而且yaourt go出现了很多没用的东西
> blackarch/python2-grandalf 0.555-1
    Graph and drawing algorithms framework.
380 blackarch/python2-py-bcrypt 0.4-1
    An implementation of the OpenBSD Blowfish password hashing algorithm
381 blackarch/python2-pydes 2.0.1-1
    Pure python implementation of DES and TRIPLE DES encryption algorithm.
382 blackarch/python2-pygoogle 0.6-1
    This module lets you search the Google search engine programmatically.
383 blackarch/python2-pygoogle-simple 0.2.3-1
    Search in google by AJAX Google API.
384 blackarch/python2-re2 0.2.22-1
    Python wrapper for Google's RE2 using Cython.
385 blackarch/python2-xgoogle 20.3db20fb-1
    Python library to Google services (google search, google sets, google 
    translate, sponsored links).
386 blackarch/python2-yaraprocessor 1.1.0-1
    Scan data streams with Yara using various algorithms.
387 blackarch/quickrecon 0.3.2-1 (blackarch blackarch-recon blackarch-scanner)

**Comment by lizongzeshunshun** [comment]
@redapple0204 

download this
http://www.golangtc.com/static/go/1.7/go1.7.linux-amd64.tar.gz

**Comment by lizongzeshunshun** [comment]
![image](https://cloud.githubusercontent.com/assets/10304206/18223560/89c83f04-71ed-11e6-9738-657eb0079626.png)

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.似乎还是不行....用我笔记本win吧
2.不错，恩漂亮
