### ISSUE TITLE
请问我能不能用您的hosts制作一个windows下获取hosts的工具

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#4]
@K-Guan

**Comment by redapple0204** [comment]
@K-Guan 就像这样 http://pan.baidu.com/s/1c1eBy3u

**Comment by redapple0204** [comment]
@K-Guan 原文
欢迎使用hosts FQ工具
主程序[By Redapple0204] 下载模块Easy_Download-V0.1[By LZZ]
主程序编程语言[BAT] Easy_Download下载模块编程语言[Golang]
在这里感谢所有制作hosts的人员 racaljk andytimes K-Guan smounives aofall davymai
等
---------------------------------------
显示简介请按1
手动更新请按2
开始替换FQ请按3(推荐)
把更新hosts添加进path请按4 (此项为高级用户选择)
---------------------------------------
按完后请Enter确定 :

**Comment by K-Guan** [comment]
自然随意。如果自认为不错的话可以在我们的项目那边打开一个 issue 或 pull request ，讨论将此工具加入 Host Tools 方便他人使用。

**Comment by redapple0204** [comment]
@K-Guan 好的，等下我去开一个

**Comment by redapple0204** [comment]
@K-Guan 请问这是啥意思 
你要先fork本repo，然后加上你的下载，然后Pull requests到本repo的master branch。
@redapple0204

**Comment by redapple0204** [comment]
@K-Guan 请问这样子行不行

**Comment by redapple0204** [comment]
@K-Guan 请问怎么开rp

**Comment by redapple0204** [comment]
@K-Guan 你要在这个repo里开PR……不是你fork的那个           请问如何在这个repo里开PR

**Comment by redapple0204** [comment]
@K-Guan 感谢您啊，我们的hosts工具终于添加进去了

**Comment by K-Guan** [comment]
哎，你的代码感谢我干嘛呀？稍等，我一会有空着，去更新下 README ，以及删除原本的那个 bat 。

**Comment by redapple0204** [comment]
@K-Guan 好的
