### ISSUE TITLE
@redapple0204

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#40]
@redapple0204 
![image](https://cloud.githubusercontent.com/assets/10304206/18229142/6b175830-729f-11e6-914a-1f449a309ab6.png)

**Comment by redapple0204** [comment]
@lizongzeshunshun OK，成功！

**Comment by lizongzeshunshun** [comment]
@redapple0204 yes

**Comment by redapple0204** [comment]
还有，这种文件名很难分清楚格式，建议自动加上后缀

**Comment by lizongzeshunshun** [comment]
@redapple0204 现在正在改

**Comment by redapple0204** [comment]
@lizongzeshunshun OK。thx

**Comment by lizongzeshunshun** [comment]
@redapple0204 wait

**Comment by lizongzeshunshun** [comment]
@redapple0204 这是个难题

**Comment by redapple0204** [comment]
@lizongzeshunshun why？只能时间轴？

**Comment by lizongzeshunshun** [comment]
@redapple0204 差不多了，试验了30min

**Comment by lizongzeshunshun** [comment]
![image](https://cloud.githubusercontent.com/assets/10304206/18229274/5fb014e0-72a5-11e6-9c73-d3465586cf43.png)

**Comment by redapple0204** [comment]
@lizongzeshunshun OK，祝贺

**Comment by lizongzeshunshun** [comment]
@redapple0204 稍后

**Comment by lizongzeshunshun** [comment]
@redapple0204 Finally solved.

可以有名字、大小了

**Comment by redapple0204** [comment]
@lizongzeshunshun OK，祝贺。

**Comment by lizongzeshunshun** [comment]
@redapple0204 thx

**Comment by lizongzeshunshun** [comment]
我试一下大文件

**Comment by redapple0204** [comment]
@lizongzeshunshun OK

**Comment by lizongzeshunshun** [comment]
26S 1G

**Comment by redapple0204** [comment]
@lizongzeshunshun 不错！

**Comment by redapple0204** [comment]
@lizongzeshunshun 我去，push错了....

**Comment by redapple0204** [comment]
@lizongzeshunshun 搞定了，终于学会push了

**Comment by lizongzeshunshun** [comment]
@redapple0204 
下一步

[ ] 服务端上传+下载

**Comment by redapple0204** [comment]
@lizongzeshunshun OK，话说....我还以为做到了呢

**Comment by redapple0204** [comment]
@lizongzeshunshun 顺便.....怎么编译go，我想编译下这个
https://github.com/loadfield/go-music
