### ISSUE TITLE
something's wrong

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#41]
怎么commits变7了，以前好多commits都变成first commit了
@redapple0204

**Comment by lizongzeshunshun** [comment]
@redapple0204 另外Win10在某些方面确实比Ubuntu1604厉害
比如u2b，Ubuntu一个视频下来丢失帧大概1%，W10才0.4%不到

**Comment by lizongzeshunshun** [comment]
也许是Ubuntu没装显卡驱动的原因

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.first_commits 是我push的备注.....
2.maybe吧，显卡驱动有时候很坑，**特别是a卡**arch驱动找的累死了。

**Comment by redapple0204** [comment]
@lizongzeshunshun 我刚刚看了下高一的数学书，发现了竟然要学BASIC语言......
整整一个单元if,end if,PRINT................................

**Comment by lizongzeshunshun** [comment]
@redapple0204 。。准备写一个东西
*Out of the Rainbow*

**Comment by lizongzeshunshun** [comment]
现在大概的定位是散文...

**Comment by redapple0204** [comment]
@lizongzeshunshun ok.....你就那么喜欢写东西？

**Comment by lizongzeshunshun** [comment]
@redapple0204 
这个.....个人性格吧。。
另外那个commit真的很奇怪，以前都有90+commits的

**Comment by lizongzeshunshun** [comment]
@redapple0204 另外我还加了个ETransV3(HTTP VERSION)

**Comment by redapple0204** [comment]
@lizongzeshunshun 好吧....散文我真的写不出。
难道是因为昨天我push的时候一不小心选择了整个桌面上传？
或者是我选择标语的时候填写了"first_commits"?
 
OK，http不是容易劫持么？

**Comment by lizongzeshunshun** [comment]
@redapple0204 会写一个auth验证模块
2.怀疑github出了bug, 或者你push的时候不小心加错了参数？

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.ok
2.用的是git or什么的 +master

**Comment by redapple0204** [comment]
@lizongzeshunshun 
参照的[这个](http://blog.csdn.net/steven6977/article/details/10567719)
最后push上去有变动，用的是
>git push origin +master

**Comment by lizongzeshunshun** [comment]
@redapple0204 我的流程一般是

```
git add -A
git commit -m "sth"
git push
```

**Comment by lizongzeshunshun** [comment]
@redapple0204 
pull一般是
```
git fetch
git merge
```

当然有时候图方便直接git pull

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.我不是很会push....
2.我喜欢用git add .
另外直接push似乎有错误.......

**Comment by lizongzeshunshun** [comment]
@redapple0204 git add . **只会添加增加的内容，不会添加减少（删除）的内容**，以前被坑过

**Comment by redapple0204** [comment]
@lizongzeshunshun 也就是说只会上传新的东西而不是全部上传？
那我只添加东西的时候就add . 好了，要不然全部上传慢死了。

**Comment by redapple0204** [comment]
话说github的lfs你听说过么

**Comment by lizongzeshunshun** [comment]
@redapple0204 what？

**Comment by lizongzeshunshun** [comment]
this?

lfs （Linux From Scratch项目简称）

**Comment by redapple0204** [comment]
@lizongzeshunshun https://git-lfs.github.com/

**Comment by lizongzeshunshun** [comment]
@redapple0204 let me see

**Comment by lizongzeshunshun** [comment]
what?

**Git Large File Storage Is Written in Go**

**Comment by redapple0204** [comment]
@lizongzeshunshun OK,如果真的好用可以把github当作一个临时网盘了

**Comment by redapple0204** [comment]
大文件上传（>100m)

**Comment by lizongzeshunshun** [comment]
**免费用户的Git LFS有限额，文件储存限制在1GB，每月带宽流量1GB。用户可付费增加储存空间和流量。**(From ***Zhihu***)

**Comment by lizongzeshunshun** [comment]
@redapple0204 忘记@

**Comment by redapple0204** [comment]
@lizongzeshunshun 这个呢？
https://help.github.com/articles/what-is-my-disk-quota/
ps：我是“楼主”不用@也行。你watch了，所以不用@也行。

**Comment by lizongzeshunshun** [comment]
> **We recommend repositories be kept under 1GB each. This limit is easy to stay within if large files are kept out of the repository. If your repository exceeds 1GB, you might receive a polite email from GitHub Support requesting that you reduce the size of the repository to bring it back down.**

> **In addition, we place a strict limit of files exceeding 100 MB in size. For more information, see "Working with large files."**

**Comment by lizongzeshunshun** [comment]
@redapple0204 i'll have a try

**Comment by redapple0204** [comment]
另外：好像百度有很多“偏方”上传大文件
https://www.baidu.com/s?wd=github%E5%A4%A7%E6%96%87%E4%BB%B6&f=12&rsp=0&oq=githubdawenjian&tn=site888_3_pg&ie=utf-8&rsv_pq=eb9f1f6e00025ab4&rsv_t=ac0754VmfN3rwjcdeDjMtNNVOnswm8x8tjZghR4j%2Fg3VxFMcV2AC%2F7RIBU62ZSjuEJXa&rqlang=cn

典型的：
http://blog.csdn.net/davion_zhang/article/details/46411849

**Comment by redapple0204** [comment]
@lizongzeshunshun ok

**Comment by lizongzeshunshun** [comment]
@redapple0204 我觉得上传要死

**Comment by lizongzeshunshun** [comment]
@redapple0204 另外ETransV3会加一个离线下载的功能

**Comment by redapple0204** [comment]
@lizongzeshunshun 我觉得还好....比垃圾百度云好。

**Comment by lizongzeshunshun** [comment]
![image](https://cloud.githubusercontent.com/assets/10304206/18249505/4f644b30-73b1-11e6-9e73-b162c183e84f.png)

**Comment by lizongzeshunshun** [comment]
@redapple0204 似乎不@不行

**Comment by lizongzeshunshun** [comment]
@redapple0204 而且我相信离线下载下国外资源的速度肯定很爽，再加一个kcptun。。。。。

**Comment by lizongzeshunshun** [comment]
@redapple0204 因为服务器放国外，只有硬盘的问题了

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.肯定了
2.我喜欢用github放文件是因为github有外链，而且是可变动的.....七牛不可更改很讨厌
