### ISSUE TITLE
Git Large File Storage

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#42]
@redapple0204 试了一下，感觉很好用

**Comment by redapple0204** [comment]
@lizongzeshunshun 看了看只有1G还是放弃了.....毕竟我上传的大文件都是要大于1G（系统备份，大约10G）
看来只能windows下分part，大约有几百个几十M的，不过没所谓，直接push上来，git clone下来.....

**Comment by lizongzeshunshun** [comment]
@redapple0204 nope，我自己搭git

**Comment by lizongzeshunshun** [comment]
@redapple0204 gitlab大法，不过现在没服务器

**Comment by redapple0204** [comment]
@lizongzeshunshun 诶，你不是有服务器么？

**Comment by lizongzeshunshun** [comment]
@redapple0204 256RAM我想还是算了，要搞个至少1G的

**Comment by lizongzeshunshun** [comment]
@redapple0204 新建了个分支filesshare，测试lfs
试试下载：https://github.com/redapple0204/my-boring-python/blob/filesshare/server/server.exe?raw=true

**Comment by redapple0204** [comment]
@lizongzeshunshun 成功下载！

**Comment by lizongzeshunshun** [comment]
@redapple0204 ok
