### ISSUE TITLE
讨论下：制作windows pe算是编程么？

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#43]
@lizongzeshunshun 今天有一个人和我讨论pe是不是编程。虽说从直觉上感觉肯定不是。但是仔细回想了下，觉得好像也很有道理：把原始pe加上那么多组建，改了那么多注册表等等......所以，你认为怎么样呢？

**Comment by lizongzeshunshun** [comment]
@redapple0204 where, 贴吧？

**Comment by lizongzeshunshun** [comment]
@redapple0204 另外，我觉得不算
```
编程是编写程序的中文简称，就是让计算机为解决某个问题而**使用某种程序设计语言编写程序代码**，并最终得到相应结果的过程。
```

**Comment by lizongzeshunshun** [comment]
使用某种程序设计语言编写程序代码..

**Comment by redapple0204** [comment]
@lizongzeshunshun not，3B科技。
不过还真的修改了很多东西哦，说不定还真的修改了代码

**Comment by lizongzeshunshun** [comment]
@redapple0204 问题是他肯定是按教程改的。如果他真的自己改，他一定会**完全**掌握一种语言，比如cpp，另外，我不认为bat是编程

**Comment by redapple0204** [comment]
@lizongzeshunshun 自己改也有可能.....毕竟网上的方案连网络支持都没有，不过值得肯定的是***他肯定是用GUI或者bat改得***
另外，bat是脚本语言**通常被认为是一种简化的脚本语言**
所以说....还是编程语言咯。

**Comment by lizongzeshunshun** [comment]
@redapple0204 win不开源，这是关键。。

**Comment by lizongzeshunshun** [comment]
@redapple0204 另外你可以叫他把所有操作告诉你

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.说的好！！！！重点啊
2.我们指的是***所有市面上的***pe，不是***单个人***的

**Comment by lizongzeshunshun** [comment]
@redapple0204 ?

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.你说windows不是开源的说的很正确
2.说的是市面上的pe（例如微pe）的做法

**Comment by lizongzeshunshun** [comment]
@redapple0204 let me see

**Comment by lizongzeshunshun** [comment]
@redapple0204 
看了下，不复杂

1. 看起来太简单了[1]
2. 不算复杂[2]

[1]: http://bbs.kafan.cn/thread-994560-1-1.html
[2]: http://jingyan.baidu.com/article/c74d60005f066d0f6b595d7b.html

**Comment by redapple0204** [comment]
@lizongzeshunshun 这个....我都说了网上的pe都没有添加网络&很好支持的驱动
我也不知道他们是哪里找的教程，~~万一真的自己做的呢~~......
