### ISSUE TITLE
话说github的表情到底是抄袭QQ还是QQ抄袭github......

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#44]
@lizongzeshunshun  for example :smirk:
[this](http://www.webpagefx.com/tools/emoji-cheat-sheet/)

**Comment by lizongzeshunshun** [comment]
emjoy是通用表情，不存在抄袭

**Comment by redapple0204** [comment]
@lizongzeshunshun 你确定qq有按照协议？......

**Comment by redapple0204** [comment]
@lizongzeshunshun 另外arch更新的我要吐了.....每更新一次都会出现问题，现在wine更新qq很卡，libreoffice更新打开有几率卡死......
内核什么我都把他列入禁止更新，一更新就无法打开虚拟机....
字体也是，一更新就不要想看了........
上次我弟玩的supertux更新了有几率闪退.......

**Comment by lizongzeshunshun** [comment]
@redapple0204 peng

**Comment by lizongzeshunshun** [comment]
@redapple0204 emjoy开源

**Comment by lizongzeshunshun** [comment]
@redapple0204 建议看一下这个视频：http://www.bilibili.com/video/av5950231/

**让我看到了中国真真正正的黑暗面**

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.b站不支持chrome？windows也无法播放
![2016-09-09 18-42-01](https://cloud.githubusercontent.com/assets/16254644/18384484/56b171ce-76bd-11e6-8f4e-e13b698c0401.png)
2.百度了，找到这个。是这个么？
![2016-09-09 18-42-48](https://cloud.githubusercontent.com/assets/16254644/18384518/89d30fe0-76bd-11e6-89f2-6528af469eda.png)
3.我去看看
wtf？？？戒网瘾？等我看完.......
另外我认为网瘾不是病，自己去看看linus少年时期......

**Comment by redapple0204** [comment]
肯定有各大国家领导人包屁，但是最近媒体曝光，也没办法了......

**Comment by redapple0204** [comment]
另外，建议看看这个
[fuck](https://www.zhihu.com/question/24183980)

**Comment by redapple0204** [comment]
另外，中国的这种政治制度也是.....哎。py交易一大堆
例如最简单的，习近平贪污等
[xjp](http://www.rfa.org/mandarin/pinglun/wangdan/wangdan-01292014093510.html)

**Comment by redapple0204** [comment]
每天上网超过5.7小时是上瘾？暑假我很多时间都是.....
@K-Guan 还每天15小时呢。
~~话说......它那么就没有上网，不会真的被送到那里了吧。~~

**Comment by lizongzeshunshun** [comment]
@redapple0204 Yep.

另外，改了一下Chrome的渲染，好看多了

**Comment by lizongzeshunshun** [comment]
![image](https://cloud.githubusercontent.com/assets/10304206/18384874/b1a44c44-76bf-11e6-8329-5a99231acda2.png)
个人觉得好看多了

**Comment by lizongzeshunshun** [comment]
![image](https://cloud.githubusercontent.com/assets/10304206/18384886/d6a5633e-76bf-11e6-8ab5-b1b6b27e9747.png)
To
![image](https://cloud.githubusercontent.com/assets/10304206/18384897/e1809d50-76bf-11e6-992a-8f94a309226b.png)

**Comment by lizongzeshunshun** [comment]
@redapple0204

**Comment by redapple0204** [comment]
@lizongzeshunshun 怎么弄的，不错嘛......比我的好看多了。
话说你是不用多了ubuntu，然后习惯任务栏放到左边？

**Comment by lizongzeshunshun** [comment]
@redapple0204 
1. Chrome插件: Stylish
![image](https://cloud.githubusercontent.com/assets/10304206/18384979/5589391e-76c0-11e6-9296-599805ff5fcf.png)

2. 没错

**Comment by redapple0204** [comment]
@lizongzeshunshun 不错，等下我看看
2.我很不喜欢ubuntu的.......

**Comment by lizongzeshunshun** [comment]
@redapple0204 in fact, 这个插件很好用， 还可以自己改，我现在改成全粗体了

**Comment by lizongzeshunshun** [comment]
![image](https://cloud.githubusercontent.com/assets/10304206/18385061/d3a586cc-76c0-11e6-880f-7bd725272009.png)

**Comment by redapple0204** [comment]
@lizongzeshunshun 恩........虽然我不是很喜欢粗体（黏在一起了）
还是宋体好一点

**Comment by lizongzeshunshun** [comment]
@redapple0204 css随便调

**Comment by redapple0204** [comment]
@lizongzeshunshun 恩...........

**Comment by lizongzeshunshun** [comment]
@redapple0204 ...

**Comment by lizongzeshunshun** [comment]
@redapple0204 can you use TV?

**Comment by redapple0204** [comment]
@lizongzeshunshun yes。但是......现在上传速度不知道怎么搞的，突然下降到10k/s，导致远程操控.......鼠标动一下有好几秒的延迟。

**Comment by redapple0204** [comment]
我觉得真的很奇怪，每一次上传文件以后速度会下降很多，要一周多恢复正常.....

**Comment by lizongzeshunshun** [comment]
@redapple0204 难到是天威限制？

**Comment by lizongzeshunshun** [comment]
@redapple0204 你们今天考了吗

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.我觉得不现实吧.....难道路由器经不起那么大的上传?
2.数学？

**Comment by lizongzeshunshun** [comment]
@redapple0204 开学考

**Comment by redapple0204** [comment]
@lizongzeshunshun 反正也没什么用......于是学校决定不考了。

**Comment by lizongzeshunshun** [comment]
@redapple0204 今天我数学神TM发挥

**Comment by redapple0204** [comment]
上学期做了一些题目，但是没有改，现在直接不考了.....因为还要买题目

**Comment by redapple0204** [comment]
怎么？

**Comment by lizongzeshunshun** [comment]
@redapple0204 第一次做数学做到最后一分钟。。。

**Comment by redapple0204** [comment]
@lizongzeshunshun 一节课？正常.......我们老师还要晚来。

**Comment by redapple0204** [comment]
考到半中间要发火...........

**Comment by lizongzeshunshun** [comment]
@redapple0204 不不不，开学考90分钟
不过幸运的是，压轴题成功了！

**Comment by redapple0204** [comment]
@lizongzeshunshun 你们.....今天开学考试？
祝贺！，上学期的东西感觉好简单........

**Comment by lizongzeshunshun** [comment]
@redapple0204 1. 是
2. 感谢，

**Comment by redapple0204** [comment]
basic语言我用不惯........

**Comment by lizongzeshunshun** [comment]
@redapple0204 
我也是，还记得大概6岁的时候编c#，现在想起来也是6

**Comment by redapple0204** [comment]
@lizongzeshunshun 6岁.......当时我什么都不会，我的电脑生涯是从15年暑假开始的......

**Comment by lizongzeshunshun** [comment]
@redapple0204 。。

**Comment by lizongzeshunshun** [comment]
@redapple0204 online?

**Comment by redapple0204** [comment]
@lizongzeshunshun yes

**Comment by lizongzeshunshun** [comment]
@redapple0204 ..下雨

**Comment by redapple0204** [comment]
@lizongzeshunshun 是啊.....好大。

**Comment by lizongzeshunshun** [comment]
@redapple0204 我觉得学习一下scala

**Comment by lizongzeshunshun** [comment]
听说难度堪比C++

**Comment by redapple0204** [comment]
@lizongzeshunshun 基于java我都不是很喜欢......因为框架很烦。

**Comment by redapple0204** [comment]
我决定坚持python......，linux自带，不用麻烦配置

**Comment by lizongzeshunshun** [comment]
@redapple0204 不是基于JAVA，基于JVM

**Comment by redapple0204** [comment]
@lizongzeshunshun 打错了.......

**Comment by lizongzeshunshun** [comment]
@redapple0204 python语法漂亮，但是效率啊（运行效率。。。。

**Comment by lizongzeshunshun** [comment]
有人说C#是设计最佳语言。。

**Comment by redapple0204** [comment]
@lizongzeshunshun 确实.....不过现在也不是写什么大程序也不需要运行效率.....
那个[feeluown](https://github.com/cosven/FeelUOwn)不是好好地么

c#......好吧，许多linux商软件（特别是deepin）都用c#

**Comment by lizongzeshunshun** [comment]
@redapple0204 我现在主线依然是Go；
因为多线程.

**Comment by redapple0204** [comment]
@lizongzeshunshun go的话......写大了会boom。

**Comment by lizongzeshunshun** [comment]
@redapple0204 go就是用来大项目的
https://github.com/gogits/gogs

**Comment by lizongzeshunshun** [comment]
这就是go写的。。

**Comment by redapple0204** [comment]
@lizongzeshunshun 奇怪......有时候跨平台有很多奇奇怪怪的问题

**Comment by lizongzeshunshun** [comment]
@redapple0204 跨平台。。
反正我的ETransV2完美跨

**Comment by lizongzeshunshun** [comment]
话说v3正在计划。。

**Comment by lizongzeshunshun** [comment]
但是没时间

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.小项目当然可以.....
2.确实，初二以后基本没时间了。
