### ISSUE TITLE
pac好方便

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#46]
自动识别要不要fq。。

**Comment by lizongzeshunshun** [comment]
话说u2b的曲线好奇怪 

![image](https://cloud.githubusercontent.com/assets/10304206/18414750/920eed86-7808-11e6-80c7-d8451a6ffb43.png)

**Comment by lizongzeshunshun** [comment]
我认为我们需要这个：

![image](https://cloud.githubusercontent.com/assets/10304206/18414822/68566de0-780b-11e6-9d39-5ad3c457b222.png)

**Comment by lizongzeshunshun** [comment]
@redapple0204

**Comment by redapple0204** [comment]
@lizongzeshunshun 真是666。
