### ISSUE TITLE
我们有网盘了

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#47]
@redapple0204 

地址: http://lizongzeshunshun-ktest.daoapp.io/

用户名: neteroster
密码: 20030506

离线下载请点左上角“文件”，选择OcDownload

感谢daocloud。（本系统由daocloud提供docker容器）
感谢 https://github.com/imdjh/owncloud-with-ocdownloader （提供镜像）

本网盘系统很完善，还有可以桌面同步。

另外我试了一下：
离线下载有5M/s哦
网盘下载速度大概1M/s

上传较大文件也是没问题的

这就是我们以后的网盘了。。

**Comment by lizongzeshunshun** [comment]
顺便，还可以共享

**Comment by lizongzeshunshun** [comment]
另外，空间无限

**Comment by lizongzeshunshun** [comment]
同步盘的下载在
https://owncloud.org/install/
的2

**Comment by lizongzeshunshun** [comment]
# Pay Attention

**请勿存储重要文件，因为数据随时会丢失（例如容器重启）**

**Comment by lizongzeshunshun** [comment]
![image](https://cloud.githubusercontent.com/assets/10304206/18469664/9b068e56-79db-11e6-8585-a4b1c6ad0988.png)

**Comment by lizongzeshunshun** [comment]
等等~！空间有限，6.4G

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.thx，看起来小文件都可以放上去了~
2.反正我也用不了那么多.......上传过大的文件会让我上传速度boom！

**Comment by redapple0204** [comment]
诶，你的服务器卡住了？卡在这里。
![2016-09-15 07 01 58](https://cloud.githubusercontent.com/assets/16254644/18532990/56852462-7b12-11e6-801d-5cd6d9153cbb.png)

**Comment by redapple0204** [comment]
当我没说.....刷新就好了

**Comment by lizongzeshunshun** [comment]
@redapple0204 。。
