### ISSUE TITLE
ArchLinux Powered

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#48]
sorry, i can't da zhong wen.

archlinux takes low ram usage, great!

![2016-09-15 14-27-43](https://cloud.githubusercontent.com/assets/10304206/18540343/990b8342-7b50-11e6-814e-15714b16e88d.png)

**Comment by lizongzeshunshun** [comment]
@redapple0204

**Comment by redapple0204** [comment]
@lizongzeshunshun 参照我写的安装向导安装fcitx 100%成功！
另外......现在arch的wine版本有点问题，也不能回退，所以.....过几天再用

**Comment by redapple0204** [comment]
@lizongzeshunshun 还有，gnome的顶端字体有问题，你要回滚Cantarell字体。

**Comment by lizongzeshunshun** [comment]
已经安装powershell字体

**Comment by redapple0204** [comment]
@lizongzeshunshun powershell不是很好看。。还不如文泉译

**Comment by lizongzeshunshun** [comment]
![2016-09-15 22-21-17](https://cloud.githubusercontent.com/assets/10304206/18553363/be402766-7b92-11e6-9fb5-ee48dee06faf.png)
@redapple0204

**Comment by redapple0204** [comment]
@lizongzeshunshun 
![2016-09-15 22-28-25](https://cloud.githubusercontent.com/assets/16254644/18553640/c48595f6-7b93-11e6-9675-2c870619daba.png)
另外，你中文还是不行？
还有你gnome顶端字体还是有问题，具体看我的。

**Comment by redapple0204** [comment]
@lizongzeshunshun 另外，我建议你软件都用stable，要不会很惨......

**Comment by lizongzeshunshun** [comment]
我装了微软雅黑字体，更好看。。

**Comment by redapple0204** [comment]
@lizongzeshunshun 微软雅黑我觉得太细......

**Comment by redapple0204** [comment]
@lizongzeshunshun 另外我要准备暂时放弃arch了。。问题太多了
>wine版本有问题
netease无法播放
chrome字体很难看

**Comment by lizongzeshunshun** [comment]
@redapple0204 

pacman -S wqy-microhei

and reboot

**Comment by redapple0204** [comment]
@lizongzeshunshun 这是bug....改了字体没用
另外你还需要在gnome-tweak-tool设置

**Comment by lizongzeshunshun** [comment]
@redapple0204 ..

**Comment by lizongzeshunshun** [comment]
@redapple0204 并不需要，系统会自动fallback
