### ISSUE TITLE
github的人员介绍改版了。。

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#49]
没有以前那么难看，不信你点下我的头像。。
@lizongzeshunshun

**Comment by lizongzeshunshun** [comment]
Yes, got it in the morning

**Comment by lizongzeshunshun** [comment]
@redapple0204 

突然想开testing了。。。

**Comment by redapple0204** [comment]
@lizongzeshunshun 开了你就惨了....
上次开滚一次直接显卡驱动报废。
我还巴不得有一个stable仓库呢。

**Comment by lizongzeshunshun** [comment]
@redapple0204 ...

**Comment by redapple0204** [comment]
@lizongzeshunshun 节选贴吧
>首先解释一下, 对于[testing] 和 [community-testing], 一般软件包在里面的理由有:
1. [core]或者[extra]有重要库rebuild, 相关[community]包完成后被放到[community-staging], 然后统一移到[community-testing] (相关[core]或者[extra]的包被移到[testing]). 这个时候每个包能不能工作是没有人试过的!

>2. 一些TU维护自己并不使用的[community]包, 当包上游版本更新, 或者自己修了个bug并且自己认为"应该没问题吧", 然后因为没测试, 所以放进 [community-testing] 等到一定测试量没问题后再放进 [community]; 或者是一些DEV维护自己并不使用的[core]或者[extra], 然后...然后放进[testing]. 这个时候每个包能不能工作也是没有人试过的!

>所以作为一只TU, 我表示[testing]和[community-testing]真心只是给比较懂系统急救+英语+报bug的人用的... Arch的[testing]并不像其他发行版那样会领先"稳定"仓库多少, 因为unstable版本的软件照样在"稳定"仓库里, 通常软件在[testing]和[community-testing]不会待很久(除非有巨大的问题, 那样你也就惨了).

>所以对于新手和身边救急用具准备不足的老手, 强烈建议不要开启[testing]和[community-testing].

>(本来回复在glibc的老贴下面, 后来觉得点开还要翻一页什么的麻烦, 干脆删了开新帖嗯)

**Comment by redapple0204** [comment]
github markdown真不不好用。。不需要markdown的也划上去了

**Comment by redapple0204** [comment]
还有这个。。。
>作者：晏然FelixYan
链接：https://www.zhihu.com/question/32767874/answer/63615766
来源：知乎
著作权归作者所有，转载请联系作者获得授权。

>Arch Linux 中的 [testing]、[community-testing] 和 [multilib-testing] 三个仓库构成了 [testing] 系列仓库。由于网上许多地方对 [testing] 系列仓库存在一定的误解，我作为一只开发者，想藉此文介绍一下 [testing] 系列仓库。

>一、[testing] 系列仓库里有哪些包？
主要有三类，按照数量排序应该是：由 soname 等 TODO 产生的大批完全未经测试的包；重要软件包、软件集合的更新、不靠谱上游推出的新版本、上游大版本更新等维护者虽然测试过但是不敢肯定没问题的包；因为维护者没有时间等情况而完全未经测试的包。注意，这里多数的情况都是完全未经测试的包，keep in mind。

>二、什么情况下软件包会留在 [testing] 系列仓库里很长时间？
主要也有三类：没人测试给 signoff 的；已知有问题但还未修复或不知道怎么修复还在研究的；维护者明明拿到 signoff 了（针对目标仓库是 [core] 的情况）或明明不需要 signoff（针对所有除了 [core] 以外的仓库）但还是觉得没把握的。简单来说，一般情况下你想用的新版软件不会在 [testing] 系列仓库里停留超过一个星期，除非它已经被发现有问题了。

>三、开 [testing] 系列仓库需要满足什么条件？
对当前系统中所有重要资料的备份。因为你不知道你装的下一个未经充分测试的包里是否会出现类似之前 bumblebee 或 steam 那样的灾难性错误。
有从包括 bumblebee 在内的各种灾难中恢复的能力。几乎没有人能帮你完成这件事，所以你需要自己拥有这种能力。这里包括的不止是对修复针对性问题所需要的知识和/或找到这些知识的能力，还包括提前准备好修复工作中需要的工具，比如 USB 安装介质和你的备份。
能接受系统在一段时间内不可用。 如果你正在工作中赶进度，或者明天就需要在一场演讲中用到，这不是一个开启 [testing] 跑更新的很好时机。请保证你在满足前两个条件的情况下，还能接受你的系统需要一段时间才能修复这个事实。无论是找到问题、修复还是重装系统，还有从备份中 恢复文件，都是需要一定时间的。
最后，如果读到这里还没被我吓跑，欢迎你像我一样启用 [testing] 系列仓库，并把发现的问题报告到 Arch Linux Bug Tracker。

**Comment by lizongzeshunshun** [comment]
..

**Comment by lizongzeshunshun** [comment]
@redapple0204 
that i'd better not open it...

**Comment by lizongzeshunshun** [comment]
why i think there is few update

![2016-09-16 20-08-42](https://cloud.githubusercontent.com/assets/10304206/18585429/7066acc4-7c49-11e6-8594-b405edea8137.png)

**Comment by redapple0204** [comment]
@lizongzeshunshun 你这个出错了吧....
没有更新会提示“今日无事可做”

**Comment by lizongzeshunshun** [comment]
@redapple0204 i use yaourt instead of pacman

**Comment by redapple0204** [comment]
@lizongzeshunshun yaourt速度在我这里.....慢得像狗。
除非必要，我都是用pacman（加了archlinuxcn源，aur很多都有）

**Comment by lizongzeshunshun** [comment]
浏览器拼音打法好

![2016-09-17 19-36-06](https://cloud.githubusercontent.com/assets/10304206/18607943/011bcc30-7d0e-11e6-8269-74a71637552f.png)

**Comment by redapple0204** [comment]
@lizongzeshunshun 这是一个插件？

**Comment by lizongzeshunshun** [comment]
@redapple0204 
yes

**Comment by redapple0204** [comment]
@lizongzeshunshun 能不能跨程序运行？

**Comment by lizongzeshunshun** [comment]
＠redapple0204
NO.

BTW, i got a vps

1G RAM / 20G Storage / 4Mbps /2 Cpus 

39/month

https://cloud.anodelic.com/index.php

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.那有什么用....................................
2.咦，不错啊。也不算太贵
你找到了好的东西了....

**Comment by redapple0204** [comment]
@lizongzeshunshun 另外我觉得linux真的很省内存！
![2016-09-18 19-25-41](https://cloud.githubusercontent.com/assets/16254644/18615311/d9389f5e-7dd5-11e6-83f4-d331cf4d6dbc.png)

**Comment by redapple0204** [comment]
@lizongzeshunshun 有时说这个虚拟机的声音.....我都要笑喷了
[例如](https://pan.baidu.com/s/1kVbJVk7)

**Comment by lizongzeshunshun** [comment]
。。
come on Friday if you can
thx

**Comment by redapple0204** [comment]
@lizongzeshunshun 周五....我尽量！
如果再老师不拖堂的情况下。
时间仍然5:15-30，如果超过45没来就说明没空了。。。
有特殊情况的话最晚周四通知你。。
