### ISSUE TITLE
请问如何计算从一个时间到另外一个时间？

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#5]
@K-Guan 例如计算今天·到2月21日的时间（精确到秒）用py要怎么算呢？

**Comment by redapple0204** [comment]
@K-Guan

**Comment by redapple0204** [comment]
@K-Guan

**Comment by K-Guan** [comment]
不好意思，今天有点忙。待我研究下。

**Comment by K-Guan** [comment]
http://stackoverflow.com/questions/1345827/how-do-i-find-the-time-difference-between-two-datetime-objects-in-python

http://stackoverflow.com/questions/12126318/subtracting-dates-with-python

**Comment by redapple0204** [comment]
@K-Guan 好的，非常感谢
