### ISSUE TITLE
BaiduYun Plug is good

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#50]
In my US vps,
download the Remix OS(1.47G)

![2016-09-16 12-51-15](https://cloud.githubusercontent.com/assets/10304206/18575609/48705180-7c0c-11e6-9906-d484cea2b7f6.png)

9-10m/s

really great

**Comment by redapple0204** [comment]
@lizongzeshunshun 
1.不错嘛......可惜这个插件不维护了，估计很快就.......被封！
2.你的输入法还是没弄成功？蛋疼.......

**Comment by lizongzeshunshun** [comment]
@redapple0204 
just for imporving my English

**Comment by redapple0204** [comment]
@lizongzeshunshun 好吧。。。

**Comment by lizongzeshunshun** [comment]
@redapple0204 ..
