### ISSUE TITLE
Linux Mint Powered

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#52]
话说很好用，Chrome的输入法也不错。

![2016-09-22 18-36-31](https://cloud.githubusercontent.com/assets/10304206/18745086/82f68f68-80f3-11e6-8475-836e66a49f60.png)

**Comment by lizongzeshunshun** [comment]
以后就用这个了

**Comment by redapple0204** [comment]
@lizongzeshunshun 1...云输入法好像都不怎么好....为什么不用fcitx?
2.mint是linux发行版排行第一的,肯定做得不错
but....感觉默认字体真心难看.
3.昨天我去你那里了,等到5:45,结果你还没来就走了..

**Comment by lizongzeshunshun** [comment]
3. tuo tang da fa

Chrome is TOO SLOW that's why i'm go to firefox now.

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.真搞不懂为什么翠园很喜欢拖课，表示我们学校都没有老师会。。。。
2.firefox没有翻译.....所以我铁定chrome。
另外我觉得firefox才叫一个慢，一个网页卡阿卡啊十几秒都出不来。

**Comment by lizongzeshunshun** [comment]
@redapple0204 
I don't know the problem about Chrome.

Once I start chrome and see some pages for a time, it will OVER suddenly

(OVER means become very very slow, which status that you can't move your SHUBIAO)

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.难道你的内存太少？要知道chrome是内存杀手。
2.鼠标英文是mouse

**Comment by lizongzeshunshun** [comment]
@redapple0204 oh yes
NO, It is not about RAm

**Comment by redapple0204** [comment]
@lizongzeshunshun 好吧..........

**Comment by lizongzeshunshun** [comment]
@redapple0204 ..安装了搜狗PY输入法，真tm好用

**Comment by redapple0204** [comment]
@lizongzeshunshun 效果比win差多了。就是fcitx套一个壳.....
