### ISSUE TITLE
破解百度云已经失效

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#54]
@lizongzeshunshun 失效了.....百度真流氓

**Comment by lizongzeshunshun** [comment]
@redapple0204 
new idea

**Comment by lizongzeshunshun** [comment]
http://www.loveno.net/baiduyun/login.html

**Comment by redapple0204** [comment]
@lizongzeshunshun Thanks a lot
虽然速度还是不是顶峰（300k）
但至少比100k限速要好很多！

**Comment by lizongzeshunshun** [comment]
@redapple0204 s10 x10 k1M

**Comment by redapple0204** [comment]
@lizongzeshunshun what？

**Comment by lizongzeshunshun** [comment]
@redapple0204 
aria2c -s10 -x10 -k1M "URL"

**Comment by lizongzeshunshun** [comment]
我这边满速11MiB/s

**Comment by redapple0204** [comment]
@lizongzeshunshun 这都行？下次试试
thx了。

**Comment by lizongzeshunshun** [comment]
@redapple0204 updated
