### ISSUE TITLE
首页的标语语法有问题

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#56]
@lizongzeshunshun 
![2016-10-05 19 38 14](https://cloud.githubusercontent.com/assets/16254644/19111645/514696da-8b33-11e6-82b9-92308bfb5f8f.png)

**Comment by lizongzeshunshun** [comment]
话说这虽然是语法错了,然而我也知道,但是如果去看外国节目,很多都是这样的,似乎更符合习惯@redapple0204

**Comment by redapple0204** [comment]
@lizongzeshunshun 他们是说let‘s吧

**Comment by lizongzeshunshun** [comment]
@redapple0204 
反正Getting Start 是错不了了

**Comment by redapple0204** [comment]
@lizongzeshunshun yes

**Comment by lizongzeshunshun** [comment]
@redapple0204 ..
