### ISSUE TITLE
TODO-LIST/2016-10 ~ 2016-11

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#57]
- [x] README增加索引
- [ ] 规范文件名
- [ ] 整理文件
- [x] 发布arch安装向导3.0 beta
- [x] 添加arch安装向导markdown版本

**Comment by redapple0204** [comment]
[ ] 发布arch安装向导3.0 beta

**Comment by lizongzeshunshun** [comment]
@redapple0204 
https://www.zhihu.com/question/22093333

233

**Comment by redapple0204** [comment]
@lizongzeshunshun 
1.666666这真的是个梗
2.你希望在下一个arch安装向导中添加什么呢？
图片是肯定要的。

**Comment by redapple0204** [comment]
@lizongzeshunshun 顺便https://www.zhihu.com/question/49056249
竟然真的有人回答我无聊的问题，而且答案真的很有说服力...

**Comment by lizongzeshunshun** [comment]
...

**Comment by lizongzeshunshun** [comment]
@redapple0204 更完善的向导
