### ISSUE TITLE
话说为什么这里的输入选项输入完毕以后就没有办法开始下载

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#59]
找了好久，都要崩溃了
@lizongzeshunshun 
import os,urllib.request,re,sys,requests
print ('欢迎使用arch安装向导获取器')
resp = requests.get("https://raw.githubusercontent.com/redapple0204/my-boring-python/master/tmp/version-beta")
print('目前最新的测试版本是',resp.text)
resp1 = requests.get("https://raw.githubusercontent.com/redapple0204/my-boring-python/master/tmp/version-stable")
print('目前最新的稳定版本是',resp1.text)
print('请输入您要下载的版本（1为测试版，2为稳定版）')
print('将下载到本程序所在的目录')
shuru = input()
if(shuru == 1):
	 pwd == os.getcwd()
	 os.chdir(pwd)
	 resp2 = requests.get("https://raw.githubusercontent.com/redapple0204/my-boring-python/master/tmp/version-beta-link")

	 data = urllib.request.urlopen(resp2).read()
	 with open("arch-install-guide.doc", 'wb') as f:
	  f.write(data)

	 if(shuru == 2):
	  pwd == os.getcwd()
	  os.chdir(pwd)
	 resp2 = requests.get("https://raw.githubusercontent.com/redapple0204/my-boring-python/master/tmp/version-stable-link")

	 data = urllib.request.urlopen(resp2).read()
	 with open("arch-install-guide.doc", 'wb') as f:
	     f.write(data)

**Comment by redapple0204** [comment]
改了下，还是没法用
import os,urllib.request,re,sys,requests
print ('欢迎使用arch安装向导获取器')
resp = requests.get("https://raw.githubusercontent.com/redapple0204/my-boring-python/master/tmp/version-beta")
print('目前最新的测试版本是',resp.text)
resp1 = requests.get("https://raw.githubusercontent.com/redapple0204/my-boring-python/master/tmp/version-stable")
print('目前最新的稳定版本是',resp1.text)
print('请输入您要下载的版本（1为测试版，2为稳定版）')
print('将下载到本程序所在的目录')
shuru = input()
if(shuru == 1):
	 lujing = os.getcwd()
	 os.chdir(lujing)
	 resp2 = requests.get("https://raw.githubusercontent.com/redapple0204/my-boring-python/master/tmp/version-beta-link")
	 data = urllib.request.urlopen(resp2).read()
	 with open("arch-install-guide.doc", 'wb') as f:
	  f.write(data)

	 if(shuru == 2):
	  lujing2 = os.getcwd()
	  os.chdir(lujing2)
	 resp2 = requests.get("https://raw.githubusercontent.com/redapple0204/my-boring-python/master/tmp/version-stable-link")
	 data = urllib.request.urlopen(resp2).read()
	 with open("arch-install-guide.doc", 'wb') as f:
	     f.write(data)

**Comment by redapple0204** [comment]
我再改，又报了一个很奇怪的错
import os,urllib.request,re,sys,requests
print ('欢迎使用arch安装向导获取器')
resp = requests.get("https://raw.githubusercontent.com/redapple0204/my-boring-python/master/tmp/version-beta")
print('目前最新的测试版本是',resp.text)
resp1 = requests.get("https://raw.githubusercontent.com/redapple0204/my-boring-python/master/tmp/version-stable")
print('目前最新的稳定版本是',resp1.text)
print('请输入您要下载的版本（1为测试版，2为稳定版）')
print('将下载到本程序所在的目录')
shuru = input()
if(shuru == 1):
	 lujing = os.getcwd()
	 os.chdir(lujing)
resp = requests.get("https://raw.githubusercontent.com/redapple0204/my-boring-python/master/tmp/version-beta-link")
data = urllib.request.urlopen(resp).read()
with open("arch-install-guide.doc", 'wb') as f:
	  f.write(data)

if(shuru == 2):
	  lujing2 = os.getcwd()
	  os.chdir(lujing2)
resp2 = requests.get("https://raw.githubusercontent.com/redapple0204/my-boring-python/master/tmp/version-stable-link")
data = urllib.request.urlopen(resp2).read()
with open("arch-install-guide.doc", 'wb') as f:
	     f.write(data)

>Traceback (most recent call last):
  File "1.py", line 14, in <module>
    data = urllib.request.urlopen(resp).read()
  File "/usr/lib/python3.4/urllib/request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 447, in open
    protocol = req.type
AttributeError: 'Response' object has no attribute 'type'

**Comment by lizongzeshunshun** [comment]
待我回去看看

**Comment by lizongzeshunshun** [comment]
回去我用go写一个

**Comment by redapple0204** [comment]
@lizongzeshunshun 终于可以了！！！
小细节害死人！！！！

**Comment by lizongzeshunshun** [comment]
Advice:

Use just one file for this

@redapple0204
