### ISSUE TITLE
请问如何让arch离线安装（在安装的时候找不到无线网卡）

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#6]
@K-Guan

**Comment by K-Guan** [comment]
表示不知道，看看Arch Wiki。

**Comment by redapple0204** [comment]
@K-Guan 好的

**Comment by K-Guan** [comment]
然后，以后别什么事情都找我。先 Google 。中文找不到用英语。比如 *How to install Arch Linux offline?* 。实在找不到答案再找我。

**Comment by redapple0204** [comment]
@K-Guan 好的

**Comment by redapple0204** [comment]
@K-Guan 刚刚找了一下archwiki，他说不是要用wifi就是要有线网

**Comment by K-Guan** [comment]
刚刚 Google 了下，听说 [**Archboot**](https://wiki.archlinux.org/index.php/Archboot) 能用，不过没试过。

**Comment by redapple0204** [comment]
@K-Guan 好的我看看
