### ISSUE TITLE
chat

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#60]
@redapple0204 The code...

update now

**Comment by redapple0204** [comment]
@lizongzeshunshun 提交冲突了...
另外我更新了代码

**Comment by lizongzeshunshun** [comment]
@redapple0204 syncthing is a good things
![screenshot from 2016-10-06 20-34-19](https://cloud.githubusercontent.com/assets/10304206/19152385/526345e6-8c04-11e6-9549-0bd07bb7d387.png)

**Comment by redapple0204** [comment]
@lizongzeshunshun 不错的东西...
速度如何？

**Comment by lizongzeshunshun** [comment]
@redapple0204 JUST A WORD

**SUPER-FAST**

You can install it , and it will be our WANGPAN

https://github.com/syncthing/syncthing

(release)

shu ru fa over

**Comment by lizongzeshunshun** [comment]
or you can download s

https://github.com/syncthing/syncthing/releases/download/v0.14.8/syncthing-linux-amd64-v0.14.8.tar.gz

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.OK，thx！
2.话说....mint在系统设置里不是有安装输入法的选项么？

**Comment by lizongzeshunshun** [comment]
@redapple0204 it can't work

**Comment by redapple0204** [comment]
@lizongzeshunshun 
apt-get install fcitx fcitx-googlepinyin 不行？
可能英文系统原因，我的调成英文也无法输入。

**Comment by lizongzeshunshun** [comment]
@redapple0204 NO

**Comment by redapple0204** [comment]
@lizongzeshunshun 真奇怪....fcitx启动了么？
