### ISSUE TITLE
糟糕！提交冲突

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#61]
@lizongzeshunshun

**Comment by lizongzeshunshun** [comment]
@redapple0204 yep, please let me override the changes and you can do it again

**Comment by redapple0204** [comment]
@lizongzeshunshun commits里有

**Comment by redapple0204** [comment]
@lizongzeshunshun 更新的代码有问题
>Traceback (most recent call last):
  File "download.py", line 2, in <module>
    from urllib import requests
ImportError: cannot import name 'requests'

**Comment by lizongzeshunshun** [comment]
wait

**Comment by redapple0204** [comment]
明明之前可以

**Comment by lizongzeshunshun** [comment]
this is use for **python2** instead of **python3**???

**Comment by redapple0204** [comment]
@lizongzeshunshun 已修改，中文逗号问题

**Comment by lizongzeshunshun** [comment]
@redapple0204 Why not **python3**

**Comment by redapple0204** [comment]
@lizongzeshunshun 已经是py3了....
中文逗号不识别

**Comment by lizongzeshunshun** [comment]
File "download.py", line 3
SyntaxError: Non-ASCII character '\xe6' in file download.py on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by lizongzeshunshun** [comment]
with python3

Traceback (most recent call last):
  File "download.py", line 1, in <module>
    import os,urllib.request,re,sys,requests,data
ImportError: No module named 'data'

**Comment by redapple0204** [comment]
@lizongzeshunshun pip install data

**Comment by redapple0204** [comment]
use python3

**Comment by lizongzeshunshun** [comment]
@redapple0204 should in the README

**Comment by redapple0204** [comment]
@lizongzeshunshun OK

**Comment by redapple0204** [comment]
@lizongzeshunshun add

**Comment by lizongzeshunshun** [comment]
@redapple0204 ok
