### ISSUE TITLE
import data and not used

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#63]
in download.py line 1

Why import data? it's not really used in this program.

@redapple0204

**Comment by redapple0204** [comment]
@lizongzeshunshun 哦对哦，这个data是我在测试的时候加上去的...没有具体用处。，可以删除
另外有个bug
如果输入1也会跳出请输入1或2的提示
>redapple@kali ~/Desktop> python3 download.py 
欢迎使用arch安装向导获取器
目前最新的测试版本是 codename "happymax" build 004

>目前最新的稳定版本是 2.0

>请输入您要下载的版本（1为测试版，2为稳定版）: 
1
正在下载中.....
下载完毕！请查看本目录生成的arch-install-guide-beta.doc
Error: Please enter 1 or 2

**Comment by redapple0204** [comment]
@lizongzeshunshun fixed

**Comment by lizongzeshunshun** [comment]
@redapple0204 i'm writing go version

**Comment by redapple0204** [comment]
@lizongzeshunshun thx,and please make a windows version.
