### ISSUE TITLE
please don't use space as filename

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#64]

**Comment by redapple0204** [comment]
@lizongzeshunshun 没错，我发现了这个问题
在windows下有错误

**Comment by lizongzeshunshun** [comment]
@redapple0204 and now can you fix it?

**Comment by redapple0204** [comment]
@lizongzeshunshun 好的，正好我要发布005版本了，请稍等。

**Comment by redapple0204** [comment]
@lizongzeshunshun wait，windows上有空格是可以打开的啊，打不开是因为不能有英文的双引号。

**Comment by lizongzeshunshun** [comment]
@redapple0204 
![screenshot from 2016-10-07 11-57-25](https://cloud.githubusercontent.com/assets/10304206/19178440/3f53e5ce-8c85-11e6-9901-327c9799c85c.png)

**Comment by redapple0204** [comment]
@lizongzeshunshun 我的py程序没有这个问题
检查地址是否出错

**Comment by lizongzeshunshun** [comment]
@redapple0204 NOW IT'S THIS

![screenshot from 2016-10-07 12-09-23](https://cloud.githubusercontent.com/assets/10304206/19178621/ed00563e-8c86-11e6-9762-edc6eace09be.png)

**Comment by redapple0204** [comment]
@lizongzeshunshun PY程序正常
你下载的方式不对？
