### ISSUE TITLE
Advice: Use markdown instead of .Doc

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#67]
.Doc supports lots of great feature, but it's still need some program(Eg: Office) to open it.

Markdown is easy, and doesn't need anything (exp text viewer) to open it, and more open.

If you agree to do that, I will help you to do it or I can turn the latest version to markdown after you release .Doc version if you don't argee and still write with .Doc.

@redapple0204

**Comment by redapple0204** [comment]
@lizongzeshunshun 完全支持！因为3.0版本要加入图片，如果用doc的可能会几百M!
而且新版本，旧版本的office可能会格式错乱，并且在win编辑的到我的linux上也会导致格式错乱。
