### ISSUE TITLE
ARch again

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#68]
Mint is really slow

![screenshot_2016-10-10_19-10-48](https://cloud.githubusercontent.com/assets/10304206/19234292/43c3226a-8f1d-11e6-84b8-299e997ac23e.png)

**Comment by redapple0204** [comment]
@lizongzeshunshun 是否可以用输入法？
我还想找到了解决方案
https://github.com/FZUG/repo/issues/33

**Comment by lizongzeshunshun** [comment]
@redapple0204 i will try
xfce is good

**Comment by redapple0204** [comment]
@lizongzeshunshun 先用我的向导装fcitx，在用这个解决办法试试...
xfce有点仿gnome2,但是既然有了“任务栏”还要dock干啥

**Comment by lizongzeshunshun** [comment]
@redapple0204 it's zidai by xfce.

**Comment by redapple0204** [comment]
@lizongzeshunshun 
1.真的不好看....gnome即视感了
2.另外不要看走眼了，解决办法实际是
>已解决，最终是在　/etc/profile 中加入：

>export XIM_PROGRAM=fcitx

>export XIM=fcitx

>export GTK_IM_MODULE=fcitx

>export QT_IM_MODULE=fcitx

>export XMODIFIERS="@im=fcitx"
>可以在上述软件中正常输入中文了。
>感谢楼上２位

**Comment by lizongzeshunshun** [comment]
@redapple0204 i tried, and it was not work.

**Comment by redapple0204** [comment]
@lizongzeshunshun fcitx-qt4 fcitx-qt5装了么？
我找找

**Comment by redapple0204** [comment]
@lizongzeshunshun 另外检查那三行加到那两个文件里面了么，在试试装个fcitx-sogoupinyin试试，记得注销 #常规解决办法

**Comment by redapple0204** [comment]
顺便，浏览器中可以用么？

**Comment by redapple0204** [comment]
@lizongzeshunshun and try this
https://bbs.archlinuxcn.org/viewtopic.php?id=1919

**Comment by lizongzeshunshun** [comment]
@redapple0204 github is now slow as shit. 1K/s

**Comment by redapple0204** [comment]
@lizongzeshunshun 正常，GFW扬言又要封了

**Comment by lizongzeshunshun** [comment]
@redapple0204 YES
