### ISSUE TITLE
tips

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#69]
由于最近开学，折腾arch的人也不多，该折腾的也都折腾了，还有许多人不支持本项目，所以可以放慢脚步来写了。
不着急，反正寒假出个3.0正式版即可，build我也不准备写了...
如果你有问题直接开issue来问吧。
@lizongzeshunshun

**Comment by redapple0204** [comment]
3.0写完以后也就没空弄了....他们也全是小白，不会合作来弄...
支持的人越来越少了...直接不闻不问
所以最终版本将会被定为3.0

**Comment by lizongzeshunshun** [comment]
@redapple0204 ok. Use power in other project.
