### ISSUE TITLE
请问一个关于在虚拟机安装arch的问题

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#7]
@K-Guan 今天在虚拟机安装arch的时候，在grub的时候出现了错误 error: will not proceed with blocklists. 刚刚google了一下，有的说是uuid有问题，有的说是分区表前段过小，请问到底是什么问题呢

**Comment by K-Guan** [comment]
同样 Google 了下，找到了这个： https://wiki.archlinux.org/index.php/GRUB#Install_to_partition_or_partitionless_disk

**Comment by redapple0204** [comment]
@K-Guan 哦好的非常感谢
