### ISSUE TITLE
找到了一个挺实用&好玩的项目

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#70]
@lizongzeshunshun 
[the fuck](https://github.com/nvbn/thefuck)

**Comment by lizongzeshunshun** [comment]
@redapple0204 i find it 1 month ago. however, i didn;t use it

btw, i change to gnome3

**Comment by lizongzeshunshun** [comment]
find->found

**Comment by redapple0204** [comment]
@lizongzeshunshun xfce真心不怎么好...
gnome3依然是...重量级
下次我研究下DE，看看能不能换
