### ISSUE TITLE
arch的gnome竟然默认了wayland

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#71]
刚刚滚完，反正很惊讶...好久都没有滚了
话说wayland桌面不能放东西，默默地回到了gnome on xorg....
ps:这次的gnome带来的bug也越来越多了.......
还是不滚好啊...
@lizongzeshunshun

**Comment by redapple0204** [comment]
说真的，最让我无法忍受的是....
打开压缩管理器不是用的归档管理器
竟然是......
直接解压到当前目录！
谁设计的这个垃圾玩意？？？还不能改

**Comment by lizongzeshunshun** [comment]
@redapple0204 不折腾了，换了deepin，默认有输入法，说实话这个系统做的不错，最新qq无bug运行，占用小，美观。

![20161015152305](https://cloud.githubusercontent.com/assets/10304206/19408255/50581248-92eb-11e6-8307-2744358261e1.png)

**Comment by redapple0204** [comment]
@lizongzeshunshun deepin做的真的挺好的...不过说qq没有bug也是不对的，我记得没有办法添加好友....而且容易卡死。
下午我折腾桌面环境的时候深深地被dde（deepin桌面环境）所震撼了，真的非常实用&美丽，不过....我的wineqq不能总在最前，所以最终放弃。
然后我换了cinnamon，终于明白了@K-Guan 为什么要用了，这玩意比gnome什么鬼的方便几十倍！
才算是真正符合arch的理念“A simple, lightweight distribution”
另外嘛....gnome真是反人类+bug超多（特别是到了gnome3.22以后）
~~ps：截图一张，可以看到占用内存什么的都比gnome小很多。~~
垃圾的GFW，没法发截图了

**Comment by redapple0204** [comment]
另外djjsq.cn被K了，彻底没有vpn可以用了

**Comment by lizongzeshunshun** [comment]
@redapple0204 然而昨天出了个坑爹的问题，然后我不小心改了一下/etc/passwd然后进不了系统了。所以换了fedora

**Comment by redapple0204** [comment]
@lizongzeshunshun 进live改回来不就得了....
另外，fedora也很激进，更新的不亚于arch
而且还可以装yaourt.....

**Comment by lizongzeshunshun** [comment]
![image](https://cloud.githubusercontent.com/assets/10304206/19414435/ecfdc6ca-9312-11e6-91f1-47a50a38e26c.png)

**Comment by lizongzeshunshun** [comment]
cinnamon和xfce有的一拼

**Comment by lizongzeshunshun** [comment]
内核不算新

```

jack in ~ λ uname -r
4.7.7-200.fc24.x86_64
jack in ~ λ 

```

**Comment by lizongzeshunshun** [comment]
软件库非常全，列表都有100M

**Comment by lizongzeshunshun** [comment]
顺便推荐你『思源黑体』，很好的字体

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.我直接用lts了...不追求新内核
>redapple@myarch /> uname -a
Linux myarch 4.4.24-1-lts #1 SMP Fri Oct 7 20:44:49 CEST 2016 x86_64 GNU/Linux
redapple@myarch /> 

2.cinnamon真的挺好看，gnome说了反人类。
![图片](http://imgsrc.baidu.com/forum/w%3D580/sign=4dbb2ec732292df597c3ac1d8c305ce2/85b97e315c6034a8878a5369c31349540823760f.jpg)

3.看来和arch有的一比

4.这个字体已经在使用了...不过因为wineqq的问题导致了字体有点改变。

**Comment by redapple0204** [comment]
哦对了，还有一个问题就是，nemo文件管理器重命名不明显。
都没有输入框

**Comment by lizongzeshunshun** [comment]
..

**Comment by lizongzeshunshun** [comment]
感觉fedora占用还是太大

**Comment by redapple0204** [comment]
@lizongzeshunshun 
~~换arch~~

**Comment by lizongzeshunshun** [comment]
@redapple0204

Very happy to tell you.

![2016-10-16-040436_1440x900_scrot](https://cloud.githubusercontent.com/assets/10304206/19415133/cd948f0e-9398-11e6-94d8-15f52d3c387f.png)

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.你还真用上了arch的包管理器？
2.cinnamon有一个致命的（反人类的）bug，就是qq有消息自动弹出...
所以我还是回到了gnome（备份大法好）

**Comment by redapple0204** [comment]
另外：gnome-screenshot大法好

**Comment by manateelazycat** [comment]
@redapple0204 用deepin系统吧， 你会被流畅、稳定、不折腾所震撼。 ;)

**Comment by lizongzeshunshun** [comment]
@manateelazycat deepin的缺点是软件包不全而且源速度慢, 然后我用arch换了kde plasma5,简直完爆dde
arch的更新更是..，内核已经到4.8.4了

**Comment by lizongzeshunshun** [comment]
deepin还是更新太慢，相比我还是更喜欢arch的哲学

**Comment by redapple0204** [comment]
@lizongzeshunshun 更新慢最大的好处是不会滚挂.....
@manateelazycat deepin搞的太像windows了，没什么折腾意义..
而且最近dde出了bug，qq无法置顶。

**Comment by lizongzeshunshun** [comment]
@manateelazycat 看起来您很了解haskell, 我最近也对这门语言很感兴趣，但是学习难度似乎较大，我想问的问题是：Haskell有什么实际用途，它主要用于哪些方面。谢谢

**Comment by manateelazycat** [comment]
Haskell 能垫付你传统C和OOP的编程思维， 对你在工作中的使用其他语言编程时的思维方式产生影响。
任何的函数式语言学习都会简化你编程模型的构建过程和看问题的角度。

在国内而言， 我还不知道哪一个公司在用Haskell用于公司产品。

2016-10-26 20:34 GMT+08:00 LIZONGZE <notifications@github.com>:

**Comment by redapple0204** [comment]
@manateelazycat 我想想你们提个建议
近日来我在我的一台电脑使用了deepin
不过嘛...里面的qq总是不能置顶
这个问题让我很不方便，不知何时能修复？

**Comment by manateelazycat** [comment]
QQ 主要是Wine程序做的， 他的置顶和X11非常大的不同， 很难实现。

2016-11-26 14:27 GMT+08:00 redapple0204 <notifications@github.com>:

**Comment by redapple0204** [comment]
@manateelazycat 但是15.2没有这个问题啊
难道是15.3更新了qq版本的缘故？

**Comment by K-Guan** [comment]
i3 + scrot + gnome-terminal + Chrome 乱配组合好用多了~

（QQ的话，这个不错的：http://www.linuxidc.com/Linux/2015-12/125686.htm）

**Comment by K-Guan** [comment]
![image](https://cloud.githubusercontent.com/assets/13862535/20870450/59dc8894-bac3-11e6-85f8-996b88a80b84.png)
Wine QQ窗口涉及隐私问题上下马赛克玩~

**Comment by redapple0204** [comment]
@K-Guan 1.您还真用了qq...不是不用的么
2.我觉得清风qq比较好，（您的这个方法安装qq，qq空间链接会从IE打开），另外还写了个pkgbuild：https://github.com/redapple0204/my-boring-python/blob/master/PKGBUILD-wineqq/PKGBUILD
运行截图
![2016-12-05 19-34-28](https://cloud.githubusercontent.com/assets/16254644/20883603/1043ace4-bb22-11e6-86b9-295e88c10be7.png)

3.诶，cinnamon不用了？

**Comment by K-Guan** [comment]
1. 其实也是最近才用的，QQ号你要不~

2. 诶不错哦，那我也琢磨琢磨。看来Wine越来越成熟了。

3. 卡！电脑配置低，跑Cinnamon再跑Chrome一段时间死机一次。i3就流畅多咯。

**Comment by K-Guan** [comment]
啊还有，i3配置好轻松。比方说我想设置一个快捷键嘛……打开三个程序播放一个音乐顺便执行两个脚本再用Chrome打开七八个标签页……嗯没错，一行代码解决（虽然我肯定会分成好多行）。

**Comment by K-Guan** [comment]
啊对了，PKGBUILD写的可以呀。不过我好久没写了，没法给你提意见，但是看来至少能用咯。

**Comment by redapple0204** [comment]
@K-Guan 1.好啊
2.确实，wine已经越来越成熟了，除了一些大型软件基本都可以用了，不过还有人批判wine是个毒瘤
3.cinnamon还好吧，至少没有gnome3卡，另外...i3算是窗口管理器中最大占用的吧，不是有个叫her什么的更好用？
4.那就将就着这样吧

**Comment by redapple0204** [comment]
哦对了，github首页的新手指南要怎么恢复，一不小心关掉了，感觉很不舒服。

**Comment by K-Guan** [comment]
1. 昂，要不你给我算了。
2. 毕竟不如原生好。
3. 但是窗口管理器跟桌面环境不是一个层面的，相对来说就是占用最高也比桌面环境占用的小呀。
4. 是了，然后新手指南我也不知，习惯习惯就行了。

**Comment by redapple0204** [comment]
@K-Guan 1.OK，1459966373
2.反正我是用不惯windows的...
3.我觉得mate或者lxde占用也差不多
4......

**Comment by K-Guan** [comment]
1、嗯好。
2、我现在双系统，Win10主要有个人工智能小娜也是挺好玩的。
3、噗噗，有条件还是桌面环境更用户友好些。不过窗口管理器也有操作方便的好处（前提是得熟悉快捷键操作）。

**Comment by redapple0204** [comment]
@K-Guan 嗯...我现在单奔win10了，里面的bash完全可以胜任Linux了，大部分软件（GUI也许）都可以运行。
另外嘛...窗口管理器感觉轻便些

**Comment by lizongzeshunshun** [comment]
我一个电脑w7一个arch。。。

**Comment by redapple0204** [comment]
@lizongzeshunshun arch太能折腾了，临近期末，就换回win10把，想折腾都不行
