### ISSUE TITLE
你们应该考完试了吧?

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#76]
@lizongzeshunshun

**Comment by lizongzeshunshun** [comment]
yes,什么时候来一趟?

**Comment by redapple0204** [comment]
@lizongzeshunshun 我看看明天有没有空...
你们也是这周校运会吧?

**Comment by lizongzeshunshun** [comment]
@redapple0204 不是,12月1号开始

**Comment by redapple0204** [comment]
@lizongzeshunshun 那么晚啊.....
另外:明天时间照旧.

**Comment by lizongzeshunshun** [comment]
@redapple0204 Holy SHIT!我们这边排练集体舞到6点，我简直想骂人。

请关注https://www.zhihu.com/question/52754827?guide=1

**Comment by redapple0204** [comment]
@lizongzeshunshun 我们这里闭幕也弄到了六点...
恩...我觉得翠园很奇怪，不应该把精力都集中在学习上吗？

**Comment by redapple0204** [comment]
@lizongzeshunshun 另外，现在百度云盘破解又失效了，任何方法都不行了
f**k

**Comment by lizongzeshunshun** [comment]
@redapple0204 I'll try to fix

**Comment by redapple0204** [comment]
@lizongzeshunshun 找到一个新的方法（仅限windows，暂未测试wine。）：https://github.com/Mrs4s/BaiduPanDownload
截图：
![qq](https://cloud.githubusercontent.com/assets/16254644/20432767/a7392024-addb-11e6-9d90-9f1be074d9bf.png)
