### ISSUE TITLE
KCPTun 太凶残了

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#77]
![2](https://cloud.githubusercontent.com/assets/10304206/20455776/c4c22e2e-ae9e-11e6-85b2-3353ce9c5296.PNG)

看Max Speed，发包速度一度超过~~1.2Gbps~~130Mbps

**Comment by redapple0204** [comment]
@lizongzeshunshun 我去那么快？

**Comment by lizongzeshunshun** [comment]
@redapple0204 是，

**Comment by redapple0204** [comment]
@lizongzeshunshun 话说这玩意可以加速国外的网吗？在这里访问慢的要死啊...
特别是下载，通常只有...1KB/s

**Comment by lizongzeshunshun** [comment]
@redapple0204 只能加速代理。
