### ISSUE TITLE
please release a new version every commit

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#79]
please release a new version **every commit**

Version: X.Z.M.N

tiny changes(or **build**): N
small changes: M
a few changes: Z
BIG CHANGES: X
@redapple0204

**Comment by redapple0204** [comment]
ok

**Comment by lizongzeshunshun** [comment]
besides, i still can;t use chinese on ARCH anyway

**Comment by redapple0204** [comment]
@lizongzeshunshun 我建议你安装kde，然后按照guide的方法来安装，就可以了（不需要安装
搜狗输入法）

**Comment by lizongzeshunshun** [comment]
i've installed KDE(plasma5.8+)

**Comment by redapple0204** [comment]
@lizongzeshunshun 
这些步骤都做了么？
>输入sudo pacman -S --needed --noconfirm fcitx-{im,qt5,googlepinyin,configtool}
然后在 nano ~/.xinitrc ，加入：
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"

然后输入 nano ~/.profile 
加入
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"

在　/etc/profile 中加入：（sudo nano /etc/profile）
export XIM_PROGRAM=fcitx
export XIM=fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"

**Comment by redapple0204** [comment]
还有：在输入法配置里把谷歌拼音弄到第二个。

**Comment by redapple0204** [comment]
另外，本来想要把这个pkgbuild放到aur的，但是发现清风的qq是放在百度盘上的
所以地址没法更新...
看来只好先扔在这里了。

**Comment by lizongzeshunshun** [comment]
@redapple0204 ok
