### ISSUE TITLE
中国的长城好高啊

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#81]
哎...
@lizongzeshunshun

**Comment by lizongzeshunshun** [comment]
@redapple0204
I'm using FINALSPEED + V2Ray to FQ

Speed: ~=50Mbps(5.2m/s)
u2b: 20000kbps

**Comment by redapple0204** [comment]
@lizongzeshunshun v2ray我没有服务器....
现在只好用hosts+lantern+chrome的一个插件
