### ISSUE TITLE
百度云破解已恢复

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#82]
@lizongzeshunshun 
![2016-11-27 08-51-02](https://cloud.githubusercontent.com/assets/16254644/20644804/e4eff0a6-b47e-11e6-8904-6c47f846669d.png)

**Comment by lizongzeshunshun** [comment]
ok

**Comment by lizongzeshunshun** [comment]
Do you still using TIAN WEI?

@redapple0204

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.YES
2.似乎还是没有提高速度，仍然限制在100k左右
![2016-11-27 09-25-22](https://cloud.githubusercontent.com/assets/16254644/20644906/82887c3a-b483-11e6-8c7e-d988e07c7d8b.png)

**Comment by lizongzeshunshun** [comment]
@redapple0204 i will change a method soon

**Comment by lizongzeshunshun** [comment]
@redapple0204 fixed

**Comment by redapple0204** [comment]
@lizongzeshunshun good！可以使用了。

**Comment by lizongzeshunshun** [comment]
速度如何@redapple0204

**Comment by redapple0204** [comment]
@lizongzeshunshun 快了一些吧，但总觉得不能满速

**Comment by lizongzeshunshun** [comment]
尝试多个地址@redapple0204

**Comment by redapple0204** [comment]
@lizongzeshunshun 没有地址可选...
只能说提高了50k....不只是我网速差还是插件失效了
![2016-11-27 19-21-52](https://cloud.githubusercontent.com/assets/16254644/20648035/f4d66a38-b4d6-11e6-97c4-34459ec2bed5.png)
