### ISSUE TITLE
TO DO LIST（study）for 'QMKS'

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#84]
### 重要提示：计划可以更改，可以提前完成，推后完成最多不超过5天！
fix：无需过多复习期中考试已复习过的东西。
## 11.27（周日）-12.04（周日）
- [x] 复习英语第六单元的语法
- [x] 复习数学第五章
- [x] 放松
## 12.05（周一）-12.09（周五）
- [x] **非常紧急：立刻掌握物理第五单元!**
## 12.10(周六）-12.11（周日）
- [x] 复习地理第一张第二，四节
- [x] 复习生物第七节并完成第一单元单元测试
- [x] 复习数学
- [x] 复习物理第一张
- [x] 复习历史六，七课
- [x] 背完语文
## 12.13(周二）
- [x] 复习物理第二章
- [x] 复习生物第二章
- [x] 复习物理第二章前半
- [x] 复习历史第七课
- [x] 复习历史第八课
## 12.17(周日）
- [x] 复习语文最后一单元生字词
- [x] 复习地理第二章第二节
- [x] 复习生物第四章1,2节
- [x] 复习地理第二章第一节
- [x] 复习物理第三章
- [x] 复习历史第九课,第二单元
- [x] 生物4.3,第四章全部
## 12.20（周二）
- [x] 写完数学的那张试卷
- [x] 复习历史11，12课
- [x] 搞懂昨天的地理
## 1.02（周一）
- [x] 弄完昨天的数学试卷
- [x] 背完语文古文
- [x] 写完所有历史
- [x] 做生物卷子一张
- [x] 做地里卷子一张
- [x] 做物理卷子一张
- [x] 做英语阅读&完型
## 1.03（周二）
- [x] 写完所有的语文古文&古诗&期末模拟测试
- [x] 完成物理卷子
- [x] 有空看英语
## 1.05(周四）
- [x] 英语复习
- [x] 完成生物卷子
- [x] 完成地里卷子
- [x] 复习物理
- [x] 复习历史
## 1.07(周六）
- [x] 数学
- [x] 做历史试卷x2
- [x] 做生物试卷x2
- [x] 做地里试卷x2
- [x] 做物理试卷
- [x] 全面落实语文
## 1.08（周日）
- [ ] 做语文说明文&弄名著阅读
- [ ] 你懂得
- [ ] 把数学所有的东西搞懂
- [ ] 做所有科目试卷

# 期末倒计时-----1Days

**Comment by lizongzeshunshun** [comment]
这里也写一下我的 

完成 +1分，未完成-1分

ROUND1概览 & ROUND2精确复习 & ROUND3刷题

**分数：0**

各科重要 & 紧急程度 & 复习状态 排行
历史 10 7 **ROUND1** 0%
地理 6 10 **ROUND1** 0%
生物 6 8 **ROUND2** 13%
物理 10 1 **ROUND1** 0%
语文 10 7 **ROUND1** 0%
数学 10 0 **ROUND0/0** 100%
英语 10 0 **ROUND0/0** 100%

# 2016.12.18（周一）
- [ ] 生物 - ROUND2 - 进度要求至30%
- [ ] 地理 - ROUND1 - 进度要求至50%

# 2016.12.19（周二）
- [ ] 生物 - ROUND2 - 进度要求至50%
- [ ] 地理 - ROUND1 - 进度要求至100%

# 2016.12.20（周三）
- [ ] 生物 - ROUND2 - 进度要求至70%
- [ ] 地理 - ROUND2 - 进度要求至10%

# 2016.12.21（周四）
- [ ] 生物 - ROUND2 - 进度要求至90%
- [ ] 地理 - ROUND2 - 进度要求至25%

# 2016.12.22（周五）
- [ ] 生物 - ROUND3 - 进度要求至5%
- [ ] 地理 - ROUND2 - 进度要求至50%

# 2016.12.23（周六）
- [ ] 生物 - ROUND3 - 进度要求至20%
- [ ] 地理 - ROUND2 - 进度要求至80%

# 2016.12.24（周日）
- [ ] 生物 - ROUND3 - 进度要求至45%
- [ ] 地理 - ROUND3 - 进度要求至5%

其他后面写

**Comment by redapple0204** [comment]
@lizongzeshunshun 你们学校没有作业的么....我们这里布置一大堆，根本没办法让复习进度下去

**Comment by lizongzeshunshun** [comment]
@redapple0204 在学校刷到6点写完，回家有3个小时复习

**Comment by redapple0204** [comment]
@lizongzeshunshun 嗯....最近语文老师闹停课，让我复习时间一下子增多起来
