### ISSUE TITLE
Greeting from github API

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#85]

**Comment by lizongzeshunshun** [comment]
yes!

**Comment by redapple0204** [comment]
不错不错
话说你用了什么调用api？go？

**Comment by redapple0204** [comment]
另外我觉得github真方便 在外随时可以上传修改文件。
还不用像xx国产云盘既限速还要下载客户端。

**Comment by lizongzeshunshun** [comment]
1. https://developer.github.com/v3/
2. 是啊，但是单文件有限制

**Comment by redapple0204** [comment]
1.真的好用？
2.我也没有大文件....真要发就写releases嘛 最大2G...

**Comment by lizongzeshunshun** [comment]
1. I will make a GITHUB CLIENT soon.
2. ..

**Comment by redapple0204** [comment]
@lizongzeshunshun OK。。。。
