### ISSUE TITLE
实际上，百度云破解仍然无效的

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#87]
刚刚看了速度还是不行
仔细观察得知这个工具只不过是把链接提取出来了
没有任何的加速功能
@lizongzeshunshun 
现在也没有客户端破解可用了
垃圾百度吃枣药丸

**Comment by lizongzeshunshun** [comment]
是的，要是没有GFW，百度早就Over了

**Comment by redapple0204** [comment]
@lizongzeshunshun baidu也被GFW控制的...

**Comment by redapple0204** [comment]
@lizongzeshunshun 另外，我发现了一个新的办法
https://github.com/GangZhuo/BaiduPCS
![2016-11-30 20-21-16](https://cloud.githubusercontent.com/assets/16254644/20752213/10b07fe4-b73b-11e6-89c5-d10524324645.png)
ps：能够满速，我的网速就那么快....

**Comment by lizongzeshunshun** [comment]
@redapple0204 
这和我那个是一样的原理，就是百度的pcs，只是这个加了多线程（猜测）

**Comment by redapple0204** [comment]
@lizongzeshunshun 应该是，好像可以满速...
