### ISSUE TITLE
[Review] Final Test 

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#88]
# Targets

语文 87
数学 100
英语 98
生物 49
地理 47
历史 95
物理 100

# Review Progress

Status: ***ROUND 1* - Overview**

语文 0%
数学 0%
英语 0%
地理 0%
历史 0%
生物 0%
物理 0%

**Comment by redapple0204** [comment]
总觉得物理要求好高....
这个分数在我们学校都可以全年级第一了.....
