### ISSUE TITLE
临时：音乐考试伴奏

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#89]
[艾琳艾德勒丶 - 薛之谦-《演员》原版伴奏.zip](https://github.com/redapple0204/my-boring-python/files/630938/-.-.zip)

**Comment by redapple0204** [comment]
鉴于教室里面的网络只是通过了网站劫持导致的无法上网，并且发现使用vpn可以逃过封锁
另外由于lantern的失效，所以寻找到了两个新方法
1.tunnello 浏览器插件：
[Tunnello-The-fastest-VPN-to-Bypass,-Unblock_v0.1.9.crx.zip](https://github.com/redapple0204/my-boring-python/files/630994/Tunnello-The-fastest-VPN-to-Bypass.-Unblock_v0.1.9.crx.zip)

2.vpn： 47.90.9.64（仅在紧急情况适用）//吃屎了，链接vpn浏览器就闪退，怀疑被劫持？@K-Guan 我觉得应该不是劫持，但是就是很奇怪，连接上vpn以后打开chrome过一会就崩溃，不知为啥，chrome真的很不稳定....

**Comment by lizongzeshunshun** [comment]
@redapple0204 只是封锁了部分IP吧（例如百度...），但是可以连接VPN服务器然后连接到外部服务器（怎么那么感觉像翻墙呢233）

**Comment by redapple0204** [comment]
@lizongzeshunshun 差不多这个意思，不过封锁的方式不太一样
听过罗湖网吧（CMCC），差不多这个原理。

**Comment by redapple0204** [comment]
就是多了一个“上网认证系统”

**Comment by lizongzeshunshun** [comment]
OH>..怀疑是HTTP劫持

**Comment by redapple0204** [comment]
@lizongzeshunshun yeap，说的太准确了，https就没法劫持了...
而且现在唯一的办法应该就是vpn了....

**Comment by lizongzeshunshun** [comment]
有一个方案。

自己家里搭建跳板（或者买个vps）然后用ss/v2ray连接

**Comment by redapple0204** [comment]
@lizongzeshunshun 这个勉强可以...
正好还有台空的vps，下次试试。

**Comment by K-Guan** [comment]
那个玩意，我记得叫Wifidog什么的。好像可以破解，但我没试过。

**Comment by redapple0204** [comment]
@K-Guan 我去看看
