### ISSUE TITLE
项目文件整理中

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#90]
会暂时删除项目里的所有文件，请稍后

**Comment by redapple0204** [comment]
@K-Guan @lizongzeshunshun 论git命令行真难用，昨天弄了半天都不行
最终弄个个GUI版本的弄好了...
![2016-12-10 08-01-43](https://cloud.githubusercontent.com/assets/16254644/21068765/0a4d1092-beaf-11e6-82b5-12e6473beb2f.png)

**Comment by redapple0204** [comment]
但是不管用什么办法都好，commit总是会变成1.....
9月用的命令行也是....

**Comment by lizongzeshunshun** [comment]
我试试

**Comment by lizongzeshunshun** [comment]
话说这个项目clone不下来，因为文件名有空格

**Comment by redapple0204** [comment]
@lizongzeshunshun 有空格吗？不是已经用“-”连接了？

**Comment by lizongzeshunshun** [comment]
ARCH INSTALL GUIDE1.0.doc

**Comment by redapple0204** [comment]
@lizongzeshunshun 好了....
话说windows真坑爹，对文件名要求那么多

**Comment by K-Guan** [comment]
噗……命令行很好学啊。我从来都是用命令行。有个小教程我觉得挺好玩的，我找给你看。

**Comment by K-Guan** [comment]
https://try.github.io/levels/1/challenges/1
这个了
