### ISSUE TITLE
项目中仍有空格

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#92]
请仔细检查arch向导开发版@redapple0204
thx.

**Comment by redapple0204** [comment]
@lizongzeshunshun OK了，话说windows还有不能空格这个要求？

**Comment by lizongzeshunshun** [comment]
是啊@redapple0204

**Comment by lizongzeshunshun** [comment]
还有一个

ARCH-INSTALL-GUIDE-code-name -happymax-build 003.doc

**Comment by redapple0204** [comment]
@lizongzeshunshun 1.OK了
2.话说这个GUI能直观显示commits，而且能把丢失的commits找回来（话说丢失的commits是不是在github网站上找不回来了....）....厉害了
![2016-12-12 21-28-44](https://cloud.githubusercontent.com/assets/16254644/21101065/58916abe-c0b2-11e6-8d97-1e531cbfe7d8.png)

**Comment by lizongzeshunshun** [comment]
都找的回来，都在.git目录里

**Comment by redapple0204** [comment]
@lizongzeshunshun 但是网页上就没了

**Comment by lizongzeshunshun** [comment]
还有..四个stars是什么情况...

**Comment by redapple0204** [comment]
@lizongzeshunshun 两个不明人士...我也不认识

**Comment by redapple0204** [comment]
另外，希望不要深度的人查看项目的破解crossover，上次的办法被发现给查封了...

**Comment by lizongzeshunshun** [comment]
可以从项目中移除单独保存。

**Comment by redapple0204** [comment]
@lizongzeshunshun 项目中的已经失效了，最近找到个新的，放到了releases里。
