### ISSUE TITLE
数学题

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#93]
![qq 20161214123913](https://cloud.githubusercontent.com/assets/16254644/21169793/562834e4-c1fa-11e6-82e4-f2127df982e8.png)

**Comment by lizongzeshunshun** [comment]
这个我们上课讲了

**Comment by redapple0204** [comment]
@lizongzeshunshun 没想到我们重点班竟然都不会，等下问我妈....

**Comment by lizongzeshunshun** [comment]
其实ax+n也是一样

**Comment by lizongzeshunshun** [comment]
方差手算很麻烦..

**Comment by redapple0204** [comment]
@lizongzeshunshun 手算真的好烦....
