### ISSUE TITLE
英语答案

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#95]
![qq 20161215122337](https://cloud.githubusercontent.com/assets/16254644/21211790/7b77bc8e-c2c1-11e6-93b2-1e2dd981a923.jpg)
![qq 20161215122329](https://cloud.githubusercontent.com/assets/16254644/21211791/7b9f37d2-c2c1-11e6-8e9e-c2bd04a4796b.jpg)

**Comment by lizongzeshunshun** [comment]
刚刚拍到一张放大镜呈倒立实像的珍贵照片

![img_7756](https://cloud.githubusercontent.com/assets/10304206/21211864/1e951380-c2c2-11e6-9890-d0515196d834.JPG)

看“南”字

**Comment by redapple0204** [comment]
@lizongzeshunshun 竟然真给你拍到了....照相机不也是凸透镜所以你应该站在.....
搞混了,到底站在几倍焦距内

**Comment by lizongzeshunshun** [comment]
这是倒立放大像所以f<u<2f，所以v>2f，

**Comment by redapple0204** [comment]
@lizongzeshunshun  嗯...应该就是这样了
