### ISSUE TITLE
误删了文件....

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#96]
一不小心rm掉了D盘文件,正在尝试恢复....
@lizongzeshunshun ......
![sshot-1](https://cloud.githubusercontent.com/assets/16254644/21261315/8f9c150c-c3c5-11e6-9c07-f1a192bb8331.png)

**Comment by lizongzeshunshun** [comment]
opps

**Comment by redapple0204** [comment]
@lizongzeshunshun rm设置得很不合理啊...我本来只是想删除系统的所有文件(rm -rf /)然后来恢复备份的,结果竟然把挂载的分区也给删了....还完全没有提示.

**Comment by lizongzeshunshun** [comment]
rm -rf /需要特别注意，以前有人这样做电脑直接变砖（引导分区和主板信息被删除）（那是个特定品牌的笔记本）

**Comment by redapple0204** [comment]
@lizongzeshunshun 以前我恢复备份都是先删除系统所有文件然后到live cd恢复的,这次大意了,忘记取消挂载分区....
另外这样还真能删除主板信息?难道也是和我一样的错误?

**Comment by lizongzeshunshun** [comment]
@redapple0204 那是某个特定品牌的笔记本，现在的电脑应该不会了，不会仍需避免使用rm -rf /

**Comment by redapple0204** [comment]
@lizongzeshunshun 下次我还是在live cd里面删吧,这样就不会出差错了.....
另外如果能的话我更希望Linux默认把NTFS设置为只读.

**Comment by redapple0204** [comment]
@lizongzeshunshun  终于恢复完了,恢复整整一天......
![sshot-1](https://cloud.githubusercontent.com/assets/16254644/21285417/c06c50ea-c472-11e6-9d25-ad8fc4da08e1.png)

**Comment by redapple0204** [comment]
有些文件还是乱的.....看来还需要再弄下

**Comment by lizongzeshunshun** [comment]
。。

**Comment by lizongzeshunshun** [comment]
google最新的BBR TCP拥塞控制很6

美国的vps竟然跑到了52Mbps(而且还是服务器单边加速)

**Comment by redapple0204** [comment]
@lizongzeshunshun .........
