### ISSUE TITLE
空格

### ISSUE THREAD

**Issue by lizongzeshunshun** [redapple0204/my-boring-python#97]
‘efi arch解决办法’

**Comment by redapple0204** [comment]
@lizongzeshunshun 正好在pe复制文件,特地创建了有空格的文件,没问题啊...
![sshot-1](https://cloud.githubusercontent.com/assets/16254644/21285699/1655de56-c47b-11e6-9b58-387aa518635c.png)

**Comment by redapple0204** [comment]
似乎M$也没说不能有空格.....
![sshot-1](https://cloud.githubusercontent.com/assets/16254644/21285728/0394a378-c47c-11e6-8131-718587457f63.png)

**Comment by lizongzeshunshun** [comment]
but there's trouble cloneing

**Comment by redapple0204** [comment]
@lizongzeshunshun 错误是什么?
