### ISSUE TITLE
嘻嘻

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#99]
12月22日作业
I. 完成第八课课堂同步精练grammar部分。
II. 作业本
判断正误，有错改正
1.	She hasn’t to listen to you.
2.	Did she have to follow your instructions?
3.	She’d better not to go out at night.
4.	She’d like to invite you to dinner.
5.	She can ride a bike when she was four.
6.	She won’t be able to pass the exam.
7.	She doesn’t need hand in her homework right now.
8.	She used to have lunch at school, but now she goes home for lunch.
9.  ---Must she work for 10 hours every day?   ---No, she mustn’t.
III. 在评价手册p80上完成Part c的作文。
朱：
郑彦楠没考到第三项作业，麻烦帮我通知她加上去。谢谢！

**Comment by lizongzeshunshun** [comment]
我现在开启mode了。。。

**Comment by redapple0204** [comment]
@lizongzeshunshun 我也开了....感觉压力大
